### ISSUE TITLE
Índice de componentes

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#1]
Precisamos criar o índice de componentes que irão compor a biblioteca de componentes visuais do Pilot. Vamos usar essa issue para levantar quais componentes precisam ser feitos.

**Comment by derekstavis** [comment]
Alguns exemplos:

http://ux.mailchimp.com/patterns
https://www.lightningdesignsystem.com
http://carbondesignsystem.com/components
https://standards.usa.gov/components
https://i.stack.imgur.com/c0cwf.png
http://smashinghub.com/wp-content/uploads/2014/02/style-guides-of-websites-4.png

**Comment by alexandralugli** [comment]
Componentes listados até o momento:


**HEADER**
--
- Logo
- Avatar
- Foto do perfil
- Ícone calendário
- Ícone calendário pendente
- Ícone notificação
- Ícone notificação pendente
- Notificação aberta
- Campo de busca
- Ícone de busca
 
**FOOTER**
- Logo
- Imagem PCI
 
**MENU**
- Aberto
- Fechado
- Com subitens
- Com ícone
 
**TIPOGRAFIA**
- H1
- H2
- H3
- Parágrafo
- Texto colorido
- Lista ordenada
- Lista desordenada
- Texto ativo
- Texto hover
- Texto link
 
**GRÁFICOS**
- Chart.js
- amCharts
 
**BOTÕES**
• Primários:
- Sacar
- Antecipar
- Ver transações
- Exportar
- Estornar
- Reprocessar
- Filtrar
- Aplicar
- Ver detalhes
- Editar
- Continuar
- Avançar
- Salvar alterações
- Atualizar senha
- Adicionar
 
• Secundários:
- Cancelar
- Limpar filtro
- Adicionar transação
- Editar colunas
- Salvar Filtro
- Carregar mais…
- Salvo automaticamente
- Sacar (menu)
- Antecipar (menu)
 
• Com ícones:
- Exportar
- Copiar
- Sair
- Fazer upload
- Excluir
- Adicionar
- Documentação
- Social icons: Facebook, Twitter, Linkedin
 
**TABELAS**
- Zebrada
- Com imagem
- Com editor
- Smart table
 
**FORMULÁRIOS**
- Campo de texto
- Senha
- Desabilitado
- Sucesso
- Erro
- Campo de descrição
- Campo com ícone
- Seleção
- Máscara
- Checkbox
- Radio
 
**FILTROS**
- Opções
- Recentes
- Salvos
- Período: Hoje (clica para calendário)
- Período: Hoje| 7 dias | 15 dias | 1 mês | 3 meses | 6 meses | 1 ano | calendário
- Combo: Filtro por movimentação
- Combo: Filtro por formas de pagamento
- Combo: Recebedor
- Radio: Período | Dia
 
**ÍCONES**
- Busca
- Calendário do conteúdo
- Perfil
- Seta para baixo
- Seta para baixo pequena para o menu
- Seta para cima
- Seta para a direita
- Seta para a esquerda
- Menu hambúrguer
- Seta do título voltar
- Itens por página
- Mais detalhes
- Fechar
- Sucesso
- Erro
- Informação (tooltip)
- Boleto
- Cartão de crédito
- Visão tabela
- Visão gráfico
- Tempo
- Editar
- Ajuda
- Cadeado aberto
- Cadeado fechado
 
**ALERTAS**
• Básicos coloridos - padrão:
- Sucesso
- Informação
- Atenção
- Perigo
 
• Básicos secundários:
- Sucesso
- Informação
- Atenção
- Perigo
 
• Com links:
- Sucesso
- Informação
- Atenção
- Perigo
 
• Dispensáveis:
- Sucesso
- Informação
- Atenção
- Perigo
 
**IMAGENS**
- Cartão de crédito Master Card
- Cartão de crédito Visa
- Cartão de crédito American Express
- Cartão de crédito Hipercard
- Cartão de crédito Elo
- Cartão de crédito Aura
- Cartão de crédito Diners
- Cartão de crédito Discover
- Cartão de crédito JCB
 
**CARDS**
- Com foto e texto
- Com foto, texto e link
 
**OUTROS COMPONENTES**
- Paginação
- Aba ou Switch: test / live
- Status: pago
- Status: pendente
- Calendário
- Switch: ligado / desligado
- Switch: verificar / não verificar
- Slider
- Barra de progresso
- Loading
- Passo a passo

**Comment by derekstavis** [comment]
Dei uma organizada na lista de componentes agregando o conhecimento de desenvolvimento. @alexandralugli, faltou alguma coisa?

Logomarcas:
- Pagar.me
- Twitter
- Facebook
- Linkedin
- PCI

Tipografia:
- Heading level 1
- Heading level 2
- Heading level 3
- Paragraph
- Colored Text
- Ordered Lists
- Unordered Lists
- Links (active/hover)

Components:
- Avatar
- Button
  - Primary
  - Secondary
- Input
  - With Icon
  - Password
  - Masked
- Charts
  - Pie
  - Bar
  - Line
- Sidebar
  - With icon
  - Text-only
  - Expanded
  - Collapsed
- Footer
- Table
  - Striped
  - Smart
- Switch
- Checkbox
- Radio Button
  - Vertical
  - Horizontal (tabs)
- Form Field
  - Without title
  - With description
  - With error message
- Tab Bar
- Date & Time Picker
  - Just date
  - Just time
  - Both
- Time Picker
- Alert
  - Info
  - Success
  - Error
  - Warning
  - With icon
  - With links
  - Colored
  - Disposable
- Card
  - With image
  - With links
- Slider
- Progress Bar
  - Indeterminate (loading)
- Steps

Icones:
- Event
- Notification
- Search
- Cash Withdrawal
- Anticipate
- Details
- Export
- Refund
- Reprocess
- Filter
- Edit
- Continue
- Next
- Previous
- Save
- Refresh
- Add
- Clear
- Edita Columns
- Load More
- Automatically saved
- Exit
- Documentation
- Profile
- Right arrow
- Left arrow
- Up arrow
- Down arrow
- Hamburger
- Sucess
- Error
- Informations
- Boleto
- Credit card 
- Table view
- Chart view
- Duration
- Help
- Open lock
- Closed lock
- Master Card
- Visa
- American Express
- Hipercard
- Elo
- Aura
- Diners
- Discover
- JCB

Images:
- Master Card
- Visa
- American Express
- Hipercard
- Elo
- Aura
- Diners
- Discover
- JCB

**Comment by derekstavis** [comment]
Aqui tem uma proposta da estrutura de diretórios:

```
assets
├── logos
│   ├── Pagarme
│   ├── Twitter
│   ├── Facebook
│   ├── Linkedin
│   └── PCI
├── typography
├── components
│   ├── Avatar
│   ├── Button
│   ├── Input
│   ├── Charts
│   ├── Sidebar
│   ├── Footer
│   ├── Table
│   ├── Switch
│   ├── Checkbox
│   ├── RadioButton
│   ├── FormField
│   ├── TabBar
│   ├── DateTimePicker
│   ├── TimePicker
│   ├── Alert
│   ├── Card
│   ├── Slider
│   ├── Progress
│   └── Steps
├── icons
│   ├── Event
│   ├── Notification
│   ├── Search
│   ├── CashWithdrawal
│   ├── Anticipate
│   ├── Details
│   ├── Export
│   ├── Refund
│   ├── Reprocess
│   ├── Filter
│   ├── Edit
│   ├── Continue
│   ├── Next
│   ├── Previous
│   ├── Save
│   ├── Refresh
│   ├── Add
│   ├── Clear
│   ├── EditColumns
│   ├── LoadMore
│   ├── AutomaticallySaved
│   ├── Exit
│   ├── Documentation
│   ├── Profile
│   ├── RightArrow
│   ├── LeftArrow
│   ├── UpArrow
│   ├── DownArrow
│   ├── Hamburger
│   ├── Sucess
│   ├── Error
│   ├── Informations
│   ├── Boleto
│   ├── CreditCard
│   ├── TableView
│   ├── ChartView
│   ├── Duration
│   ├── Help
│   ├── LockOpen
│   ├── LockClosed
│   ├── MasterCard
│   ├── Visa
│   ├── AmericanExpress
│   ├── Hipercard
│   ├── Elo
│   ├── Aura
│   ├── Diners
│   ├── Discover
│   └── JCB
└── images
    ├── MasterCard
    ├── Visa
    ├── American Express
    ├── Hipercard
    ├── Elo
    ├── Aura
    ├── Diners
    ├── Discover
    └── JCB
```
