### ISSUE TITLE
Mapeamento de funcionalidades

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#10]
Mapear as funcionalidades para a confecção da dashboard admin.

Etapas de mapeamento sugeridas:

- Workshop de características com OPS ( Isa pode ajudar nisso)
- Workshop de caracteristicas com Suporte (Rodrigo Amaral pode ajudar)
- Workshop com RC
- Workshop com Ativação
- Revisão de atividades que devem ser automatizadas a partir do repositório da [marreta](https://github.com/pagarme/marretinha)

**Comment by vitorvmiguel** [comment]
Issue tratada em 

https://github.com/pagarme/produtos/issues/39
https://github.com/pagarme/produtos/issues/40
https://github.com/pagarme/produtos/issues/41
https://github.com/pagarme/produtos/issues/42 
https://github.com/pagarme/produtos/issues/43
https://github.com/pagarme/produtos/issues/44
