### ISSUE TITLE
Botão de exportar detalhes da transação 

### ISSUE THREAD

**Issue by alalbux** [pagarme/pilot#1001]
Épico: https://github.com/pagarme/roadmap/issues/556

### Contexto
Para substituimos a atual dash precisamos que as funcionalidades atuais dela estejam contidas dentro do pilot, visto isso, a ideia é adicionar um botão que converta a página em PDF

### Exemplo
![screenshot from 2018-10-08 14-42-28](https://user-images.githubusercontent.com/38147979/46632585-86c1b080-cb21-11e8-85a4-1ab25790264b.png)
![screenshot from 2018-10-08 14-18-16](https://user-images.githubusercontent.com/38147979/46632586-86c1b080-cb21-11e8-9178-2681b3887db1.png)

### Descrição técnica

```
<Button 
  icon={DownloadIcon}
  onClick={onExport}
/>
```

### Requisitos e Critérios de Aceite
- [x] gerar PDF com dados detalhados da transação

**Comment by alalbux** [comment]
PDF gerado na pilot
[Pagar.me Dashboard.pdf](https://github.com/pagarme/pilot/files/2526345/Pagar.me.Dashboard.pdf)

Melhorias:
- Mudar diagramação dos dados
- Melhorar nome de arquivo gerado / Title da página

**Comment by flaviolee** [comment]
Segue o pdf rediagramado.
[layout_exportacao.pdf](https://github.com/pagarme/pilot/files/2720864/layout_exportacao.pdf)

Aqui, prints do pdf para preview:
pag 1
<img width="660" alt="pg1" src="https://user-images.githubusercontent.com/29930809/50533536-ddcc9580-0b12-11e9-864d-2493f0de354a.png">

pag 2
<img width="660" alt="pg1" src="https://user-images.githubusercontent.com/29930809/50533539-e1f8b300-0b12-11e9-8a14-d228629f79da.png">

pag 3
<img width="660" alt="pg1" src="https://user-images.githubusercontent.com/29930809/50533540-e58c3a00-0b12-11e9-80c3-3a19de675f1a.png">

**Comment by alalbux** [comment]
Fiz alguns ajustes referente a essa issue e no desenvolvimento foram visto algumas coisas que são invibializam 100% o enquadramento do layout desenvolvido pelo o @flaviolee. A principio o contexto inicial da task era reproduzir o exportar similar ao da atual dashboard. No Firefox existe um bug na renderizanção do `display: flex` o que faz com que a interface quebre e não traga todos os dados.

Exemplo: 
Layout exportado pelo firefox 62
[Pagar.me Dashboard_mozilla_boleto.pdf](https://github.com/pagarme/pilot/files/2789045/Pagar.me.Dashboard_mozilla_boleto.pdf)
[Pagar.me Dashboard_mozila_card.pdf](https://github.com/pagarme/pilot/files/2789046/Pagar.me.Dashboard_mozila_card.pdf)

Layout exportado pelo chrome
[Pagar.me Dashboard_chorme_boleto.pdf](https://github.com/pagarme/pilot/files/2789047/Pagar.me.Dashboard_chorme_boleto.pdf)
[Pagar.me Dashboard_chrome_card.pdf](https://github.com/pagarme/pilot/files/2789048/Pagar.me.Dashboard_chrome_card.pdf)


Tinha conversando com algumas pessoas e para resolver o problema do firefox teria duas opções. Uma delas refaria todo o estilo trocando todos os `display: flex` pra `display: block` mas ainda sim inviabilizaria atender o layout. E a segunda que é a que eu mais estou daria viabilidade para desenvolver o layout seria criar um container com os dados da transações que só seria renderizado quando fosse necessaria a renderizaçao e não teria os efeitos colaterais do mozilla no layout.

**Comment by rsmelo** [comment]
foi pra produção na versão https://github.com/pagarme/pilot/releases/tag/v0.9.0
