### ISSUE TITLE
Walkthrough / user onboarding de Extrato

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#1010]
https://github.com/pagarme/roadmap/issues/564

## Contexto
Precisamos pensar em como apresentaremos as mudanças na dashboard para os clientes que acessarem a nova versão.

Isso é muito importante para que ninguém se sinta perdido e evitemos proativamente abertura de tickets com dúvidas e reclamações.

## Solução ideal
- [x] Mapear as diferenças entre dash antiga e nova
- [x] Definir os pontos mais relevantes a serem exibidos em cada tela informando os seguintes pontos:
 • Benefício entregue ao usuário - É o problema que estaremos resolvendo. Ex: novo sistema de filtros para transações.
 • Como - É a explicação de como faremos isso. Ex: Mudando a forma como as transações são filtradas, simplificando o uso.
 • Onde - É a demostração prática do caminho para alcançar o objetivo desejado. Ex: explicar o uso prático dos novos filtros.
- [x] Preparar o fluxo de onboarding no appcues para Extrato

**Comment by flaviolee** [comment]
## Diferenças entre dash antiga e nova:

• Descrever

## Conteúdo para essa seção:

**Extrato**
Essa seção trata sobre seu dinheiro. Aqui você vê qual sua conta bancária registrada para receber os pagamentos, quanto você já tem de saldo para sacar (saldo atual e saldo liberado para saque) e quanto ainda está por vir (a receber) e pode ser antecipado (liberado para antecipação). Também é possível ver e controlar suas solicitações de antecipação. Na tabela de lançamentos mostramos de forma específica tudo o que entrou e saiu de dinheiro na sua conta.

**Saque**
Essa é nossa área de saque. Confira sempre se as informações da conta exibida aqui são de onde você deseja receber seu dinheiro. O funcionamento é bem simples. É só conferir seu saldo disponível, digitar um valor que esteja dentro do estipulado e confirmar seu saque. No próximo dia útil, a partir das 16 horas o valor já está na sua conta.
Você também consegue sacar seu dinheiro pelo menu lateral, clicando no botão mostrar saldo e depois em sacar.

**Antecipação**
Como num saque, é importante ter certeza que a conta bancária de destino escolhida é a correta em primeiro lugar. Depois é decidir se quer antecipar do período inicial ou final dos seus recebíveis, selecionar a data para a operação ser realizada e digitar o valor. Também é possível escolher se sua antecipação deve ir direto para sua conta bancária ou ficar disponível aqui na sua conta da Pagar.me. Ao clicar em "calcular valor" você descobre os valores reais finais de sua antecipação na aba lateral. Depois disso é só clicar no botão e confirmar sua operação.

---

Mais informações nessa issue: https://github.com/pagarme/design/issues/10

**Comment by flaviolee** [comment]
Essa issue está bloqueada aguardando o andamento dessa aqui #1051  .

**Comment by alexandralugli** [comment]
Segue sequência sugerida para a parte de extrato. Precisamos entender como vamos aplicá-la no Appcues.

![image](https://user-images.githubusercontent.com/8549244/53209426-3141f800-3619-11e9-9136-75b62f23bf0f.png)
![image](https://user-images.githubusercontent.com/8549244/53209430-37d06f80-3619-11e9-88b9-0a5ec5227e8a.png)
![image](https://user-images.githubusercontent.com/8549244/53209443-3f901400-3619-11e9-8f3f-95fb248ab142.png)
![image](https://user-images.githubusercontent.com/8549244/53209464-4f0f5d00-3619-11e9-95d5-c74f14b353cb.png)

Link para o Zeplin: https://zpl.io/aMPvLgr

**Comment by alexandralugli** [comment]
@rsmelo Queria sua ajuda para aplicar isso no Appcues. Vou abrir outra issue pra gente ver isso depois.

**Comment by rsmelo** [comment]
@alexandralugli beleza, acha que ainda tem algo a ser feito nessa issue aqui?

**Comment by suzanabueno** [comment]
Sobre como Appcues lida com isso: https://docs.appcues.com/article/232-css-selectors

**Comment by alexandralugli** [comment]
Pessoal, estou fechando essa issue e abrindo uma nova para devs.
