### ISSUE TITLE
Incluir variáveis de tradução em TransactionDetails 

### ISSUE THREAD

**Issue by alalbux** [pagarme/pilot#1015]
### Contexto
Adicionar variáveis de tradução em transactionDetails, por algum motivo quando tava sendo desenvolvido ficou de lado as tradução. Idealmente precisariamos seguir o padrão da code base e pra isso será preciso fazer um refactor dessas `strings` para `variáveis`.

### Descrição técnica

```
Vou colocar o objeto json com os dados logo menos
```

### Requisitos e Critérios de Aceite

- [ ] Mapear lugares onde está sem tradução
- [ ] Adicionar o objeto das traduções no arquivo de `translate`

**Comment by rsmelo** [comment]
duplicada da issue #1015
