### ISSUE TITLE
Botão de exportar em extrato

### ISSUE THREAD

**Issue by alalbux** [pagarme/pilot#1029]
Épico: https://github.com/pagarme/roadmap/issues/556

### Contexto
Para substituimos a atual dash precisamos que as funcionalidades atuais dela estejam contidas dentro do pilot, visto isso, a ideia é adicionar um botão de exportar que receba os dados por recebedor

### Descrição técnica
Rota: 
```js
// balanceOperations
GET 
/recipients/{recipient_id}/balance/operations.{format}?end_date={endDate}&session_id={session_id}&start_date={startDate}
```

### Requisitos e Critérios de Aceite
- [x] Criar rota no pagarme-js com endpoint da API
- [x] Adicionar botão de exportar dentro do componente de `Operations`
- [x] Exportar lista de operações em csv
- [x] Exportar lista de operações em xlsx

**Comment by alalbux** [comment]
Atualmente na dashboard são exportados quatro tipos de arquivos, o CSV, CSV (antigo), Excel, Excel (antigo)
<img width="511" alt="screen shot 2019-01-14 at 15 05 44" src="https://user-images.githubusercontent.com/38147979/51143900-d3124000-1836-11e9-831a-917ab726ab65.png">

Modelos excel: 
[PagarMe_Extrato_14_01_2019_antigo.xlsx](https://github.com/pagarme/pilot/files/2757226/PagarMe_Extrato_14_01_2019_antigo.xlsx)

[PagarMe_Extrato_14_01_2019_novo.xlsx](https://github.com/pagarme/pilot/files/2757227/PagarMe_Extrato_14_01_2019_novo.xlsx)

A ideia é unificar todos em um só relatório com dados mais intuitivos para os clientes disponivel nos formatos de CSV e XLSX vindo diretamente da API como vem o modelo de CSV "novo" e o Excel "novo"

**Comment by alalbux** [comment]
Hoje na reunião com a Patricia chegamos na ideia de um modelo ideal para balanceOperations: 

#### Colunas e valores:
- Data de operação
- Tipo da operação (movement_object,operations_status, transfer_status)
- Id da operação (balance_id, operations_id ou transfr_id)
- Id da transação (tid)
- Parcela (formato parcela/total das parcelas)
- Método de pagamento 
- Entrada bruta (float)
- Saída bruta  (float)
- Taxa de operação (float)
- Taxa de antecipação (float)
- Taxa total da operação  (float)
- Entrada líquida (float)
- Saída líquida (float)

#### Segue modelo de tabulação: 

Data da operação | Tipo da operação | Id da operação | Id da transação | Parcela | Método de pagamento | Entrada bruta | Saída bruta | Taxa de operação | Taxa de antecipação | Taxa total da operação | Entrada líquida | Saída líquida
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
28/12/2018 12:55 | Transação | 6304679 |  4717305 | - | Boleto | 39,80 | 0,00 | -3,80 | 0,00 | -3,80 | 36,00 | 0,00
28/12/2018 12:43 | Transação | 6304656 |  4717243 | 1/2 | Cartão de Crédito | 39,80 | - | -1,99 | - | -1,99 | 37,81 | -

**Comment by rsmelo** [comment]
foi pra produção na versão https://github.com/pagarme/pilot/releases/tag/v0.9.0
