### ISSUE TITLE
Conferir se resolvemos na Pilot o problema com o digito do banco na hora de estornar um boleto.

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#1043]
### Contexto
Problema detectado através de feedback do cliente no canal #feedback-cliente no Slack.
Na hora de estornar um boleto, ele precisa colocar o digito da agencia, e isso varia de banco para banco. A falta desse número acaba dificultando a vida do usuário, que não consegue preencher os campos corretamente por não saber qual banco precisa desse digito ou nao.

### Exemplo
Print da reclamacao do cliente:
![image](https://user-images.githubusercontent.com/29930809/49885977-b80b7500-fe1f-11e8-9fd6-20de08fd9c2a.png)

Print da thread:
![print_thread](https://user-images.githubusercontent.com/29930809/49886225-3831da80-fe20-11e8-8391-5260ece0be5d.jpg)

### Descrição técnica
Conferir se o campo está mais claro e se essa confusão é desfeita no fluxo usado na Pilot.

### Requisitos e Critérios de Aceite
- [ ] Link do layout correto no Zeplin
- [ ] Teste e validação da solução com cliente

**Comment by rsmelo** [comment]
não tivemos nenhum report sobre o assunto e a interface necessita o digito hoje
