### ISSUE TITLE
Criação de conta de usuário pós convite

### ISSUE THREAD

**Issue by suzanabueno** [pagarme/pilot#1048]
Épico: https://github.com/pagarme/roadmap/issues/555

### Contexto

Quando o cliente recebe um convite para usar a dashboard, ele clica no link enviado por email e é enviado para uma tela onde ele pode digitar a senha e criar sua nova conta de acesso.

Precisamos dessa tela na nova dashboard.

Também precisamos modificá-la, pois hoje ela permite que o email de cadastro seja modificado, e ela pede para validar o email cadastrado mesmo depois de aceitar o convite, o que é um fluxo complicado pro usuário e pouco seguro.

É importante que apenas o email usado no convite seja usado para o cadastro.

### Exemplo

![screenshot from 2018-12-21 15-14-47](https://user-images.githubusercontent.com/20975186/50354600-390af080-0533-11e9-8755-4615b999f64b.png)

### Descrição técnica

Precisamos dos seguintes itens:

#### Design
- Interface da nova tela de criação de acesso
- Novo email de convite

#### Desenvolvimento
- Tela de Convite
- Implementar novo email de convite
- Criar na API a nova lógica de cadastro com trava do email

### Requisitos e Critérios de Aceite

- [x] Usuário consegue criar novas contas a partir de convite
- [x] Cadastro é feito apenas com email cadastrado no convite
- [x] Fluxo todo tem a mesma identidade visual

**Comment by rsmelo** [comment]
@vagnervst o outro pr ja foi mergeado, pode atualizar esse =)
