### ISSUE TITLE
Implementar Chat do RC

### ISSUE THREAD

**Issue by suzanabueno** [pagarme/pilot#1050]
Precisamos implementar o SDK do Zopim para que os clientes possam entrar em contato com nosso RC através de chat dentro da Pilot.

O código deverá ser adicionado via Google Tag Manager.

Temos 2 trechos de código que precisam ser adicionados. Ambos seguem em anexo.

Um dos trechos é para ser adicionado em telas onde o usuário não está logado, ou seja, não sabemos se ele é um cliente ou não: 

[20181207_Chat_Zopim_Pagar.me_Site.txt](https://github.com/pagarme/pilot/files/2710819/20181207_Chat_Zopim_Pagar.me_Site.txt)

O outro trecho é para ser adicionado em telas onde o usuário está logado. Este código faz o chamado cair direto para o time de RC: 

[20181207_Chat_Zopim_Pagar.me_Dash.txt](https://github.com/pagarme/pilot/files/2710820/20181207_Chat_Zopim_Pagar.me_Dash.txt)

A configuração do chat em si é feita pelo RC e pela Stone. Tudo que precisamos fazer é ter essa lógica de trocar de um para outro dependendo do tipo de usuário.

**Comment by miguelssrs** [comment]
Precisa do acesso do GTM para realizar essa tarefa, certo @suzanabueno @rsmelo ?

**Comment by rsmelo** [comment]
@suzanabueno  vai ver com o RC quais cenários o chat precisa aparecer, sugriu a duvida se o chat deve aparece em:
- ambiente de teste deslogado
- ambiente de teste usuário não ativado
- ambiente de teste usuário ativado

**Comment by miguelssrs** [comment]
> falamos com rc e ficou definido que:
> 
>     * chat do rc para qualquer cliente logado e ativo não importa se está em teste ou live
> 
>     * qualquer outro caso é chat do comercial

então significa que está correto como foi implementado ou o chat do comercial é outro chat?

**Comment by rsmelo** [comment]
@miguelssrs antes não validavamos se a company está ativa, precisa adicionar esse check, hoje é apenas verificado se o usuário fez login, mas a company pode não ter sido ativada ainda

**Comment by rsmelo** [comment]
publicado na release https://github.com/pagarme/pilot/releases/tag/v0.8.0
