### ISSUE TITLE
Appcues: enviar dados para segmentação

### ISSUE THREAD

**Issue by suzanabueno** [pagarme/pilot#1051]
Para conseguirmos segmentar os usuários e assim entregar comunicação personalizada dependendo do tipo de usuário, precisamos enviar dados  de usuário para o Tag Manager, e dali replicar os dados para os SDKs instalados.

Nosso objetivo de negócio é poder segmentar das seguintes formas:
- Usuários novos e recorrentes
- Empresas novas e recorrentes
- Específico para uma empresa ou usuário
- Específico para um tipo de status de empresa
- Mencionar nome da empresa e de usuário para personalizar comunicações

Portanto, aqui precisaremos tanto rever o que está sendo enviado ao Tag Manager, quanto ajustar o Appcues em si para receber os dados.

Coloquei ambos itens na mesma issue pois um deles é muito pequeno para merecer a própria issue.

------
## Parte 1: Revisão do envio de dados para o Tag Manager

Os dados necessários para segmentação são:

- Nome do usuário
- Email do usuário
- User ID
- Company ID
- Nome da Company
- Data de Criação da Company
- Data de Criação do Usuário
- Status da Company
- Tipo de acesso do usuário (read, write, admin)
- Ambiente da sessão (live/test)

Estes dados precisam ser configurados na Pilot para envio como variáveis ao Tag Manager.

Segundo papo no canal Tech, temos chamadas de API para puxar estes dados. Ver conversa no link: https://pagarme.slack.com/archives/C046UDH94/p1545935553200800

## Parte 2: Envio de dados ao AppCues e ajuste de config

Feito a Parte 1, temos algumas coisas para ajustar na configuração do AppCues dentro do Tag Manager.

A primeira é que precisamos checar se ele está "trigando" quando troca de página. Como a pilot é um SPA, pode ser que tenhamos que usar o "History" ao invés do "All Pages" como trigger.

Também vale ler: https://docs.appcues.com/article/389-single-page-applications-spas

A segunda é que precisamos configurar o Appcues para receber todos esses dados que estamos enviando. 

Como no Appcues tudo é ligado ao usuário, dados de Company precisam ser enviados como se fossem do usuário em si.

Para isso, conferir este artigo: https://docs.appcues.com/article/47-user-properties-overview

Importante: Datas precisam ser enviadas no formato YYYY-MM-DD

## Checklist

- [x] Enviar dados da Pilot para o Tag Manager e configurar variáveis
- [x] Configurar Appcues para receber as variáveis configuradas

**Comment by rsmelo** [comment]
No passo 1 de envio dos dados, na verdade cada sdk tem sua forma de triggar isso, atualmente enviamos pra cada uma delas quando necessário. 

Porem é relativamente simples adicionar novos campos se estes ja estiverem sendo devolvidos nas requests, caso ainda não sejam devolvidos nas requests existentes pode ser um pouco mais trabalhoso mas nada muito complexo.

**Comment by rsmelo** [comment]
validei na master da pilot todos os campos que a @suzanabueno  listou ja retornam nas requests:


- [x] Nome do usuário
- [x] Email do usuário
- [x] User ID
- [x] Company ID
- [x] Nome da Company
- [x] Data de Criação da Company
- [x] Data de Criação do Usuário
- [x] Status da Company
- [x] Tipo de acesso do usuário (read, write, admin)

**Comment by rsmelo** [comment]
@suzanabueno  faz sentido mexer nessa issue ja? ou esperamos liberar o WIP atual?

**Comment by suzanabueno** [comment]
@rsmelo podemos jogar ela na fila!

**Comment by suzanabueno** [comment]
@rsmelo 
> validei na master da pilot todos os campos que a @suzanabueno listou ja retornam nas requests:
Esses dados retornados já são enviados como variáveis de Tag Manager?

**Comment by rsmelo** [comment]
> Esses dados retornados já são enviados como variáveis de Tag Manager?

@suzanabueno não, atualmente poucos são enviados, mas eles ja retornam nas requests feitas na api no fluxo de login então é bem facil passar eles pro gtm e demais sdks

**Comment by rsmelo** [comment]
a parte referente ao triggar eventos em troca de pagina foi separada em uma nova issue #1085

**Comment by rsmelo** [comment]
foi pra produção na versão https://github.com/pagarme/pilot/releases/tag/v0.9.0
