### ISSUE TITLE
Adicionar status `analyzing` na statusLegends

### ISSUE THREAD

**Issue by alalbux** [pagarme/pilot#1054]
### Contexto
É necessário adicionar o status `analyzing` que vem atráves da api, atualmente quando é exibido porque está acontecendo uma quebra de interface na lista de transações

### Exemplo
![screen shot 2019-01-10 at 15 52 36](https://user-images.githubusercontent.com/38147979/50989846-96251100-14f7-11e9-99c0-fbad3c96febc.png)

### Descrição técnica
```
  analyzing: {
    color: '#0b6e69',
    text: 'Em análise',
    acronym: 'EA',
  },
```

### Requisitos e Critérios de Aceite
- [x] adicionar na lista de labels
- [ ] adicionar traduções

**Comment by rsmelo** [comment]
publicado na release https://github.com/pagarme/pilot/releases/tag/v0.8.0
