### ISSUE TITLE
Cenários extras de antecipação na tela de Extrato

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#1063]
### Contexto
O @Fausto-Junior chamou minha atenção para alguns cenários de antecipação que não estão no layout para a tela de extratos. Precisamos analisar e implementar de acordo com o previsto no protótipo.

### Exemplo
Print de detalhe do prototipo: ![image](https://user-images.githubusercontent.com/29930809/51266178-ac244d00-19a1-11e9-8ffc-ede46b3320c8.png)

### Descrição técnica
Desenhar os cenários no layout, caso precise de mudanças grandes e desenvolver esses cenários com as variações de informação.
Os cenários novos são:
• Quando não existe modelo liberado para antecipação
• Quando já antecipou tudo que podia
• Quando possui antecipação automática

### Requisitos e Critérios de Aceite
- [x] Layouts do cenário para quando não há um modelo de antecipação
- [x] Layout para quando o cliente já tiver antecipado tudo que podia
- [x] Layout para quando o cliente possuir antecipação automatica

**Comment by flaviolee** [comment]
Cenários validados e já desenhados.

Layout do cenário para quando não há um modelo de antecipação
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5c4610280c6b0938574fd761

Layout para quando o cliente já tiver antecipado tudo que podia
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5c461027b09a3dbffc66e943

Layout para quando o cliente possuir antecipação automatica
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5c461026b09a3dbffc66e7ba

**Comment by alexandralugli** [comment]
Cenários no Zeplin. Falta um outro cenário em que o cliente não possui modelo de antecipação ou ela está bloqueada, mas ele acessa diretamente pela url, vamos fazer um empty state. Vou abrir em outra issue.
