### ISSUE TITLE
Alerta ao cliente sobre a validade do token de captura

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pilot#1065]
### Contexto
O atual fluxo de captura manual não exibe o botão de captura caso o token gerado pelo Checkout tenha vencido. Este é o comportamento esperado porém falta feedback ao usuário que espera que o botão esteja sempre ali simplesmente pelo fato da transação estar autorizada.

### Exemplo
![image](https://user-images.githubusercontent.com/18339615/51407601-78812880-1b43-11e9-8b7e-08e62d31b071.png)

### Descrição técnica
Na página de detalhes da transação, podemos verificar pela capability `isCapturable` e também pela propriedade `referer`, fazendo um alerta ser exibido ao cliente caso eles estejam da seguinte forma:

- referer: `encryption_key`
- isCapturable: `false`

### Requisitos e Critérios de Aceite
- [ ] Alerta na página de detalhes da transação deve ser exibido após as 5 horas de validade do token

**Comment by suzanabueno** [comment]
Precisamos entender com FinOps como funciona o processo de captura, como essa autorização é abandonada, e se isso aqui é algo que precisamos resolver mais profundamente. Não parece ser algo apenas no frontend.

**Comment by rsmelo** [comment]
verifiquei com ops e existem dois casos de transações que foram autorizadas e não capturadas:
- **transação criada com ek (checkout)**: 
  - tempo pra captura: 5 horas
  - o `probe` roda e atualiza os status das transações expiradas para `refused` com o motivo de `capture timeout`
  - o @vagnervst tinha levantando que conseguiu capturar após 5 horas, temos que verificar, talvez o `probe` não rode no ambiente de teste
- **transações criadas com api key**:
  - tempo de captura: 5 dias
  - essas não são pegas pelo `probe`, ficam como `autorizado` para sempre. Porem o tempo do captura do banco é 7 dias e ele libera o saldo autorizado depois desse tempo

**Comment by rsmelo** [comment]
não tem nada a ser alterado na pilot
