### ISSUE TITLE
Extrato - ID do recebedor não é mantido no segundo acesso

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pilot#1074]
### Contexto
Ao clicar duas vezes no botão de acesso à página de extrato, somos redirecionados para a rota `/balance/:id`, gerando erro na identificação do recebedor.

### Exemplo
![image](https://user-images.githubusercontent.com/18339615/51624366-d0dc6f80-1f21-11e9-98df-8ff5d8eb1b71.png)

### Requisitos e Critérios de Aceite
- [x] Manter o ID do recebedor ao re-acessar a página de extrato

**Comment by rsmelo** [comment]
Verifiquei que esse problema na verdade é devido ao comportamento da Sidebar. Atualmente sempre que é clickado em um item da sidebar ela faz o redirecionamento. O ideal seria garantir que para items que já estão ativos ou que a rota deu match não seja feito o `historu.push` novamente
