### ISSUE TITLE
Criar fallback de erro para detalhes de transação

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1077]
### Contexto

Hoje quando há algum status novo vindo para a tela de detalhes de transação acabamos recebendo uma série de erros que normamente estão atrelados aos modelos que utilizamos, um bom exemplo de erro é o da issue #1067. 
A proposta é criarmos um fallback default para este tipo de erro que possa realmente ser útil e não quebrar a interface de detalhes de transação.
### Exemplo

![image](https://user-images.githubusercontent.com/1773766/51925570-7e45fc00-23d6-11e9-97f9-1908cb1bce00.png)

### Requisitos e Critérios de Aceite

- [ ] Criar um meio de evitar quebras de interface graves na tela de detalhes de transação.

**Comment by rsmelo** [comment]
- no momento corrigir para que em transações de cartão de credito que não existe detalhes de recebedores o card não ser exibido
- em um segundo momento podemos ver com o o time de ux se é necessário adicionar algum outro feedback

**Comment by rsmelo** [comment]
foi pra produção na versão https://github.com/pagarme/pilot/releases/tag/v0.9.0
