### ISSUE TITLE
Criar componente printable crossbrowser

### ISSUE THREAD

**Issue by alalbux** [pagarme/pilot#1080]
### Contexto
Como alinhado em algumas reuniões ideialmente pra cobertura de todos os browser na exportação do PDF de detalhes de transação. Atualmente o exportar que está sendo gerado não atende as necessidades visuais necessárias. Esse componente poderá ser usado em outras partes da pilot pra exportação de dados em PDF.

### Exemplo
Referência https://github.com/pagarme/pilot/issues/1001

### Descrição técnica

```
<Printable 
  ... props
/>
```

### Requisitos e Critérios de Aceite

- [ ] Criar componente reutilizável em outras páginas da pilot
- [ ] Substituir exportação de detalhes de transação

**Comment by suzanabueno** [comment]
Não vamos fazer este ajuste na Pilot pois este problema precisa de uma solução de backend.
