### ISSUE TITLE
Extrato - Formulário de antecipação pode ser acessado sem limite

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pilot#1083]
### Contexto
O formulário de antecipação pode ser acessado mesmo quando não há payables disponíveis para antecipar, tornando "estranha" a experiência do usuário que se depara com os inputs bloqueados ao acessar o formulário.

### Exemplo
O formulário pode ser acessado tanto pela Sidebar como pela página de Extrato:

![image](https://user-images.githubusercontent.com/18339615/52288393-3e8d9000-2953-11e9-8d2c-7c3ee5c7d328.png)

### Descrição técnica
Fazer com que a Sidebar receba do Redux os limits do recebedor principal e bloquear o botão e também adicionar a mesma validação na página de extrato.

### Requisitos e Critérios de Aceite
- [ ] Formulário de antecipação é inacessível se não houver limite antecipável

**Comment by suzanabueno** [comment]
Ficou faltando para planejar: Empty State quando a pessoa acessa a antecipação diretamente pela URL.

**Comment by alexandralugli** [comment]
Esse é o cenário em que o cliente não possui valores disponíveis a serem antecipados, seja porque já antecipou todos os valores disponíveis ou porque não possui payables. Hoje não conseguimos diferenciar esses dois cenários citados porque a rota /Limits não especifica os motivos do saldo a receber disponível. 

Segue cenário abaixo:
![image](https://user-images.githubusercontent.com/8549244/52969312-a4840980-338e-11e9-8ac0-6dc776636350.png)

Link para o Zeplin: https://zpl.io/bJ7OJlW

**Comment by suzanabueno** [comment]
Acho que fica mais fácil entender se a gente usar o mesmo paradigma do saque.

Texto para usar ali:

De:
> Não há valores disponíveis a serem antecipados.

Para:
> Liberado para antecipação: R$ 0

@alexandralugli o que você pensou de explicação no (i)?

**Comment by alexandralugli** [comment]
@suzanabueno Pensei em explicar um pouco melhor os motivos possíveis de porque não existem valores a serem antecipados. Pode ocorrer o cenário em que o saldo a receber é positivo, mas não está liberado para antecipação.

Acho que podemos colocar algo como "Você não possui valores a receber ou já antecipou todos os recebíveis".

@vagnervst você sabe se tem algum cenário fora esses?

**Comment by vagnervst** [comment]
@alexandralugli Fora os que citou me lembro somente do cenário onde o recebedor já antecipou tudo o que podia de acordo com o percentual antecipavel, mas acho que esse já cai em "Você não possui valores a receber".

**Comment by rsmelo** [comment]
foi criada a issue de dev para solucionar esse problema:
- Desabilitar o botão antecipar e sacar quando não possuir limite para antecipação #1132
