### ISSUE TITLE
Extrato - Limite não é atualizado corretamente

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pilot#1084]
### Contexto
Ao acessar o formulário de antecipação, e então a partir dele acessar a página de extrato, o limite antecipável é apresentado de forma sempre zerada, exigindo que façamos o reload da página.

### Exemplo
![peek 2019-02-05 14-39](https://user-images.githubusercontent.com/18339615/52288749-e3a86880-2953-11e9-8c15-a9f25e317155.gif)

### Requisitos e Critérios de Aceite
- [ ] Limite disponível para antecipação é recalculado ao acessar de qualquer lugar a página de extrato

**Comment by rsmelo** [comment]
publicado a versão https://github.com/pagarme/pilot/releases/tag/v0.10.1
