### ISSUE TITLE
Tela inicial enquanto não temos a home

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1100]
**Contexto**
A tela inicial deve proporcionar ao usuário uma jornada e funcionalidades para completar suas tarefas prioritárias, além de proporcionar conteúdo que atende as suas expectativas.

Atualmente, a primeira tela que aparece para o usuário após o login é a tela de transações. Essa seção só ficou como tela inicial por sequência de desenvolvimento.

**Possível solução**

Enquanto a home não estiver em produção para o clientes, vamos trocar a tela inicial de Transações para Extrato. Dessa forma conseguimos informar o usuário sobre a situação financeira da empresa e dar um ponto de partida mais claro a eles.

**Comment by Deivis** [comment]
Done !
