### ISSUE TITLE
Antecipação - Empty state

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1105]
**Contexto**

Existem alguns cenários que impedem os usuários de antecipar o saldo a receber. São eles:

• Quando não existe modelo liberado para antecipação;
• Quando já antecipou tudo que podia;
• Quando possui antecipação automática;
• Quando não possui payables.

Para esses cenários foram criadas medidas que impossibilitam os usuários de prosseguirem no fluxo (#1063 e #1083), porém existem casos em que o cliente acessa a tela de antecipação diretamente pela URL.

**Solução**
Criar um empty state na tela de antecipação com uma mensagem que informe o motivo da restrição.

**Comment by alexandralugli** [comment]
![image](https://user-images.githubusercontent.com/8549244/53035652-b29c5d80-3454-11e9-83d9-d976e24042f9.png)

Link para o Zeplin: https://zpl.io/anprxBA

**Comment by rsmelo** [comment]
criada a issue para desenvolvimento #1109
