### ISSUE TITLE
Criar meio de tratar erros desconhecidos

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1117]
### Contexto

Hoje nossos components precisam tratar todo tipo de erro vindo da api, muitos destes acabam gerando erros ou mensagens de alerta como a descrita no exemplo abaixo de extrato. 
A proposta é criarmos um componente que centralize estes erros e gere um retorno mais agradável para o usuário.
### Exemplo

Erro de extrato quando não encontra um recebedor adequado.
![screen shot 2019-02-28 at 13 43 16](https://user-images.githubusercontent.com/1773766/53582757-dd766800-3b5e-11e9-9a23-b8d061fc8f81.png)
Erro de acesso a configurações sem um recebedor configurado
![error configurations without recipient](https://user-images.githubusercontent.com/1773766/53583006-68eff900-3b5f-11e9-9313-f0d7de63a9c8.gif)

### Descrição técnica

Criar um componente de alta ordem (`HOC`)  que tenha capacidade de capturar e tratar os erros ocorridos nas páginas devido a chamadas na API ou demais quebras de interface.

### Requisitos e Critérios de Aceite

- [x] Tratar erros gerados nos componentes filhos
- [x] Gerar respostas de acordo com os erros recebidos

**Comment by alexandralugli** [comment]
Estou listando abaixo alguns cenários de erros ou empty states que podem ocorrer para conferirmos se não está faltando nenhum. Se lembrarem de mais algum, vão adicionando também, por favor.

Lembrando que junto a mensagem de erro devemos sempre oferecer um call to action como saída para o usuário.

**Geral**
- [ ] 404, página não encontrada
  Mensagem em desenvolvimento
  CTA: ir para a seção inicial

- [ ] Sessão expirada
   Mensagem: Sessão expirada
   CTA: Faça o login para acessar sua conta

- [ ] Não possui recebedor configurado
  Mensagem: Você não possui um recebedor padrão configurado para esse ambiente.
  CTA: Configure um recebedor

**Transações**
- [ ] Não foram encontradas transações para os filtros estabelecidos
   Mensagem: Não foram encontrados resultados para essa busca
   CTA: Tente novamente com outros filtros

- [ ] Ainda não possui nenhuma transação
  Mensagem: Você ainda não possui nenhuma transação

- [ ] Adicionar transação:
  Mensagem: Você ainda não adicionou nenhum produto
  CTA: Utilize a ferramenta acima para adicionar um ou mais produtos


**Extrato**

- [ ] / Antecipação: Cliente acessou diretamente pela url, mas não possui valores disponíveis
  Mensagem: Não há valores disponíveis a serem antecipados.
  CTA: Voltar para o extrato

- [ ] / Antecipação / Saque: Erro de api
  Mensagem: Desculpe! Algo deu errado em nossa plataforma e não pudemos prosseguir. Fique tranquilo, seu dinheiro continua seguro com a gente.
  CTA 1: Tentar novamente
  CTA 2: Sair

**Comment by suzanabueno** [comment]
Textos em tabela: https://docs.google.com/spreadsheets/d/1YhWXorAjJ9aEUnRltLaRXvCKpGiLEaBdkuTNVTl-R_w/edit#gid=0

Estou revisando.

**Comment by vagnervst** [comment]
@alexandralugli Sobre o erro de `Recebedor não configurado`, o mais próximo que consegui de replicar o problema foi acessando a nossa página de Extrato em modo live, com minha company sem chave live. 

Assim a página fica em sua maior parte desabilitada:

![image](https://user-images.githubusercontent.com/18339615/55515814-e7015d00-5641-11e9-9e54-80fd455044cc.png)

Pois ao fazer uma request pra limits a API respondeu: `Limite de antecipação não pode ser calculado sem adquirente 'pagarme' neste ambiente.`

Acha que vale criar um empty state nos cards relacionados à antecipação?

**Comment by Deivis** [comment]
@alexandralugli  vamos precisar de alguns `empty-state`  novos como para este erro de transações 
![Screen Shot 2019-04-10 at 11 34 13](https://user-images.githubusercontent.com/1773766/55887817-9d0a0100-5b84-11e9-9196-5485a3be53c6.png)
😄
