### ISSUE TITLE
Erro ao gerar saque

### ISSUE THREAD

**Issue by rsoaress** [pagarme/pilot#1118]
### Contexto

Company está tentado gerar um saque pela nova dash mas está levando um erro: "Erro ao tentar sacar.". 
### Exemplo

Cliente possui saldo disponível:
![image](https://user-images.githubusercontent.com/33908218/53646548-3525d980-3c1a-11e9-92d0-70e89c3de0ab.png)

Ao receber o erro vi nos logs que a mensagem do erro é : " { "type": "action_forbidden", "parameter_name": null, "message": "Saldo insuficiente." }" .
![image](https://user-images.githubusercontent.com/33908218/53646534-2c350800-3c1a-11e9-9a2d-e33b6645d11f.png)

Buscando nos últimos 14 dias, apenas este cliente tentou fazer saque pela nova dash e em todas as tentativas ocorreu tal erro

`where("method": "POST" AND "url": "/transfers" AND "referer": "https://beta.dashboard.pagar.me/")`

Olhando nos logs de request, percebi que a request está chegando sem amount e sem recebedor:

`{
	"id":"eed01220-717d-4967-a0a9-af2b038eb2aa",
	"method":"POST",
	"url":"/transfers",
	"body":
	{
		"session_id":"*":10477
	}
}`

**Comment by rsmelo** [comment]
fiz alguns testes em ambiente de desenvolvimento e não consegui identificar o erro ainda. Ainda estamos investigando.
segue o output de um dos testes:

url:
`https://api.pagar.me/1/transfers`

payload:
```JSON
{
   "session_id":"xxxxxxxxxxxxx (apenas mudei o valor aqui)",
   "amount":50000,
   "recipient_id":"re_cja5ack8i02fkzr6e6l0d3qll"
}
```

response:
```JSON
{
   "object":"transfer",
   "id":197880,
   "amount":50000,
   "type":"ted",
   "status":"pending_transfer",
   "source_type":"recipient",
   "source_id":"re_cja5ack8i02fkzr6e6l0d3qll",
   "target_type":"bank_account",
   "target_id":"17876745",
   "fee":367,
   "funding_date":null,
   "funding_estimated_date":"2019-03-02T03:00:00.000Z",
   "transaction_id":null,
   "date_created":"2019-03-01T16:29:47.014Z",
   "date_updated":"2019-03-01T16:29:47.014Z",
   "metadata":{

   },
   "bank_account":{
      "object":"bank_account",
      "id":17876745,
      "bank_code":"063",
      "agencia":"21312",
      "agencia_dv":null,
      "conta":"213123",
      "conta_dv":"12",
      "type":"conta_corrente",
      "document_type":"cnpj",
      "document_number":"00000000000000",
      "legal_name":"CONTA BANCARIA DE TESTES",
      "charge_transfer_fees":true,
      "date_created":"2018-08-16T20:36:29.009Z"
   }
}
```

**Comment by Deivis** [comment]
Bom encontramos o erro @rsoaress, descobrimos que não fazemos o desconto do `fee` na hora de enviar a requisição de saque, vamos fazer uma `hot-fix` para este problema e assim que possível fazermos o deploy deste ajuste.

**Comment by rsmelo** [comment]
corrigido e está em produção
