### ISSUE TITLE
Erro na captura de boleto

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1121]
### Contexto

Hoje ao tentarmos capturar uma transação de boleto em produção recebemos o seguinte magnífico erro:
### Exemplo

![boelto capture error](https://user-images.githubusercontent.com/1773766/53665528-76ce7880-3c4a-11e9-96ca-19381541e857.gif)

![screen shot 2019-03-01 at 17 46 04](https://user-images.githubusercontent.com/1773766/53665443-35d66400-3c4a-11e9-81cd-3a9cd8d9b9b2.png)

**Comment by rsmelo** [comment]
verifiquei que nesse caso não faz sentido exibir o input de valor, visto que o amount passado na captura não influencia em nada no caso de boleto. O valor do boleto gerado sempre é o mesmo do valor autorizado

![Screen Shot 2019-03-13 at 11 21 51](https://user-images.githubusercontent.com/479495/54286265-3e9c3380-4582-11e9-9939-6a9f3faabe40.png)

**Comment by rsmelo** [comment]
O pull request Fix boleto capture #1136 deve resolver apenas o problema da pilot quebrando.
Verificamos a necessidade de fazer mais alterações na modal de captura de boleto porem isso será resolvido em outra issue

**Comment by rsmelo** [comment]
publicado a versão https://github.com/pagarme/pilot/releases/tag/v0.10.1
