### ISSUE TITLE
Tela de saque apresenta duas mensagens de erro para o mesmo problema

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1124]
**Contexto**

Estamos apresentando duas mensagens de erro para o mesmo problema no fluxo de saque.

**Exemplo**
![image](https://user-images.githubusercontent.com/8549244/54040810-fb6a4b00-41a4-11e9-94ea-29d1e687fb92.png)

**Solução**
Devemos apresentar uma única mensagem de erro, no modelo de empty state.
Mensagem: Algo inesperado aconteceu, mas seu dinheiro continua seguro com a gente.
CTA: Tentar novamente

**Comment by rsmelo** [comment]
repetido da #1307

**Comment by alexandralugli** [comment]
Não sei se vamos usar essa issue, mas, seguem as telas no zeplin:

https://zpl.io/VDAoKDg e https://zpl.io/VQQRQp9
