### ISSUE TITLE
Release v0.10.0 - 13/03/2019

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1125]
### Esta versão inclui:
- redirecionamento pelo botão da `Sidebar` mantém a sessão e redireciona para a homepage da Dashboard atual
- adiciona nova versão do `DateInput` nas páginas de listagem de transações, extrato e Antecipação
- adiciona empty state na pagina de antecipação
- adiciona microinteração na `Sidebar`
- corrige o comportamento do redirecionamento da `Sidebar` para items já ativos
- adiciona nova versão da exportação csv/xlsx na pagina de extrato
- corrige problema ao recarregar  pagina de extrato
- adiciona a exclusão da sessão ao efetuar logout
- alterada página inicial para Extrato

## Checklist
- [ ] testar o redirecionamento para a dashboard atual através da sidebar, deve conseguir manter o login ao redirecionar
- [ ] testar a seleção de datas por etapa em Lista de Transações
- [ ] testar a seleção de datas por etapa em Extrato
- [ ] testar a seleção de datas no formulário de antecipação
- [ ] ao acessar o formulário de antecipação sem limites à antecipar, o empty state deve ser exibido
- [ ] testar a navegação utilizando a `Sidebar`, itens já ativos não devem triggar redirecionamento
- [ ] testar a exportação de csv/xlsx de extrato, as colunas devem estar traduzidas e valores em reais
- [ ] testar o recarregamento da página de extrato, não deve acontecer o erro de company inexistente
- [ ] verificar se a sessão é destruída quando o logout é feito
- [ ] verificar se a primeira tela após o login é a de Extrato

**Comment by suzanabueno** [comment]
Dúvidas:

- Quando eu clico em Prod para ir para a dash atual, eu não continuo logada. Isso é porque o link é da RC?
- A data do filtro na tela de Transações está aparecendo em vermelho por default. Não me parece ser o comportamento padrão esperado.
- Tentei exportar transações, mas nada aconteceu. Nenhum feedback visual de erro, e não baixou.
