### ISSUE TITLE
Mensagem de feedback para saque e antecipação no sidebar

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1130]
**Contexto**

Existem alguns cenários em que o cliente não possui saldo para saque e/ou antecipação. Esses cenários foram previstos para os cards na tela de Extrato, mas não no Sidebar.

**Exemplos**

Funcionalidades saque e antecipação nos cards de Extrato e como tratamos os cenários:
![image](https://user-images.githubusercontent.com/8549244/54226039-b4998f80-44db-11e9-870e-fff858a0fb7a.png)

Funcionalidades saque e antecipação no Sidebar:
![image](https://user-images.githubusercontent.com/8549244/54226915-93d23980-44dd-11e9-99dc-40dcc8fde1d4.png)

**Problema**

Precisamos pensar nesses cenários e como trazer mensagens de feedback para o usuário que tentar acessar essas funcionalidades através do Sidebar.

**Possível solução**

Desabilitar os botões de saque e antecipação quando não houver valor disponível e um tooltip com mais informações.

**Comment by alexandralugli** [comment]
**Update**

Mudamos a lógica de informações apresentadas na subseção "mostrar saldo" do **sidebar**.

Como apresentamos os botões de ação que levam o usuário a sacar ou antecipar, achamos que faz mais sentido mostrarmos os valores disponíveis para cada ação.

Por exemplo: temos dois valores para saldo - disponível em conta e o disponível para saque. Como logo abaixo dessa informação temos o botão de saque, faz sentido mostrar o valor disponível para saque.

Para valores à receber:

Até o projeto Atlas ficar pronto, nos recomendaram a não mostrar os valores disponíveis para antecipação, tanto na tela de extrato como no sidebar, pois o cálculo acabava fazendo muitas requisições e corremos o risco de quebrar algo.

Seguindo a lógica do saque, devemos mostrar apenas o valor disponível para antecipação. Porém, até o projeto Atlas ficar pronto, vamos ocultar essa informação. Segue exemplo abaixo.

![image](https://user-images.githubusercontent.com/8549244/56926356-03a97d00-6aa8-11e9-8306-36d35080536c.png)

**Comment by miguelssrs** [comment]
> **Update**
> 
> Mudamos a lógica de informações apresentadas na subseção "mostrar saldo" do **sidebar**.
> 
> Como apresentamos os botões de ação que levam o usuário a sacar ou antecipar, achamos que faz mais sentido mostrarmos os valores disponíveis para cada ação.
> 
> Por exemplo: temos dois valores para saldo - disponível em conta e o disponível para saque. Como logo abaixo dessa informação temos o botão de saque, faz sentido mostrar o valor disponível para saque.
> 
> Para valores à receber:
> 
> Até o projeto Atlas ficar pronto, não mostraremos os valores disponíveis para antecipação, tanto na tela de extrato como no sidebar.
> 
> Seguindo a lógica do saque, devemos mostrar apenas o valor disponível para antecipação. Porém, até o projeto Atlas ficar pronto, vamos ocultar essa informação. Segue exemplo abaixo.
> 

Acho que faz sentido sim! Ficou ótimo, @alexandralugli

**Comment by Deivis** [comment]
Vale lembrar que o disponível para saque pode vir a divergir do saldo total devido as novas regras da trava de recebedores. O texto poderia ser o mesmo para o extrato e para a sodebar neste caso, para isso seria necessário mudar a frase `Liberado para saque` do extrato para `Disponível para saque`.
Desabilitar os botões é o ideal, mas não creio que uma tooltip sobre eles na sidebar seja muito bom, poderiamos desabilitar os botões e trocar a mensagem para algo como "Nada disponível para saque" (ou qualquer frase melhor 😄 )
