### ISSUE TITLE
Alterar versionamento de relatório de extrato

### ISSUE THREAD

**Issue by alalbux** [pagarme/pilot#1137]
### Contexto
Atualmente temos versões da API que não foram documentadas, precisamos unir ambas em uma única versão (2018-09-10). É necessário alterar todas as chamanda que estão com a `apiVersion('2019-02-18')` e substituir para `apiVersion('2018-09-10')`

depends https://github.com/pagarme/pagarme-core/issues/1820

### Requisitos e Critérios de Aceite

- [ ] Exportação de balance na nova versão.

**Comment by rsmelo** [comment]
está issue está bloqueada até que este PR seja mergeado #1115

**Comment by rsmelo** [comment]
virou expedite pois a versão do pagarme-core que remove a versão atual já foi para produção
