### ISSUE TITLE
Aplicação componente Truncate

### ISSUE THREAD

**Issue by alalbux** [pagarme/pilot#1138]
### Descrição técnica
Em alguns lugares na pilot se um texto exceder o tamanho da coluna na tabela, o texto será exibido excedendo o elemento pai. Portanto a ideia é implementar o componentes nos seguintes pontos da pilot.

Lista de transações no campo de email: 
![image](https://user-images.githubusercontent.com/38147979/54382803-77fe9d00-466f-11e9-915a-d1fffecd1844.png)

Modal de captura no campo de email:
![image](https://user-images.githubusercontent.com/38147979/54382948-c875fa80-466f-11e9-8601-c050ae1b2674.png)

Página de detalhes de transação no campo de email
![image](https://user-images.githubusercontent.com/38147979/54383002-e3e10580-466f-11e9-892f-b161866ee7b9.png)

depends https://github.com/pagarme/former-kit/issues/176

### Requisitos e Critérios de Aceite

- [x] Adicionar lista de transações no campo de email
- [x] Adicionar modal de captura no campo de email
- [x] Adicionar página de detalhes de transação no campo de email

**Comment by vagnervst** [comment]
Acredito que a sidebar também precisaria de quebra de linha para clientes absurdamente rico💲  igual eu:

![image](https://user-images.githubusercontent.com/18339615/54765218-e3002480-4bd7-11e9-8cbc-0223fac2d713.png)

**Comment by suzanabueno** [comment]
@vagnervst não acho que precisamos nos preocupar com a sidebar por hora.

**Comment by uselessdev** [comment]
Eu acho que a Sidebar principalmente nesses valores não deveria ter truncate, talvez diminuir a fonte pra mostrar o valor inteiro, talvez o usar o text-fit para funcionar de forma automática.

**Comment by rsmelo** [comment]
aguardando a issue pagarme/former-kit/issues/176
