### ISSUE TITLE
Data aparece vermelha com browser em outra língua

### ISSUE THREAD

**Issue by suzanabueno** [pagarme/pilot#1151]
### Contexto

Seleção de data aparece em vermelho quando você usa o browser em outra língua, como se estivesse errada.

Também aparece o nome dos meses na língua do browser, o que fica estranho considerando que a interface inteira aparece em português.

### Exemplo

![Screenshot from 2019-03-26 15-41-39](https://user-images.githubusercontent.com/20975186/55024471-b126fd80-4fdd-11e9-97bb-8bc08f1c3edd.png)

![Screenshot from 2019-03-26 15-42-31](https://user-images.githubusercontent.com/20975186/55024563-e2073280-4fdd-11e9-8c4d-f7a7dab56c97.png)

### Descrição técnica

Seletores de data tem que seguir formato de data da interface definida pela localização da dashboard, não pela configuração do browser.

### Requisitos e Critérios de Aceite

- [ ] Seletor de data não é carregado com erro
- [ ] Nomes de meses no seletor de data segue a linguagem da interface

**Comment by vagnervst** [comment]
Corrigido na issue https://github.com/pagarme/pilot/issues/972
