### ISSUE TITLE
Extrato - Verificar se o recebedor pode transferir

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pilot#1163]
### Contexto
Atualmente um recebedor sem permissão de fazer transferências consegue acessar o nosso formulário normalmente. 

### Exemplo
![Apr-04-2019 13-51-46](https://user-images.githubusercontent.com/18339615/55573700-03080b80-56e1-11e9-8ec7-893029700b5c.gif)

### Descrição técnica
Cada recebedor possui uma configuração `transfer_enabled` que deve ser levada em consideração quando tentar fazer transferências.

### Requisitos e Critérios de Aceite
- [ ] Recebedor com `transfer_enabled: false` não consegue acessar o formulário de saque

**Comment by marisamodolo** [comment]
O parâmetro se trata das transferências automáticas e não há necessidade de bloquear a tela de saque.
