### ISSUE TITLE
Adicionar popup de aviso de teste com o appcues

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1165]
### Contexto
Adicionar utilizando o appcues uma popup avisando o usuário está no ambiente de teste após o login em ambiente de teste

### Requisitos e Critérios de Aceite

- [ ] ao efetuar login em ambiente de teste uma popup informando o usuário que ele está no ambiente de teste deve ser exibida

**Comment by suzanabueno** [comment]
Texto:

> Ambiente de Testes
> 
> Use esta dashboard e as chaves de API de teste para simular sua operação e garantir que tudo funciona como esperado.
> 
> Saiba tudo que você pode fazer com a Pagar.me em: https://docs.pagar.me/

**Comment by suzanabueno** [comment]
Popup no ar. Ativado todas as vezes em que a página de Extrato é carregada.
![Screenshot from 2019-04-15 13-19-00](https://user-images.githubusercontent.com/20975186/56148655-1fc5fe00-5f81-11e9-9c18-2cd863bc9695.png)
