### ISSUE TITLE
Melhorar as labels para as telas de configuração

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pilot#1176]
### Contexto
Atualmente temos duas labels sobre configurações:

- Configurações da conta: redireciona para a tela de alteração de senha

  ![image](https://user-images.githubusercontent.com/18339615/55998414-7cc96780-5c94-11e9-9b0c-0a1be2c22f8f.png)

- Configurações: redireciona para as configurações da conta

  ![image](https://user-images.githubusercontent.com/18339615/55998420-82bf4880-5c94-11e9-8963-3b55427ef651.png)

Acredito que `Configurações da Conta` ficaria mais claro se mudássemos para `Configurações do Usuário`, assim ficaria alinhado com a nossa tela de gerenciamento de equipe:

![image](https://user-images.githubusercontent.com/18339615/55998458-b0a48d00-5c94-11e9-8189-00a1d7b89587.png)

**Comment by uselessdev** [comment]
Configurações de conta leva para as configurações de conta pessoal, o que acontece é que só temos o campo de alterar senha, configurações de usuários não é equivalente para configuração de conta.

Se formos alterar o label, faria mais sentido colocar apenas `Configurações` e então colocar uma aba para configuração de conta pessoal, porque no momento a única forma de acessar esta tela é popover.
