### ISSUE TITLE
Refactor container de extrato

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1188]
### Contexto
A nova versão do extrato exibe os dados em duas abas (`anteriores` e `a receber`).
O container de extrato deve adicionar um `TabBar` para a separação dos periodos anteriores` e `a receber` e utilizar o novo componente `BalanceOperations` para a exibição do periodo selecionado.

### Exemplo
![Screen Shot 2019-04-22 at 19 00 59](https://user-images.githubusercontent.com/479495/56534928-039e0000-6531-11e9-8471-a34bec0d13d8.png)

### Descrição técnica
- remover os componentes de `DateInput`, `BalanceSumary` e `Operations` os componentes utilizados para formatação do mesmo no layout
- utilizar o novo componente`BalanceOperations`
- adicionar o componente `TabBar` para identificação dos periodos
- gerenciar no state do container a query de cada periodo

### Requisitos e Critérios de Aceite
- [ ] o layout deve seguir o prototipo definido no zeplin https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5cb8fce9fcb28ca12ec47585
- [ ] o container de Balance deve utilizar os novos componentes desenvolvidos
- [ ] o componente deve fazer a atualização da query e url conforme o periodo (aba) selecionado 
- [ ] o componente deve gerenciar qual a aba selecionada

**Comment by vagnervst** [comment]
O PR https://github.com/pagarme/pilot/pull/1227 também resolve esta issue
