### ISSUE TITLE
Revisão de textos, rótulos e termos técnicos

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#12]
Revisão de textos, rótulos e termos técnicos

**Comment by beatriztoccis** [comment]
Foi feita uma revisão de todos os labels utilizados no wireframe. Eles estão divididos por funcionalidade (ex: botão, título, componente tabela, etc.) e apresentam sua versão antes e depois de revisados. Há também indicações informando se eles apresentam o mesmo comportamento em outras telas. 
O labels dessa planilha não são definitivos. 
[Componentes Revisados.xlsx](https://github.com/pagarme/pilot/files/1173756/Componentes.Revisados.xlsx)
