### ISSUE TITLE
Detalhes de transação - Empty state para boleto não emitido

### ISSUE THREAD

**Issue by vagnervst** [pagarme/pilot#1210]
### Contexto
Hoje podemos ter uma transação de boleto que ainda não foi emitido. Neste caso, precisamos de uma forma de empty state para exibir no card do boleto em detalhes da transação

### Exemplo
Ao acessar uma transação de boleto com status `authorized`, o card não apresenta o código do boleto e os links deixam de funcionar como esperado:

![image](https://user-images.githubusercontent.com/18339615/57104319-61cf9d80-6cfe-11e9-92d0-6852683d8cc2.png)

**Comment by miguelssrs** [comment]
Galinhada: pessoa que puxar este card, por favor checar se precisa fazer mesmo

**Comment by alexandralugli** [comment]
Ibagem:

![image](https://user-images.githubusercontent.com/8549244/61973686-02122700-afbb-11e9-8b30-a728ae6b187e.png)

Zeplin: https://zpl.io/VOxyvg8

**Comment by miglsoares** [comment]
Isso já foi resolvido, certo? @vagnervst 🤔

**Comment by miglsoares** [comment]
Já foi resolvido, galera! Acabei de testar aqui.
<img width="465" alt="Screen Shot 2019-10-14 at 15 17 04" src="https://user-images.githubusercontent.com/20358128/66773598-be320e00-ee95-11e9-9b63-464a0eeb8415.png">
