### ISSUE TITLE
Configurações - troca de API

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1215]
**Contexto**

Hoje o cliente precisa entrar em contato com RC/Suporte para mudar sua versão de API. O ideal seria o cliente/plataforma enviar direto no header da transação. No entanto não conseguimos viabilizar isso hoje.
Por esse motivo vamos colocar na Pilot a opção de mudar a versão da API do cliente.

**Possível solução**

O processo será divido em três etapas:
BackEnd - Disponibilizar a configuração da api_version através da rota de company.

FrontEnd - É necessário estar disponível na Pilot a opção de troca, visto que muito dos clientes que necessitam disso utilizam plataformas e por consequência tem pouco conhecimento de API.

Divulgação - É necessário estar bem claro o que pode acontecer caso seja alterado de forma errada a versão da API. Vale a pena ver com o time de plataformas o depara para atrelar na documentação e ter o link disponível.

**Comment by alexandralugli** [comment]
@suzanabueno Você consegue me ajudar com os textos desse bloco?

Pensei em colocar um aviso assim antes do dropdown de escola da versão: "Você pode utilizar uma versão mais recente da API para aproveitar funcionalidades novas. Mas atenção, ao mudar de versão você corre o risco de (...)

E mais embaixo: "Você poderá voltar à versão anterior a qualquer momento através do dropdown dessa seção.

Ao selecionar uma opção no dropdown, podemos abrir um modal com um texto apresentando os riscos e pedindo uma segunda confirmação.

**Comment by suzanabueno** [comment]
@alexandralugli isso já terminou?

**Comment by alexandralugli** [comment]
Sim, desculpa, esqueci de fechar a issue.

Link para o Zeplin: https://zpl.io/b6QONzW

![image](https://user-images.githubusercontent.com/8549244/60292956-9d4ca980-98f4-11e9-8a87-e6e4dd1edf51.png)
![image](https://user-images.githubusercontent.com/8549244/60292982-a50c4e00-98f4-11e9-8729-4dbc84e0e07d.png)
![image](https://user-images.githubusercontent.com/8549244/60293016-accbf280-98f4-11e9-8536-6b823405432a.png)
