### ISSUE TITLE
Criar tratativa para card de boletos não capturados

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1216]
### Contexto

Hoje boletos apenas autorizados geram o seguinte card na tela de detalhes de transações o qual acaba atrapalhando a visualização e confundindo o usuário por conta de o boleto não ter sido criado de fato por que a transação foi apenas autorizada
### Exemplo

![image](https://user-images.githubusercontent.com/1773766/57336228-8d39fa00-70fb-11e9-8758-08bcf27bcd0c.png)

### Descrição técnica

Uma soluçsolução viável é a troca deste `card` por um card que contenha uma mensagem explicando a situação para o usuário e disponibilizando um botão "Gerar boleto" que fará a captura da transação e a criação do boleto.

**Comment by alexandralugli** [comment]
Link para o Zeplin: https://zpl.io/VOxyvg8

![image](https://user-images.githubusercontent.com/8549244/57958998-21644800-78d8-11e9-92e9-498af427a0c2.png)

**Comment by suzanabueno** [comment]
Vamos usar a mesma issue para desenvolvimento. Manter na coluna de in progress que vamos puxar!
