### ISSUE TITLE
Remover service worker 

### ISSUE THREAD

**Issue by suzanabueno** [pagarme/pilot#1237]
Atualmente após o deploy da pilot ao acessar o link de deploy o cliente vê uma tela branca no primeiro acesso.
Isso só ocorre se o cliente já tiver acessado a pilot anteriormente.
Indetificamos que isso é relacionado ao cache do service worker

### o que fazer?
- atualmente o service worker não traz grandes beneficios a pilot dessa forma podemos remover o service worker para solucionar o problema de tela branca

**Comment by rsmelo** [comment]
Pesquisei em alguns repositorios open-source que tambem usam Create react app e vi que resolver o problema de tela branca após o deploy pode não ser tão simples.
Como atualmente o service worker não agrega nada para nosso usuário final acredito que a forma mais fácil de resolver esse problema no momento é remover totalmente o uso de service worker na pilot

**Comment by rsmelo** [comment]
Acredito que faz sentido esse card rodar como um standard pra proxima release ao inves de um fixed date. Visto que o problema só ocorre após um deploy, conseguimos garantir que ele não irá ocorrer até a proxima versão.
