### ISSUE TITLE
Fix no white-space de Cards do former-kit-skin-pagarme

### ISSUE THREAD

**Issue by miguelssrs** [pagarme/pilot#1240]
**🚨 Alerta 🚨: Essa issue foi modificada para não atrapalhar o fluxo de métrica de Lead Time do board do time. Porém, originalmente é um fix a ser feito no former-kit-skin-pagarme.**

### Contexto
Na `release/v0.15.0` estamos com um bugzin nos CardTitles dos Cards apresentados na Dash, o que faz o Percy alertar sempre por conta do `white-space: pre` de Cards.

### Exemplo
![white-space](https://user-images.githubusercontent.com/20358128/58187618-795ece00-7c8d-11e9-9bec-4591dcdbf4c9.gif)

### Requisitos e Critérios de Aceite
- [ ] Remover `white-space: pre` de Cards

**Comment by rsmelo** [comment]
publicado na release 1.3.1
