### ISSUE TITLE
Aplicação do Novo Logo na Pilot - Prazo 30/5

### ISSUE THREAD

**Issue by miguelssrs** [pagarme/pilot#1241]
## Contexto
Trocar logos os lugares listados.

## Checklist
- [ ] Trocar logo na área de Login
- [ ] Trocar logo na Sidebar
- [ ] Trocar favicon

### Com cores que estão atualmente na Pilot

- **Login**
Nome do arquivo: `Link_Pagamento_Pagarme_227x55.png`
Tamanho: 226x67
Cor: #37cc9a

- **Sidebar**
Nome do arquivo:`Link_Pagamento_Pagarme_227x55.png`
Tamanho: 140x67
Cor: #37cc9a

- **Favicon**
Nome do arquivo: `Favicon_Pagarme_42x42.png`
Tamanho: 42x42
Cor: #37cc9a

### Com cores da marca

- **Login**
Nome do arquivo:`Link_Pagamento_Pagarme_227x55.png`
Tamanho: 226x67
Cor: #9ec00c

- **Sidebar**
Nome do arquivo:`Link_Pagamento_Pagarme_227x55.png`
Tamanho: 140x67
Cor: #9ec00c

- **Favicon**
Nome do arquivo: `Favicon_Pagarme_42x42.png`
Tamanho: 42x42
Cor: #9ec00c

**Comment by rsmelo** [comment]
data atualizada para dia 30/05 a pedido da Ana Menes

**Comment by rsmelo** [comment]
Assets necessários para a issue.m
A Ana Nemes me passou hoje.
[Assets-dash-2.zip](https://github.com/pagarme/pilot/files/3233478/Assets-dash-2.zip)
