### ISSUE TITLE
Filter Search: Ajustar relevância do botão `Limpar filtros` 

### ISSUE THREAD

**Issue by Fausto-Junior** [pagarme/pilot#1247]
### Contexto
Hoje nosso componente de filtro `search` possui um comportamento um pouco estranho, pois o botão `limpar filtros` fica sem relevância (parece desabilitado) nos momentos onde ele mais precisa de destaque.

### Exemplo
![limpar-filtros](https://user-images.githubusercontent.com/29923036/58726140-503dec00-83b7-11e9-82ee-56e5e9075be9.gif)

### Descrição técnica
Deixar o botão `limpar filtros` com relevância sempre que um parâmetro estiver aplicado no filtro.

**Comment by alexandralugli** [comment]
Pessoal, estou adicionando mais alguns screenshots aqui pra gente mover essa issue.

Cenário abaixo: Selecionei datas específicas e status da transação. O botão `Limpar filtros` deveria estar habilitado.

<img width="1181" alt="Screenshot 2019-09-16 at 17 31 40" src="https://user-images.githubusercontent.com/8549244/64995243-1387f900-d8b1-11e9-9a74-0dcffb1c2217.png">

Após o cenário acima, eu removi o status e fechei o expansível `Mais filtros`. Sumiu a tag `estornada`, mas continuou o label `Filtrando por`:
<img width="1185" alt="Screenshot 2019-09-16 at 17 31 25" src="https://user-images.githubusercontent.com/8549244/64995326-492ce200-d8b1-11e9-8d65-1e0fa5e3f84b.png">

Após clicar no botão `Limpar filtros`, a data final permaneceu no input:
<img width="1189" alt="Screenshot 2019-09-16 at 17 35 17" src="https://user-images.githubusercontent.com/8549244/64995417-8b562380-d8b1-11e9-9581-9a4993354732.png">

**Comment by rsmelo** [comment]
repetido de https://github.com/pagarme/greenphoenix/issues/116
