### ISSUE TITLE
Truncate Hook Error

### ISSUE THREAD

**Issue by gmbarroso** [pagarme/pilot#1267]
### Context
Something is went wrong with the Truncate component. When apply to a table that demands a change of page or filter values, the state is not been updated.

### Example
![Peek 2019-05-30 13-16](https://user-images.githubusercontent.com/20197808/58647204-5e1f3e80-82dd-11e9-9f83-0bfbdfbf5f88.gif)

### Description
This started to happen when I took off  the `React.memo(Truncate)`  from the `export default consumeTheme(React.memo(Truncate))`

Maybe make some tests with the Hooks engine.

**Comment by Deivis** [comment]
Done in release v0.17.0
