### ISSUE TITLE
implementar componente DonutChartLegend

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1283]
### Contexto
Implementar o componente genérico para exibição das metricas com um grafico e lista de items

### Exemplo

![image](https://user-images.githubusercontent.com/479495/60832787-21bfe780-a193-11e9-8143-699b4674b851.png)

### Descrição técnica
```JSX
<DonutChartLegend
  title='string'
  data=[
   {
    label: string,
    color: string,
    value: number,
    listRenderer: func
   }
  ]
/>
```

### Requisitos e Critérios de Aceite

- O componente deve receber as properties definidas na descrição tecnica

**Comment by rsmelo** [comment]
foi visto que o componente MetricChart pode resolver a demanda dessa issue sendo mais generico https://github.com/pagarme/pilot/issues/1281

**Comment by uselessdev** [comment]
![donuts](https://media.giphy.com/media/TTgdzuKfMiPlOmA99ni/giphy.gif)
