### ISSUE TITLE
Construção de vocabulário controlado

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#13]
Precisamos de um vocabulário controlado de termos e linguagem financeira, para associar a documentação e oferecer ajuda/apoio ao usuário na navegação das telas de extratos e transações.

**Comment by beatriztoccis** [comment]
Vocabulário de apoio criado a partir das telas de transações e extratos

[Vocabulário Financeiro.docx](https://github.com/pagarme/pilot/files/1178105/Vocabulario.Financeiro.docx)

**Comment by mccraveiro** [comment]
@beatriztoccis Consegue compartilhar o texto direto no comentário do github? 
Fica mais acessível a todo mundo.

**Comment by beatriztoccis** [comment]
@mccraveiro tá aqui! 


Antecipação - Receber adiantado o pagamento de transações realizadas com cartão de crédito. 
Antecipadas - Parcelas que seriam recebidas futuramente, mas foram antecipadas.  
Anteriores - Movimentações de períodos anteriores ao dia de hoje.  
Antifraude - Serviço contratado pelo Pagar.me que analisa uma transação, a partir de diversas variáveis, a fim de tentar constatar se esta é genuína ou fraudulenta. 
Autorização de transação - Análise de prevenção, limite de crédito e validação dos dados do cartão pelo banco. 
Alerta de Chargeback Reapresentável - Notificação que avisa ao cliente se o chargeback recebido é passível de contestação (reapresentação) por parte do lojista. 
Assinatura - Cada assinatura que o consumidor final possui em um site de recorrência. 
A Receber - Pagamentos que serão recebidos pela loja futuramente. 
Antecipações Pendentes - Antecipações em processo de validação 

Boleto registrado - Boleto que contém obrigatoriamente o nome e CPF/CNPJ do pagador do documento. 

Chargeback - Contestação da compra feita pelo consumidor diretamente com a instituição financeira responsável pelo cartão. 
Chargeback reapresentado - Contestação do chargeback por parte do lojista, a fim de provar que a compra realizada em seu site foi genuína. 
Chargeback estornado - Quando o emissor do cartão devolve ao Pagar.me (que repassa ao lojista) o valor que havia sido revertido no chargeback alegado pelo consumidor. 
Custos / Custo total - Custo final de uma transação, com todos os descontos, taxas e cobranças somados.  
Captura de transação - A cobrança de fato do valor da transação, que nesse momento passa a ter o status pago. 
Código de autorização - Código de autorização retornado pela bandeira do cartão utilizado na compra 

Docs - Documentação do Pagar.me, composta de guias e exemplos para integração com a API. 
DOC - Documento de Ordem de Crédito. Possui limite de R$4.999,00 por dia. O valor é enviado no próximo dia útil após a solicitação. 

Entradas - Valores a serem recebidos. 
Estorno - Valor devolvido pelo lojista ao consumidor, referente a algum produto ou serviço adquirido. Em troca, o consumidor devolve o produto ou abre mão do serviço. 

Índice de Chargeback - Resultado percentual da divisão do total de transações realizadas com cartão de crédito, que sofreram chargeback, ao final de cada mês pelo total de transações realizadas com cartão de crédito ao final de cada mês.  
ID da Transação - Número de identificação do pedido do cliente com o Pagar.me. 
ID do Pedido - Número de identificação do pedido do cliente no e-commerce. 
ID da Assinatura - Número de identificação da assinatura do seu cliente. 

MDR – Menchant Discount Rate: é a taxa percentual cobrada pela intermediação de cada transação feita por cartão de crédito.
Metadado - Parâmetro que permite enviar informações adicionais sobre a transação, como o ID do pedido, tipo de produto ou serviço adquirido, etc. 

NSU - Número Sequencial Único: código identificador da transação na adquirente. 

Operadora do Cartão: Empresa ou instituição financeira que administra o cartão. 

Plano - Opção de plano em um serviço de recorrência. 
Postback - Notificações enviadas pelo servidor. Elas podem ser gerenciadas através da API do Pagar.me. 
PCI - Payment Card Industry: normas internacionais que regem a indústria de cartões. 
PSP - Provedor de Serviços de Pagamento: Solução para processamento de pagamentos online com diversas funcionalidades. 

Recebedor - Pessoas físicas ou jurídicas cadastradas na base de cada cliente como recebedores dos pagamentos transacionados pelo Pagar.me. O cliente define quem são seus recebedores, assim como sua hierarquia (primário, secundário). 
Recebível - Montante a ser recebido pelo lojista. 
Recorrência - Forma de cobrança recorrente de. O lojista define período, maneira e valor das cobranças. 
Reapresentação de Chargeback- Contestação do chargeback pelo lojista. Para que seja válido é necessário a apresentação de uma série de documentos, que comprovem a realização da compra por parte do consumidor. 

Sacar - Transferir valores disponíveis da conta Pagar.me para a conta pessoal. 
Saldo atual: Saldo de hoje na conta Pagar.me. 
Saldo anterior: Saldo do período selecionado (sempre passado) na conta Pagar.me.
Saldo a receber: Total a receber no período selecionado (futuro) na conta Pagar.me. 
Score do Antifraude - Pontuação obtida pela análise de antifraude (mínimo: 0 ; máximo: 100). Transações com pontuações iguais ou acima de 95 são recusadas. 
Serviço de Antecipação - Desconto referente a realização do serviço de antecipação. 
Split de pagamentos - Divisão dos valores das vendas de maneira customizada. Funcionalidade utilizada por Marketplace. 
Saídas - Valores debitados da conta Pagar.me: descontos, cobranças de taxas, saques realizados. 
Soft descriptor – Texto que aparece na fatura do consumidor logo após o nome da loja. Seu limite é de 13 caracteres.

TED - Transferência Eletrônica Disponível. Não tem limite de valores, o montante enviado cai no mesmo dia útil, se a operação for realizada até às 17h. 
Transferência entre recebedores - Transferência entre diferentes recebedores de uma mesma company. 
Taxa de conversão - Resultado percentual da divisão de transações capturadas pela quantidade de transações autorizadas. 
Transação - Compra realizada ou serviço adquirido pelo consumidor final. 
Total de Entradas - Soma de todos os valores a serem  ou que foram creditados na conta Pagar.me no período selecionado. Inclui antecipações. 
Total de Saídas - Soma de todos os valores que foram debitados da conta Pagar.me no período selecionado. Inclui MDR, serviços de antecipação, cobrança de gateway, antifraude e saques. 

Valor Capturado - Valor bruto de uma transação. 
Valor Líquido - Valor de uma transação após a subtração de seus custos (MDR, serviço de antecipação).
