### ISSUE TITLE
Ajustes visuais no componente TotalDisplay

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1312]
### Contexto

Dado o levantamento feito na issue https://github.com/pagarme/pilot/issues/1306 foram encontrados alguns ajustes que serão necessários no componente `TotalDisplay` devido a troca da fonte básica do projeto para `Rubik` como é descrito [nesta issue](https://github.com/pagarme/former-kit-skin-pagarme/issues/185).

### Exemplo

O componente `TotalDisplay` é largamente utilizado por outros componentes dentro de páginas como [extrato](https://zpl.io/aNzKvNN), [saque](https://zpl.io/bAWloMx) e [antecipação](https://zpl.io/bAWloMx)

#### Hoje
![image](https://user-images.githubusercontent.com/1773766/62151023-c7b7cb00-b2d5-11e9-802b-f454bd08fb99.png)

#### Ideal (considere que o sinal de positivo deve continuar na frente do valor como temos hoje)
![image](https://user-images.githubusercontent.com/1773766/62151054-de5e2200-b2d5-11e9-8a11-202611e234ee.png)

#### Opcional (considere que o sinal de positivo deve continuar na frente do valor como temos hoje)
![image](https://user-images.githubusercontent.com/1773766/62151122-fe8de100-b2d5-11e9-8b00-02082068845e.png)

### Requisitos e Critérios de Aceite

- [ ] O tamanho da fonte do texto principal deve passar de `28px` para `24px`
- [ ] A cor do texto principal deve ser `#4d4f62`(será adicionada no former-kit-skin-pagarme).
- [ ] A altura da `div` ao redor do título deve ser removdia para que ela cresça de acordo com o texto contido.

**Comment by marisamodolo** [comment]
Nesse componente, ele recebe o tamanho da fonte por props em amountSize:

https://github.com/pagarme/pilot/blob/d1e6f9968496ef1558317ef5e94e54ac1de7b0df/packages/pilot/src/components/BalanceSummary/index.js#L30-L39

do css:

https://github.com/pagarme/pilot/blob/fe6c8fe963378245d6a333340fa58fd282182b39/packages/pilot/src/components/TotalDisplay/style.css#L59-L73

O ideal seria alterar as props de todos os lugares onde o componente é chamado para `"large"` ou tornar isso um padrão no estilo do componente?

**Comment by Deivis** [comment]
Creio que apenas mudar para o tamanho `large` já seja suficiente, e assim também mantemos um pouco mais explicito qual é o tamanho utilizado no componente 😄 .
