### ISSUE TITLE
Ajustes na página de detalhes de transação derivados da troca de fonte

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1313]
### Contexto
O levantamento feito na issue #1306 nos geraram conhecimento sobre alguns ajustes necessários derivados da troca da `font-family` base do projeto da família `Assistant` para `Rubik`.

### Exemplo
As seguintes telas do zeplin descrevem nosso objetivo visual:
Detalhes da transação: 
Boleto: https://zpl.io/V49e6k0
Cartão: https://zpl.io/V0Z7Ggx

Os pontos descritos nos `Critérios de aceite` podem ser visualizados abaixo:
Boleto: 
![image](https://user-images.githubusercontent.com/46823713/67425798-2035f600-f5af-11e9-94be-f5eb245afe5b.png)
Cartão:
![image](https://user-images.githubusercontent.com/46823713/67427638-d949ff80-f5b2-11e9-99fc-888b15032290.png)

### Requisitos e Critérios de Aceite
- [x] Leve em consideração trocar o componente TotalDisplay pelo componente BalanceTotalDisplay.
- [x] Remover o icone de cartão do lado do número do cartão de crédito.
- [x] O título e o valor devem ter a cor `--color-light-noir-100`.
- [x] A fonte do número do boleto deve ter 13px.
- [x] A fonte do número do cartão e o valor deve possuir 22px e peso 600.
- [x] As legendas devem possuir 11px.

### Issues relacionadas
https://github.com/pagarme/pilot/issues/1311
https://github.com/pagarme/pilot/issues/1312

**Comment by marisamodolo** [comment]
Blocked: Esperando as atualizações no zeplin pra seguir com essa issue.

**Comment by alexandralugli** [comment]
@marisamodolo Atualizei todas as telas de detalhes da transação, de cartão e boleto. Se perceber alguma coisa faltando, me avisa, por favor!

Zeplin: https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5ab16eb8f7719b4c81ab604c

Exemplos em ibagens:

![image](https://user-images.githubusercontent.com/8549244/67235330-3f048300-f41d-11e9-9f68-91bb51c920f4.png)

![image](https://user-images.githubusercontent.com/8549244/67236324-6fe5b780-f41f-11e9-94ee-5e2c1dd57548.png)

![image](https://user-images.githubusercontent.com/8549244/67236338-770cc580-f41f-11e9-8ab7-aca9d71170ac.png)
