### ISSUE TITLE
Ícones de taxa de recusa

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1322]
**Contexto**

Na home, inserimos um card que apresenta a taxa de recusa:

![image](https://user-images.githubusercontent.com/8549244/62649072-7a1d0d00-b92a-11e9-8830-3f26ed0241fb.png)

Precisamos criar ícones para os demais motivos possíveis a serem apresentados. São eles:

- [x] manual_review // negado na revisão manual
- [x] internal_error // erro interno
- [x] acquirer // adquirente ou banco
- [x] capture_timeout // expirou o tempo de captura
- [x] acquirer_timeout //  adquirente ou banco não respondeu
- [x] invalid_capture_amount // valor de captura inválido
- [x] manual_review_timeout //  expirou o tempo de revisão manual
- [x] no_acquirer // Sem  adquirente ou banco
- [x] antifraud // Negado pelo antifraude
- [x] none // ainda não sabemos de onde vem isso* investigar

**Comment by alexandralugli** [comment]
Zeplin: https://zpl.io/25AQwNe

![image](https://user-images.githubusercontent.com/8549244/62877681-f4200e00-bcfd-11e9-8929-e9b2ac12176d.png)

**Comment by Deivis** [comment]
Para o status `none` iremos usar o icone `alert` mostrado na imagem inicial junto do título `Antifraude`.
