### ISSUE TITLE
Quando clica no preset de período no filtro de data do extrato, ele popa a data pro fim e não pro começo

### ISSUE THREAD

**Issue by suzanabueno** [pagarme/pilot#1333]
## Problema

Quando clica no preset de período no filtro de data do extrato, ele popa a data pro fim e não pro começo

### Passos de reprodução

1. Entre na área de extrato
1. Clique no filtro de data
1. Clique no preset de Período
1. Veja que o seletor de data saiu do início e foi para a data de fim

### Comportamento Esperado

Sempre que um filtro é alterado, a seleção precisa retornar para a data de início e não para a de fim.

## Definição de Pronto

- [ ] Problema corrigido

**Comment by rsmelo** [comment]
@vagnervst foi lançada release 1.7.3 do former-kit com o fix do focus, só bumpar ele na pilot ja resolve o problema?

**Comment by vagnervst** [comment]
@rsmelo Isso! Fazer o bump já deveria resolver este problema na Pilot, o que fiz no PR acima :point_up:
