### ISSUE TITLE
Rever ordem de colunas de Transações

### ISSUE THREAD

**Issue by suzanabueno** [pagarme/pilot#1342]
### Contexto

Há um tempo, conversamos com o RC sobre as colunas que aparecem em Transações. Levantamos o seguinte: 

> - Motivo de Recusa nunca aparece direito
> - Mostra valor capturado, mas não mostra autorizado, fica uma confusão danada
> - Link de boleto em transação de cartão? não tem que mostrar
> - Bandeira em transação de boleto não tem que mostrar

Além de modificar o que vamos na issue #1341 o que resolve os pontos 3 e 4, precisamos entender se as colunas que temos hoje são as que precisamos ter mesmo. 

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ]

**Comment by alexandralugli** [comment]
Os testes de usabilidade foram realizados com as seguintes colunas:
Status | ID da transação | ID do pedido | Data/hora | Nome | CPF/CNPJ | Formas de pagamento | Valor capturado | Custos | Valor líquido 
Todos os clientes ficaram satisfeitos e relataram não ter nenhuma dúvida a respeito dessas colunas. PS: não haviam linhas expansíveis nesses protótipos.

Passado algum tempo de uso, juntando feedbacks como os da descrição e observando alguns padrões de uso, chegamos ao modelo abaixo:

Status | Data/hora | ID da transação | Nº do pedido | Nome | Forma de pagamento | Valor da transação (valor autorizado).

Vou colocar como exemplo de tabela no Zeplin e adiciono link aqui depois.

**Comment by alexandralugli** [comment]
Aplicação na tela:

![image](https://user-images.githubusercontent.com/8549244/65082906-7a72e400-d97d-11e9-88e1-52e4e3970005.png)

**Comment by rsmelo** [comment]
vimos que a coluna `id do pedido`é mais complexo do que o esperado devido a flata de padrão então a @alexandralugli propos as seguintes colunas
![image (7)](https://user-images.githubusercontent.com/479495/65187407-33025b80-da42-11e9-913d-525ce3872cbd.png)
