### ISSUE TITLE
Adicionar onboarding na pilot

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1354]
### Contexto

Precisamos adicionar um meio de guiar nosso usuário pela Pilot em seu primeiro acesso
e em novas features disponibilizadas. Para isso usaremos o Appcues que nos fornece a possibilidade de criarmos tutoriais baseados em destaques e alertas sobre a nossa aplicação.

### Exemplo

Os exemplos estão todos no seguinte link da seção `Onboarding` do Zeplin
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4?seid=5d640f67a2daef5e3ddd243e

### Descrição técnica

Para que o Appcues encontre os espaços nos quais ele vai aplicar o destaque ou as mensagens é necessário que marquemos estes campos com alguns nomes ou identificadores únicos.

### Requisitos e Critérios de Aceite

- [ ] Adicionar fluxo de _onboard_ à todas as telas da Pilot.
- [ ] Possibilitar que o usuário desabilite estes tutoriais ou mostrar apenas uma vez.
- [ ] Manter o estilo da pilot nas mensagens do fluxo de _onboard_.

**Comment by lucas-hidalgo** [comment]
Pessoal estamos pensando em um fluxo nativo de onboarding na Pilot, vamos consolidar tudo aqui https://github.com/pagarme/credenciamento/issues/403

**Comment by rsmelo** [comment]
já está sendo executada a fase de downstream (Desenvolvimento)
