### ISSUE TITLE
Trocar cor de fundo no ambiente Live da Recuperação de Senha na Pilot

### ISSUE THREAD

**Issue by miglsoares** [pagarme/pilot#1365]
### Contexto
Em ambiente live, o background indica ao usuário que ele está na área de testes - por ser o dark mode. O ideal seria que o background fosse o light mode para indicar que o usuário está, de fato, no ambiente que ele espera estar.

### Exemplo
<img width="1680" alt="Screen Shot 2019-09-03 at 17 16 41" src="https://user-images.githubusercontent.com/20358128/64205593-c2b6e000-ce6e-11e9-8a11-12c47ae7010f.png">

### Requisitos e Critérios de Aceite

- [ ] Mudar background para o padrão do ambiente de Live

**Comment by rsmelo** [comment]
resolvido @miglsoares #1362
