### ISSUE TITLE
Rollout Pilot - Q3&Q4 2019

### ISSUE THREAD

**Issue by daniantar** [pagarme/pilot#1368]
## Contexto
A pilot está há muito tempo em desenvolvimento e o seu rollout já passou por alguns roadmaps, mas ainda não foi realizado. Dessa maneira o objetivo agora é estruturar o rollout de maneira viável e dar o seu início o quanto antes.

## Descrição
Como ainda possuímos algumas hipóteses em cima do que foi criado na Pilot, o trabalho de research deve ser realizado do zero, para sermos assertivos na priorização dos próximos passos do produto.

Devido a isso também estamos levantando 20 clientes elegíveis a utilizar a pilot, e assim fazermos um acompanhamento mais assertivo e próximo, para validarmos o necessário do produto.

## To Do's
- [x] Levantar os 20 clientes de teste.
- [x] Rodar a pesquisa Quali que a Ale montou.
- [x] Preparar pesquisa Quanti com base na primeira Quali.
- [x] Repriorizar próximas entregas com base nas pesquisas.
- [x] Soltar na mão dos clientes teste e ver a parada explodir.
- [ ] Pegar os feedbacks e iterar o produto/estratégia.

Copio aqui o comentário que fiz na Issue da Suzana: https://github.com/pagarme/greenphoenix/issues/113

--> Esses ítens que a Suzana comentou anteriormente, já estão alinhados p/ serem feitos?

- [ ] Usar Capability como parâmetro de company participante de rollout, para irmos aos poucos na adoção, conseguimos usar isso de flag p/ ser interpretado no SF pra galera do RC?
- [ ] Indicar de alguma maneira que a área está sob construção
- [ ] Explicar ao cliente que ele vai mudar de ambiente

Levantamento Quali

Dado interessante que a Su trouxe --> 52% da base não utiliza as features que temos prontas da dash - acho essa info um ótimo ponto de partida p/ realizarmos uma validação quali, e entender o uso da dash por essa galera. @alexandralugli 

Recomendo fazermos um levantamento quali por feature atrelado à personas, assim entendemos quais partes são mais importantes para quem, isso pode ser game changing p/ o produto que temos hoje, bora alinhar isso com o plano geral de research @alexandralugli ? De repente envolver o Lucas & Chapter? Que tal?

**Comment by daniantar** [comment]
Fizemos uma dinâmica na última galinhada em que discutimos os casos de uso e personas do cliente que utilizar a Dash/Pilot, assim deixo aqui as informações que levantamos em conjunto:

**Comment by daniantar** [comment]
Lista de prioridades p/ os próximos passos na Pilot:

- [ ] 1. Apresentação das Taxas
- [ ] 2. Onboarding
- [ ] 3. Contrato
- [ ] 4. Comprovante de estorno
- [ ] 5. Ajustes e refinamentos
            - Rebrand
            - Rastreabilidade de páginas
            - Bugs
- [ ] 6. Link
- [ ] 7. Recorrência
- [ ] 8. Agenda de recebíveis ```Atlas Blocker```
- [ ] 9. RAV ```Atlas Blocker```
- [ ] 10. Modularização de Features ```Atlas Blocker```
- [ ] 11.  Clientes

**Comment by daniantar** [comment]
Reunião com Bia:
- Novos feedbacks

- [ ] 1. Motivos de recusa
- [ ] 2. Extrato
- [ ] 3. Downgrades de experiencia (user antigo gosta de certas features/peeks que temos na dash antiga, como replicar na Pilot?)
-- Listagem das transações - possibilidade de brincar mais com as colunas, o comportamento se réplica.
-- Filtro sobre taxas pagas e os recebíveis líquidos.
Obs. Importante:
Saber quais clientes pagaram, ser cliente-driven e não transaction-driven.
- [ ] 4. Planejamento anual p/ prever épicos realmente grandes e complicados: exemplo de múltiplos acessos com diferentes visualizações.

**Comment by Deivis** [comment]
@daniantar  se conseguires uma explicação melhor sobre o item
```
-- Filtro sobre taxas pagas e os recebíveis líquidos.
Obs. Importante:
Saber quais clientes pagaram, ser cliente-driven e não transaction-driven.
```

Pois não sei como fazer isso na dash velha não, e se o caso for a combinação de filtros, talvez devessemos mostrar que isso é possível com a seção `Mais filtros`.

**Comment by daniantar** [comment]
Epa @Deivis , é sobre se conseguimos apresentar pro usuário quais são os clientes que pagaram e não se a transaction está paga de maneira independente.
