### ISSUE TITLE
Criação de input de confirmação de senha na tela de Cadastro

### ISSUE THREAD

**Issue by miglsoares** [pagarme/pilot#1369]
### Contexto
Hoje não temos um `FormInput` para confirmação de senha nas nossas duas pages de Cadastro: `LoginSignUp` e `Invite`. O ideal é que existisse um input de confirmação de senha e de força de senha para ambas telas.

**Observação: Encontramos uma confirmação de senha dentro do Minhas Configurações que pode ser utilizado também nessas telas de Cadastro. Exemplo:**
<img width="1425" alt="Screen Shot 2019-09-06 at 13 52 08" src="https://user-images.githubusercontent.com/20358128/64446168-7a860080-d0ae-11e9-9470-e7203d3a7b77.png">

### Exemplo
`Dash atual tela`
![image](https://user-images.githubusercontent.com/20358128/64446205-97223880-d0ae-11e9-9538-e6b4cb251fc8.png)

`Dash atual força de senha`
![image](https://user-images.githubusercontent.com/20358128/64446278-cafd5e00-d0ae-11e9-8974-f01639dfd785.png)

### Requisitos e Critérios de Aceite
- [ ] Adicionar input de confirmação de senha na tela de Cadastro
- [ ] Adicionar input de confirmação de senha na tela de Cadastro após convite
- [ ] Adicionar funcionalidade de força de senha na tela de Cadastro
- [ ] Adicionar funcionalidade de força de senha na tela de Cadastro após convite

**Comment by rsmelo** [comment]
ja foi resolvido
