### ISSUE TITLE
Recrutamento de clientes

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1374]
Parte do plano de pesquisa #1372

### **Contexto**

Vamos realizar pesquisas focadas nos usuários de SaaS. Para isso, precisamos listar os clientes aptos para o teste de acordo com os seguintes requisitos:

**Base para entrevista presencial**

Quantidade de usuários: 8
[4 users dash atual, 4 users pilot: 2 A.1, 3 A.1, 3 B.1]
Canal: Entrevista presencial

**Requisitos de perfil: Clientes que configuram smb**

- Não utilizam recorrência;
- Não utilizam marketplace;
- Não utilizam venda digitada;
- Clientes que transacionaram nos últimos 3 meses.

A. Empresa média
A.1. Dono da empresa: Cuida do balance e coisas específicas da operação.
A.2. Funcionários: Cuidam da área financeira e administrativa das operações.

B. Empresa pequena
B.1. O dono da empresa cuida de toda a operação

**Base para a pesquisa qualitativa da home**

Quantidade de usuários: 100
Canal: E-mail
Requisitos de perfil: Clientes que configuram smb

- Utilizam a dashboard e não a API como solução;
- Não utilizam recorrência;
- Não utilizam marketplace;
- Não utilizam venda digitada;
- Clientes que transacionaram nos últimos 3 meses.
- 20 perfis [6-10 users]; 10 perfis [4-5 users]; 20 perfis [2-3 users]; 50 perfis [1 user].

**Requisitos da issue**

- [x] Lista de clientes para a pesquisa qualitativa da home
- [x] Lista de clientes para entrevista presencial
- [x] Pedir ajuda para os account managers para entender quais clientes estão mais abertos a uma visita.
- [x] Pensar em algum brinde ou mimo para o cliente que participar da entrevista

**Comment by alexandralugli** [comment]
Lista de clientes que usam a **Pilot** para entrevista presencial atualizada.

Falta só da dash atual.

**Comment by daniantar** [comment]
Update: alinhando com o time do comercial p/ selecionar quem serão os entrevistados da Dash atual.

**Comment by alexandralugli** [comment]
Update: O Dani pegou a lista de clientes e conferimos no Logentries se eles utilizam a dash, tudo certo. Agora vamos ligar e agendar as visitas.
