### ISSUE TITLE
Implementar capability de reprocessamento na página de reprocessamento

### ISSUE THREAD

**Issue by flyingluscas** [pagarme/pilot#1379]
### Contexto

Adicionar a capability `allow_reprocess_without_antifraud` na tela de reprocessamento.

### Descrição técnica

1. Mapear nova capability da company para dentro das propriedades recebidas pela página de [reprocessamento](https://github.com/pagarme/pilot/blob/master/packages/pilot/src/pages/Reprocess/index.js).

### Requisitos e Critérios de Aceite

- [ ] Adicionar ao propTypes a capability `allowReprocessWithoutAntifraud`.
- [ ] Precisar passar essa propriedade para o container.

**Comment by rsmelo** [comment]
verificamos que a issue https://github.com/pagarme/pilot/issues/1387 ja cobre esse escopo então estamos fechando esta
