### ISSUE TITLE
Motivos de recusa - lista e detalhe de transações

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1406]
Atualmente, os motivos de recusa de uma transação é o 3º assunto que as pessoas mais tem dúvidas e procuram o RC.

Precisamos repensar a forma de apresentar essa informação e trazer ações relacionadas que os usuários poderão fazer.

**Comment by alexandralugli** [comment]
Pedi para a Bia do RC me enviar as orientações que damos aos clientes dependendo de cada motivo de recusa:


CÓDIGOS DE RETORNOS DAS TRANSAÇÕESCódigo | Mensagem | Orientação
-- | -- | --
0 | Transação autorizada | ----------
1000 | Transação não autorizada | Oriente o portador a entrar em contato com o banco emissor do cartão
1001 | Cartão vencido | Oriente o portador a entrar em contato com o banco emissor do cartão
1002 | Transação não permitida | Oriente o portador a entrar em contato com o banco emissor do cartão
1003 | Rejeitado emissor | Oriente o portador a entrar em contato com o banco emissor do cartão
1004 | Cartão com restrição | Oriente o portador a entrar em contato com o banco emissor do cartão
1005 | Transação não autorizada | Oriente o portador a entrar em contato com o banco emissor do cartão
1006 | Tentativas de senha excedidas | Oriente o portador a entrar em contato com o banco emissor do cartão
1007 | Rejeitado emissor | Oriente o portador a entrar em contato com o banco emissor do cartão
1008 | Rejeitado emissor | Oriente o portador a entrar em contato com o banco emissor do cartão
1009 | Transação não autorizada | Oriente o portador a entrar em contato com o banco emissor do cartão
1010 | Valor inválido | É possível que o tipo de operação seja inválido. Ex.: cartão de débito onde se aceita apenas crédito
1011 | Cartão inválido | O número do cartão digitado está incorreta. Oriente o portador a tentar novamente, se atentando ao preenchimento do número do cartão
1013 | Transação não autorizada | Oriente o portador a entrar em contato com o banco emissor do cartão
1014 | Tipo de conta inválido | O tipo de conta selecionado não existe.
1015 | Função não suportada | É possível que o tipo de operação seja inválido. Ex.: cartão de débito onde se aceita apenas crédito
1016 | Saldo insuﬁciente | Oriente o portador a entrar em contato com o banco emissor do cartão para aumento do limite
1017 | Senha inválida | Oriente o portador a entrar em contato com o banco emissor do cartão
1019 | Transação não permitida | Oriente o portador a entrar em contato com o banco emissor do cartão
1020 | Transação não permitida | Oriente o portador a entrar em contato com o banco emissor do cartão
1021 | Rejeitado emissor | Oriente o portador a entrar em contato com o banco emissor do cartão.
1022 | Cartão com restrição | Oriente o portador a entrar em contato com o banco emissor do cartão
1023 | Rejeitado emissor | Oriente o portador a entrar em contato com o banco emissor do cartão.
1024 | Transação não permitida | Oriente o portador a entrar em contato com o banco emissor do cartão
1025 | Cartão bloqueado | Oriente o portador a entrar em contato com o banco emissor do cartão.

**Comment by alexandralugli** [comment]
Fiz um exercício de como ficaria essa info na listagem de transações:

![image](https://user-images.githubusercontent.com/8549244/66949798-85c53800-f02d-11e9-89f6-d97caab8718c.png)

**Comment by Deivis** [comment]
Bom dado este "de para" do RC acho que podemos fazer o mesmo na Pilot por hora, pois se formos ajustar isso na API vai nos tomar muito tempo.
Podemos gerar um modelo que de acordo com a chave(Código de recusa) recebido retorna o titulo e a descrição da recusa.

**Comment by Deivis** [comment]
> Fiz um exercício de como ficaria essa info na listagem de transações:
> 
> ![image](https://user-images.githubusercontent.com/8549244/66949798-85c53800-f02d-11e9-89f6-d97caab8718c.png)

Achei um pouco escondido isso no `?` mas acho q vai ser difícil acharmos uma solução melhor.
Em relação a *tooltip*  acho que o título poderia ser só **Recusado** ao invés de `Recusado - motivo:`

**Comment by alexandralugli** [comment]
**Lista de transações**

![image](https://user-images.githubusercontent.com/8549244/67245294-0622d900-f432-11e9-9144-bf9f37788f6f.png)

Zeplin: https://zpl.io/blkjYxG


**Detalhe da transação**

Exemplo de transação negada
![image](https://user-images.githubusercontent.com/8549244/67248138-d8419280-f439-11e9-833d-e8b211ce7485.png)


Zeplin https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5ab16eb8f7719b4c81ab604c

**Comment by daniantar** [comment]
@alexandralugli , na ultima tela que comentou que irá atualizar, o 2o exemplo é de uma transação paga, como ficaria em caso de recusa? O motivo da recusa (orientação), aparece nessa tela também? Tks

**Comment by alexandralugli** [comment]
Oi @daniantar ! O detalhe de uma transação recusada ficaria assim:

O motivo de recusa com a instrução ficaria logo abaixo da tag.

![image](https://user-images.githubusercontent.com/8549244/67584241-8e9bc500-f723-11e9-8057-949100598c85.png)

**Comment by daniantar** [comment]
Massa! Só um comentario, o box vermelho chama bastante atenção, acho legal também dar destaque na linha aonde tem o alert do motivo. A tela como está pode fazer com que o user pule a linha do alert e não preste atenção. Seria massa dar um destaque, de repente até colorido, nessa linha.

**Comment by alexandralugli** [comment]
Concordo @daniantar . Ajustei o alert para que chame a atenção do usuário logo abaixo da tag:

![image](https://user-images.githubusercontent.com/8549244/67603482-5f9b4880-f74f-11e9-91f9-950efa074630.png)

Fiz um teste com um alert vermelho, mas teríamos de criar um componente novo e é diferente do padrão de feedback que estamos usando, daí teríamos de ajustar todos os outros também:

![image](https://user-images.githubusercontent.com/8549244/67604413-e18c7100-f751-11e9-9f51-16e3a4d6fd74.png)


Eu iria com a primeira opção. Por ser um padrão e porque como a leitura está em F e abaixo da tag, dificilmente passará despercebida pelo usuário. Esse aqui:
![image](https://user-images.githubusercontent.com/8549244/67604513-22848580-f752-11e9-99ce-bb2b3c1f382b.png)

**Comment by GAnelli** [comment]
Issue técnica criada: #691

**Comment by daniantar** [comment]
@beatrizabud

**Comment by dcdiogo** [comment]
Olá, por acaso existe um endpoint para consultar esses status?
Pergunto pois a descrição não é retorna no objeto transanction, apenas o código.
Procurei nos docs, mas não achei.
Obrigado

**Comment by said-alex** [comment]
Vocês teriam uma lista completa dos códigos de erros com o motivo?

**Comment by jonaselan** [comment]
> Vocês teriam uma lista completa dos códigos de erros com o motivo?

@said-alex seria isso? https://github.com/pagarme/pilot/issues/1406#issuecomment-542754693
