### ISSUE TITLE
Volume transacionado da Pilot difere do Dash antigo

### ISSUE THREAD

**Issue by GAnelli** [pagarme/pilot#1417]
![image](https://user-images.githubusercontent.com/31356460/66772973-4f07ea00-ee94-11e9-86a6-e399210cf3cd.png)

Possivelmente o volume transacionado da Pilot esteja considerando pagamentos pendentes e não apenas transações confirmadas.

**Comment by rsmelo** [comment]
duplicado da issue  ##1419
