### ISSUE TITLE
Volume transacionado na tela de resumo pode confundir o usuário

### ISSUE THREAD

**Issue by lucas-hidalgo** [pagarme/pilot#1419]
### Contexto
Realizamos algumas transações de teste para validar o reprocessamento e notamos que ao visualizar o "Volume transacionado" na tela de resumo, o mesmo retorna o valor referente a todas transações realizadas, mesmo que não aprovadas tanto pelo AF quanto pelo banco. 

No meu ponto de vista isso pode acabar confundindo o usuário uma vez que o volume transacionado sempre vai ser muito maior do que o valor disponível para saque, o que também pode enfatizar a diferença de valor por conta de recusas do antifraude.

Na imagem abaixo, o print da minha dash com R$25 de volume transacionado sem ter nenhuma transação realmente paga.
![Captura de Tela 2019-10-14 às 15 20 57](https://user-images.githubusercontent.com/54157203/66774566-40bbcd00-ee98-11e9-830c-562897f22cdd.png)

O @mccraveiro sugeriu mostrarmos apenas transações pagas, faz sentido?

**Comment by rsmelo** [comment]
duplicada dessa issue, mas como esta esta com mais detalhes acho que faz sentido usar essa aqui pra discussão

**Comment by miglsoares** [comment]
### Algumas observações à partir da análise que fiz (Incompleto)

Na minha concepção, analisei as requests tanto da Pilot quanto da Dash Atual e o conteúdo que vem de `/search` para o cálculo de volume transacional é o mesmo, puxado via Elastic Search.

`dash atual`
```
    "aggregations": {
      "account_overview": {
        "doc_count": 2257,
        "past_week_volume": {
          "doc_count": 6,
          "volume": {
            "value": 6000
          }
        },
        "current_day_volume": {
          "doc_count": 1,
          "volume": {
            "value": 1000
          }
        },
        "volume_on_period": {
          "doc_count": 27,
          "volume": {
            "value": 22830
          }
        },
        "avg_ticket_on_period": {
          "doc_count": 27,
          "avg_ticket": {
            "value": 845.5555555555555
          }
        },
        "current_month_volume": {
          "doc_count": 37,
          "volume": {
            "value": 48830
          }
        },
        "past_month_volume": {
          "doc_count": 70,
          "volume": {
            "value": 485278
          }
        },
        "current_week_volume": {
          "doc_count": 27,
          "volume": {
            "value": 22830
          }
        },
        "past_day_volume": {
          "doc_count": 0,
          "volume": {
            "value": 0
          }
        }
      }
    }
```

` pilot`
```
"metrics": {
  "volume": {
     "value": 50000
  },
}
```

Conversei com o @vagnervst e chegamos a conclusão que seria interessante restringir as transações apenas com o status `paid` no ElasticSearch mesmo. Por isso, precisa criar uma nova `agreggation` para filtrar as transações com status `paid` - não interferindo no filtro que já existe para não ter side-effects em outros cálculos que usem esse valor.

**Comment by vagnervst** [comment]
Investigando com a @miglsoares chegamos na seguinte query, que faz uma aggregation de `status` sobre a já existente aggregation de `date_range`. E então sobre o resultado, somamos o `amount` das transações:

```js
const query = ({ end, start }) => ({
  filter: {
    range: {
      date_created: {
        lte: end,
        gte: start,
      },
    },
  },
  aggs: {
    weekdayVolume: {
      filter: {
        range: {
          date_created: {
            lte: end,
            gte: start,
          },
        },
      },
      aggs: {
        weekdays: {
          date_histogram: {
            field: 'date_created',
            interval: 'day',
          },
          aggs: {
            volume: {
              sum: {
                field: 'amount',
              },
            },
          },
        },
      },
    },
    metrics: {
      date_range: {
        field: 'date_created',
        ranges: [
          {
            from: start,
            to: end,
          },
        ],
      },
      aggs: {
        paidTransactions: {
          terms: {
            field: 'status',
            include: ['paid', 'pending_refund', 'refunded', 'chargedback']
          },
          aggs: {
            volume: {
              sum: {
                field: 'amount',
              },
            },
          },
        },
        payment_method: {
          terms: {
            field: 'payment_method',
          },
        },
        card_brand: {
          terms: {
            field: 'card_brand',
          },
        },
        status: {
          terms: {
            field: 'status',
          },
        },
        refuse_reason: {
          terms: {
            field: 'refuse_reason',
          },
        },
        installments: {
          terms: {
            field: 'installments',
          },
        },
      },
    },
  },
})
```

**Comment by vagnervst** [comment]
Comparando a nossa implementação com a Dashboard atual, notamos que a atual considera somente as transações `paid`, enquanto na Pilot estamos considerando todas as transações que foram `paid` em algum momento, isto é, incluindo no filtro os status que vem depois de `paid` como `refunded` e `chargedback`. 

Estamos discutindo qual das implementações é mais correta.
