### ISSUE TITLE
Adicionar dados de cliente(customer) a requisição de reprocessamento

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1427]
### Contexto

Hoje quando reprocessamos uma transação em versões mais antigas da API (ex: 2013-03-01) nós passamos apenas o `id` do `customer` e isso se torna insuficiente para as validações da API e isso acaba gerando o erro abaixo:

### Exemplo

![image](https://user-images.githubusercontent.com/18116811/66949486-0172b500-f02d-11e9-9354-1fbc4628dc9b.png)

### Descrição técnica

A correção pode ser feita no `cockpit` pois quando reprocessamos uma transação enviamos a ele todos os dados da transação incluindo o `customer` e os dados necessários que devem ser formatados e adicionados a requisição de reprocessamento.

### Requisitos e Critérios de Aceite

- [ ] Criar reprocessamentos com antifraude compativeis com versões mais antigas da API.

**Comment by rsmelo** [comment]
@flyingluscas  comentou esse trecho como é feito na dashboard atual 
https://github.com/pagarme/pagarme-dashboard/blob/c56596abe64645670dce6c8a88be029f8d183faa/app/screens/transactions/details.js#L718-L734
