### ISSUE TITLE
Problema ao carregar tela de extrato na pilot

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1428]
### Contexto
Após o deploy da versão v0.20.0 começou a ocorrer o erro
`fantasy-land/map of undefined` para alguns clientes ao carregar a tela de extrato,
precisamos entender o problema

![image](https://user-images.githubusercontent.com/479495/66949931-c3c25c00-f02d-11e9-84f3-cd5e0b306a5c.png)

**Comment by vagnervst** [comment]
Investigando o problema, encontrei uma requisição em que o cliente recebeu o código `304`  e `null` como resposta. Na API encontrei somente um local que responde com este código, porém não consegui replicar o problema ao fazer as requisições manualmente via Postman.

**Comment by vagnervst** [comment]
Foi reportado hoje o mesmo problema. Investigando novamente descobri que o problema ocorre quando há uma transferência para contas Bradesco. Estou atuando na resolução do problema.

**Comment by rsmelo** [comment]
criei uma issue nova pra consolidar o novo esforço #1491
