### ISSUE TITLE
Filtro de transações por e-mail

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1436]
### Contexto
Atualmente não o filtro de transações por e-mail não está funcionado corretamente.
Precisamos investigar o que está acontecendo

### Exemplo

![image](https://user-images.githubusercontent.com/479495/67032397-e619af80-f0e9-11e9-9a72-f405a7b3cb43.png)

### Descrição técnica
- permitir o filtro pelo campo e-mail na tela de listagem de transações

**Comment by vagnervst** [comment]
O que provavelmente está ocorrendo é que estamos usando o `term` do ElasticSearch para filtrar o campo de e-mail, precisamos testar o `match_text` para filtrar pelo texto inteiro.

**Comment by vagnervst** [comment]
Fazendo alguns testes com o `pagarmejs` em um projeto sandbox, ajustei a nossa query para que funcione com o `match_phrase`.

## Query de email

**Antes**
```js
{
  term: {
    'customer.email': '<email>',
  }
}
```

**Depois**
```js
{
  query: {
    match_phrase: {
      'customer.email': '<term>',
    },
  }
},
```

Basta aplicar no cockpit esta alteração específica para e-mail e a nossa busca passará a funcionar normalmente. O arquivo onde construímos a query é:
https://github.com/pagarme/pilot/blob/master/packages/cockpit/src/transactions/search/query.js
