### ISSUE TITLE
Lista de transações - alterar exibição da coluna status para o texto completo

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1440]
### Contexto
Atualmente não existe uma tootlip na coluna status para informar o usuário qual o status da transação. Observando o fullstory vimos que isso causa confusão em alguns usuários. A ideia alterar exibição da coluna status para o texto completo
![image](https://user-images.githubusercontent.com/479495/67043039-83cba980-f0ff-11e9-8ae9-c765cb24a5e0.png)

Ficando da seguinte forma:

![image](https://user-images.githubusercontent.com/18339615/67118958-70cadf00-f1bc-11e9-95c5-dd4a9806da63.png)

### Descrição técnica
- adicionar a tooltip na coluna de status informando o valor textual do status

**Comment by alexandralugli** [comment]
Fizemos recentemente um update nas cores das legendas. Segue abaixo a lista de possíveis status.
### **Possíveis status para cartão de crédito:**

- **Processando**: transação sendo processada. 

- **Autorizado**: transação autorizada. Cliente possui saldo na conta e esse valor foi reservado para futura captura. Essa captura deve acontecer no período de 5 horas para transações feitas pelo Checkout Pagar.me. Caso isso não seja feito, a autorização é cancelada automaticamente;

- **Pago**: transação paga (autorizada e capturada). 

- **Estornado**: transação estornada no valor total. As transações estornadas parcialmente continuam com o status “pago”;

- **Chargeback**: transação sofreu uma contestação;

- **Chargeback reapresentado**: transação sofreu uma contestação e foi reapresentado pelo cliente.

- **Recusado**: transação não autorizada.

- **Revisão pendente**: A transação fica pendente de revisão manual por um período de até 48h.

### **Possíveis status para boleto:**

- **Recusado**: geralmente, quando uma transação se encontra com esse status ocorreu algum erro de configuração e o boleto não foi emitido;

- **Aguardando registro**

- **Aguardando pagamento**: o pagamento do valor total do boleto emitido está pendente;

- **Pago**: foi pago o valor integral do boleto. Boleto conciliado e pago para o cliente;

- **Estorno pendente**: status intermediário entre “Pago” e “Estornado”. Quando o estorno ainda não foi processado pelo banco;

- **Estornado**: o valor total do boleto foi estornado para a conta do consumidor final.

**Comment by alexandralugli** [comment]
Update no zeplin: https://zpl.io/am7Z44r

**Comment by rsmelo** [comment]
@alexandralugli @miglsoares o componente Legend do former-kit hoje força caixa alta na fonte da label e no zeplin está somente a primeira letra em maiusculo. 
Além disso agora temos a necessidade de alterar a cor do texto, antes era sempre branca, mas no caso de autorizado que tem o fundo amarelo a fonte branca fica ilegivel.
Acredito que faz sentido alterar o componente Legend para que possibilite passar alem da cor de fundo tambem a cor do texto.

**Comment by alexandralugli** [comment]
Corrigindo: status `aguardando pagamento` ali na imagem ta com hexa errado. O correto é #f29f03
