### ISSUE TITLE
detalhes da transação - Botão reprocessar está aparecendo em transações de subscriptions

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1446]
### Contexto
Em alguns casos o botão reprocessar está aparecendo quando não deveria, como por exemplo em transações de subscriptions. Precisamos investigar melhor essa situação

**Comment by vagnervst** [comment]
Fiz alguns testes em um ambiente local da API e não consegui replicar o cenário onde o botão aparece para transações de assinatura. Até porque já previmos isto em nossa capability :thinking: 

https://github.com/pagarme/pilot/blob/f730f6ed6527843cb14951f458d9b5383687afcd/packages/cockpit/src/transactions/details/isReprocessable.js#L19
