### ISSUE TITLE
Adicionar mensagem de erro para Rate Limit no extrato

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#1467]
### Contexto
Hoje, a mensagem de Rate Limite excedido está em inglês e não dá uma saída para o usuário.
A ideia é ter uma mensagem mais clara e seguindo os padrões atuais

### Exemplo

![image](https://user-images.githubusercontent.com/8549244/67250004-1b066900-f440-11e9-965e-5d3d747c4df4.png)

Zeplin: https://zpl.io/br08BZD

### Descrição técnica

Mudar mensagem para:

`O limite de requisições foi excedido. Por favor, tente novamente em alguns minutos.`

### Requisitos e Critérios de Aceite

- [ ] Mensagem exibida é a contida nesta issue

**Comment by marisamodolo** [comment]
Fiz os testes com a API e notei que já temos uma mensagem de rate limit no extrato, que é tratada pelo error boundary: 
![image](https://user-images.githubusercontent.com/46823713/68235256-adcb0a00-ffe1-11e9-87c2-ce411800cada.png)
https://github.com/pagarme/pilot/blob/f730f6ed6527843cb14951f458d9b5383687afcd/packages/pilot/src/errors/connection.js#L60

**Comment by rsmelo** [comment]
pelo que foi reproduzido parece que ja temos uma tratativa customizada pra esse caso
