### ISSUE TITLE
Remover indexação do ambiente de sandbox

### ISSUE THREAD

**Issue by mccraveiro** [pagarme/pilot#1471]
### Contexto

O Google indexou ambos os ambientes (sandbox e live) em sua pesquisa. Isso gera alguns problemas com os clientes que chegam na dashboard através do google pois muitos acabam caindo no ambiente de sandbox.

Dado isso, decidimos remover a indexação do ambiente de sandbox. 

### Descrição técnica

Temos 2 caminhos para chegar nessa solução:

1. Criação de um robots.txt
2. Inserção de uma meta tag no follow `<meta name="robots" content="noindex,nofollow">`

O segundo caminho parece mais simples de ser implementado na estrutura atual do projeto.

### Requisitos e Critérios de Aceite

- [ ] Remoção da indexação da URL http://beta.dashboard.sandbox.pagar.me
- [ ] Continuidade da indexação da URL http://beta.dashboard.pagar.me

**Comment by rsmelo** [comment]
oi @mccraveiro

**Comment by mccraveiro** [comment]
Oi @rsmelo 👋
