### ISSUE TITLE
Checar o custo de processamento na descrição do recebedor

### ISSUE THREAD

**Issue by marisamodolo** [pagarme/pilot#1473]
### Contexto
Hoje a página de `Detalhes da Transação` é inconsistente na demonstração dos valores entre os cards e a descrição da transação para os recebedores.
Devemos procurar uma melhor forma de mostrar esses valores para o usuário, dado que para os recebedores não mostramos que é cobrado o custo de processamento de R$ 1,20, assim o valor de saída e o valor líquido diferem dos cards.

Também mostramos uma cobrança de R$ 3,80 de MDR + R$ 3,80 de custo de processamento em casos de boleto, mas não é cobrado dessa forma. Cobramos apenas 3,80 e não 7,60. Pode ser visto 
 no exemplo abaixo.

#### Cartão
![50%](https://user-images.githubusercontent.com/46823713/67885748-e3c24700-fb26-11e9-9aa3-2758852f83e7.png)

#### Boleto
![image](https://user-images.githubusercontent.com/46823713/67893916-4bcc5980-fb36-11e9-859e-f1f6e663bc52.png)

**Comment by alexandralugli** [comment]
Fiz alguns exercícios de como demonstrar esse custo, tanto na tela de detalhes da transação quanto no extrato.

O custo de processamento não deve ser somado ao total de saídas da transação. Essa taxa é descontada uma vez por mês junto aos custos de processamento das demais transações do período.

Porém, pensei em deixar esse valor como demonstrativo para que o cliente saiba o custo gerado pela transação em questão e informar as regras de desconto e pagamento dessa taxa.

Como é uma informação secundária, que uma vez que o cliente entende que será descontado posteriormente, não existe necessidade de sobrecarregar a tela com esse texto corrido ou muito explícito o tempo todo. Sendo assim, coloquei num tooltip na tela de detalhes da transação e vou dividir melhor os custos na tela de extrato.

Telas no zeplin: https://zpl.io/V0Z7Ggx / https://zpl.io/2p79ggy

![image](https://user-images.githubusercontent.com/8549244/68125706-e7701800-fef0-11e9-9d51-d8496977e86f.png)

![image](https://user-images.githubusercontent.com/8549244/68126429-906b4280-fef2-11e9-9cf0-be9ca01ea316.png)

**Comment by alexandralugli** [comment]
@marisamodolo Posso fechar essa issue?

**Comment by alexandrejuk** [comment]
Eu achei que ficou bom parabéns @alexandralugli  :rocket:
