### ISSUE TITLE
Exibir motivo de recusa no detalhes de transação

### ISSUE THREAD

**Issue by marisamodolo** [pagarme/pilot#1494]
### Contexto
Atualmente, os motivos de recusa de uma transação é o 3º assunto que as pessoas mais tem dúvidas e procuram o RC.
Precisamos repensar a forma de apresentar essa informação e trazer ações relacionadas que os usuários poderão fazer.

### Descrição técnica
- Garantir que o card do histórico da transação está utilizando a cor da model de status.
https://github.com/pagarme/pilot/blob/fb891436e97ed828a28eb042d47ffb76694f0b34/packages/pilot/src/models/statusLegends.js#L2-L5
- Adiciona informações na timeline de eventos:
https://github.com/pagarme/pilot/blob/c0a5ea073ada0f31eb5bfec974baa46e37a98b64/packages/pilot/src/containers/TransactionDetails/index.js#L525-L532
![image](https://user-images.githubusercontent.com/46823713/68861885-2eb59000-06cb-11ea-990e-766f2bde2cfe.png)

- Mover o alert com mensagem de reprocessamento para cima do header da transação.
Atual:
![image](https://user-images.githubusercontent.com/46823713/68795367-94543e80-062f-11ea-8f17-0c67424ab7aa.png)
Trocar para:
![image](https://user-images.githubusercontent.com/46823713/68795394-9f0ed380-062f-11ea-8081-8bf23d3df813.png)
- Adiciona alert secundário com o motivo de recusa.
![image](https://user-images.githubusercontent.com/46823713/68795482-d67d8000-062f-11ea-8870-bbff50673828.png)

https://zpl.io/VDoBJEO

### Requisitos e Critérios de Aceite
- [ ] Visualizar o alert com o motivo de recusa e a ação a ser tomada em detalhes da transação.
- [ ] Atualizar a timeline de eventos com as informações de recusa.

**Comment by rsmelo** [comment]
depende da issue https://github.com/pagarme/pilot/issues/1493

**Comment by rsmelo** [comment]
verificar o escopo dessa (https://github.com/pagarme/pilot/issues/1475)  isssue talvez seja possivel resolver as duas no mesmo pr

**Comment by felipebrunetti94** [comment]
Oi, estou tendo problemas com o setup de vcs, após `$ cd packages/pilot
$ yarn start`, vcs ainda usam yarn start ?

**Comment by marisamodolo** [comment]
> Oi, estou tendo problemas com o setup de vcs, após `$ cd packages/pilot $ yarn start`, vcs ainda usam yarn start ?

Oi @felipebrunetti94, usamos sim. Você rodou `yarn` na pasta raiz antes de rodar `yarn start` em pilot/packages/pilot?
