### ISSUE TITLE
Pilot - Implementação do Link de Pagamentos

### ISSUE THREAD

**Issue by lucas-hidalgo** [pagarme/pilot#1501]
### Contexto
Atualmente 1/3 dos clientes ativos de autocred utilizam o link de pagamentos na dashboard, acreditamos que fornecer essa feature na pilot pode ser positivo para esses clientes assim como pode reduzir o tempo de ativação, uma vez que muitos dos clientes que entram via autocred não estão com o site pronto.

Outro fator que corrobora para o desenvolvimento da feature é a relevância que a Pilot vem ganhando nos últimos meses, sendo que boa parte dos pedidos no RC relacionados à pilot dizem respeito ao Link de Pagamentos.

### Design
O layout já está desenvolvido e validado com hard users da feature na dashboard antiga.

As telas podem ser encontradas no link abaixo:
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5dc08e0ffe2dae2ba6b65818

O estudo de usabilidade acerca das telas está disponível em:
https://docs.google.com/spreadsheets/d/1ZkK-Mehh2QmPWUndwjMjQCkOOBXDyEyZCblGPXvC60I/edit?usp=sharing

### Fluxos
![68159007-a3503800-ff2f-11e9-943f-791e12802384](https://user-images.githubusercontent.com/54157203/70069331-5d3ed080-15d0-11ea-87ec-9a049c11cfd9.png)
![69449195-1aac0700-0d39-11ea-8447-5ce0177f05ee](https://user-images.githubusercontent.com/54157203/70069335-5e6ffd80-15d0-11ea-8712-77b88b1f5cf4.png)

**Lógica dos status**
![69448980-88a3fe80-0d38-11ea-8b0e-e30224f307df](https://user-images.githubusercontent.com/54157203/70069337-5fa12a80-15d0-11ea-9aec-2504b0151494.png)

### O que precisa ser feito?
- [x] Realizar planning para mapear como será desenvolvida a feature
- [x] Destrinchar os to-dos em issues no board

---

Se precisarem de mais algo é só me avisar, se possível, me envolvam na planning. ;)

**Comment by rsmelo** [comment]
já foi feita analise e criada issue de desenvolvimento
