### ISSUE TITLE
O fantasy-land Voltouuuuu

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#1508]
### Contexto

O de acordo com contato do comercial, o famigerado `fantasy-land/map of undefined` descrito nesta issue https://github.com/pagarme/pilot/issues/1428 voltou. 
### Exemplo

Imagem enviada por nosso cliente
![](https://scontent-gru1-1.xx.fbcdn.net/v/t1.15752-9/78880324_686577081749357_1742215881183723520_n.jpg?_nc_cat=101&_nc_ohc=E9OeJLkUFAQAQlQduw3sAbG_fsYhxaMregPTqYFtbyV5txWed6NnanQTw&_nc_ht=scontent-gru1-1.xx&oh=3943e6632d7a92cb20d34133a39ef99b&oe=5E6FE6F1)

Fullstory com o erro https://app.fullstory.com/ui/BKP05/session/6665986705096704:4580041206169600!5478527969165312/devtools/console

### Requisitos e Critérios de Aceite

- [ ] Fazer com que o extrato apareça corretamente.

**Comment by vagnervst** [comment]
Investigando descobri que o problema ocorre quando há uma BalanceOperation de cobranças do gateway. Ela possui a seguinte estrutura:

```json
{
  "type": "fee_collection",
  "movement_object": {
    "type": "billing",
    "description": "Serviços de gateway (01/11/2019 a 30/11/2019)",
  }
}
```

Precisamos incluir no cockpit o suporte à esse tipo de operation
