### ISSUE TITLE
Comparativo de features: dash atual x pilot - rollout

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1546]
**Contexto**

Precisamos entender quais features temos na dash atual que ainda não estão na Pilot e o seu grau de importância para o próximo rollout.

**Comment by alexandralugli** [comment]
Update: Eu e o Anelli criamos uma planilha com as seções e funcionalidades existentes na dash atual, definindo o que é essencial para o rollout segundo as pesquisas e o que entra como melhoria futura no produto:

https://docs.google.com/spreadsheets/d/1ka-ZieWPEQVCJA2iehmY5_8ICcMeYQLerO89fWrMQdU/edit?usp=sharing

**Comment by alexandralugli** [comment]
[Dash_atual_vs_Pilot.pdf](https://github.com/pagarme/pilot/files/4041008/Dash_atual_vs_Pilot.pdf)

**Comment by GAnelli** [comment]
Foi validado com o time as features que são necessárias para o Rollout V1. O único ponto que não havia sido mapeado era a questão de potencialmente recebermos o metadata do cliente e quebrarmos em colunas. Necessário criar uma issue referente a isto.
