### ISSUE TITLE
Telas de Detalhe da Transação 

### ISSUE THREAD

**Issue by IedaOtero** [pagarme/pilot#158]
Wireframes: Mapear os possíveis status que uma transação possa ter e especificar as regras.

**Comment by Fausto-Junior** [comment]
@beatriztoccis

**Comment by beatriztoccis** [comment]
@Fausto-Junior , a maior descrição tem 103 caracteres, que é a do Score do antifraude, se esse número for muito, podemos deixar apenas "Nota atribuída pelo antifraude à transação.", porém eu sugiro - se for possível - colocarmos a informação toda para o cliente não se esquecer, principalmente os novos. Qualquer coisa, é só avisar :)

**Descrições tool tips:**

Soft descriptor: Descrição que aparece na fatura depois do nome da sua empresa. 

Score do antifraude: Nota atribuída pelo antifraude à transação. Transações com pontuação maior ou igual 95 são recusadas.  

ID da assinatura: Número identificador da assinatura. 

Resposta da operadora: Resposta de aprovação ou recusa da transação por parte da operadora do cartão utilizado. 

NSU: Código que identifica a transação no adquirente.

**Comment by Fausto-Junior** [comment]
@beatriztoccis , você poderia fazer a descrição de mais um tool tip por favor? 

Seria para a informação "método de captura" 

Surgiu a necessidade de incluirmos essa informação também. 

Qualquer coisa me fala, valeu! 

:)

**Comment by Fausto-Junior** [comment]
Time, 

atualizei as páginas de detalhe da transação e documentei. 

Ficou pendente mapearmos casos críticos de split e da timeline de eventos. O @derekstavis está me ajudando nesse mapeamento para então passarmos para o protótipo. 

https://github.com/pagarme/produtos/tree/master/Arquitetura/Extrato%20e%20Transa%C3%A7%C3%B5es/Wireframes/Desktop

É isso!

**Comment by mccraveiro** [comment]
@beatriztoccis 
> Transações com pontuação maior ou igual 95 são recusadas.

Lembrando que essa regra só vale para a Clearsale.
Hoje já temos Simility e Konduto e em breve vamos ter outros provedores. Assim, acho que precisamos formular isso melhor.

**Comment by beatriztoccis** [comment]
Boa @mccraveiro , não tinha mesmo me ligado disso! :) 

@Fausto-Junior vou editar o comentário e arrumar a frase, qualquer coisa me avisa!

**Comment by derekstavis** [comment]
@Fausto-Junior  esta trabalhando em estressar a timeline com a ajuda da Isa :)
