### ISSUE TITLE
Extrato - versão mobile

### ISSUE THREAD

**Issue by IedaOtero** [pagarme/pilot#159]
A versão mobile contemplará a princípio as informações da tela principal do Extrato, assim como os fluxos de sacar e antecipar.

**Comment by ericksahara** [comment]
Segue o wireframe da versão mobile:

http://d0o47m.axshare.com/

pw: eppagarme

**Comment by flaviolee** [comment]
Removi a senha de acesso porque o repositório é público.

**Comment by mccraveiro** [comment]
@flaviolee qual o motivo para não liberar?
Acredito que se vamos fazer open source, devemos ser 100% open source. Não vejo motivo para ser open source se as pessoas de fora não puderam ajudar e estiverem completamente envolvidas no processo.

**Comment by flaviolee** [comment]
A questão aqui é controlar a divulgação das novidades da nova dashboard.
Como é um wireframe ainda, talvez muita coisa mude até a versão final.
O controle do acesso ao wire serve para que ninguém divulgue nada para os clientes que não venha a aparecer no lançamento e cause aborrecimento ou decepção por conta da expectativa, sacou? =)

**Comment by Evilhideki** [comment]
@mccraveiro , a principal razão pela qual vamos manter assim, é para tentar controlar a divulgação e expectativa sobre funcionalidades que estão planejadas, mas que não estão necessariamente no roadmap de desenvolvimento =)

**Comment by felquis** [comment]
@Evilhideki é uma boa prática adicionar uma conclusão do assunto ao fechar uma issue, para que as pessoas não fiquem no vácuo :)

![](https://media.giphy.com/media/s2qXK8wAvkHTO/giphy.gif)

**Comment by Evilhideki** [comment]
@felquis Mals dude, adicionei a conclusão ali em cima. Farei da forma apropriada das próximas vezes =)
