### ISSUE TITLE
Form Fields

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#164]
Implementar os seguintes campos de formulário:

- [ ] Input

```jsx
<Input
  name="email"
  type={"text" | "number" | "email" | "password"}
  label="Digite seu email"
  type="email"
  placeholder="nome@email.com"
  value={this.state.email}
  boxed={this.props.boxed ? true : false}
  onChange={e => this.setState({ email: e.target.value })}
  hint="Texto secundario"
  error={this.props.error}
  success={this.props.success}
/>
```

- [x] Dropdown

```jsx
<Dropdown
  options={options}
  name="pessoas"
  label="Pessoas da Pagarme"
  onChange={value => this.setState({ selected: value })}
  value={this.state.selected}
  disabled={this.props.disabled}
  title={this.props.title}
  error={this.props.error}
  success={this.props.success}
/>
```

- [x] Radio Group

```jsx
<RadioGroup
  options={options}
  name="pessoas"
  onChange={value => this.setState({ selected: value })}
  value={this.state.selected}
  disabled={this.props.disabled || undefined}
  error={this.props.error || undefined}
  success={this.props.success || undefined}
/>
```

Sendo `options` um array de objetos:

```js
[
  { name: 'Nome da opção', value: 'Valor da opção' },
  { name: 'Nome da opção', value: 'Valor da opção' },
  { name: 'Nome da opção', value: 'Valor da opção' },
]
```

- [ ] Checkbox

```jsx
<Checkbox
  name="pessoas"
  onChange={value => this.setState({ selected: value })}
  value={this.state.selected}
  disabled={this.props.disabled || undefined}
  title={this.props.title || undefined}
  error={this.props.error || undefined}
  success={this.props.success || undefined}
/>
```

Para usar um grupo de checkboxes juntos:

```jsx
<CheckboxGroup
  name="pessoas"
  options={options}
  onChange={values => this.setState({ selected: values })}
  values={this.state.selected}
  disabled={this.props.disabled || undefined}
  title={this.props.title || undefined}
  error={this.props.error || undefined}
  success={this.props.success || undefined}
/>
```

sendo `options` um array de objetos:

```
[
  { name: 'Nome da opção', value: 'Valor da opção' },
  { name: 'Nome da opção', value: 'Valor da opção' },
  { name: 'Nome da opção', value: 'Valor da opção' },
]
```

- [ ] Textarea

```jsx
<Input
    multiline
/>
```

O PR #154 adiciona estes artefatos em suas variações e estados.

Apenas um detalhe: A versão com ícone deve estar presente em todos os fields. 

Edited by Leo:
### Input
- [ ] ADAPTAR AO NOVO CSS :) E PROPRIEDADE MULTILINE

#### Text field boxes
- [x] Mudar boxes para boxed
- [x] Mudar secondaryText para hint
- [x] disabled
- [x] idle & empty
- [x] press
- [x] idle & filled 
- [x] error
- [x] success

#### Text field
- [x] disabled
- [x] idle & empty
- [x] press
- [x] idle & filled 
- [x] error
- [x] success

#### Password 
- [x] disabled
- [x] idle & empty
- [x] press (nao esquecer do icone de olhar password)
- [x] idle & filled (nao esquecer do icone de olhar password) 
- [x] error (nao esquecer do icone de olhar password)
- [x] success (nao esquecer do icone de olhar password)
- [x] Ao clicar no icone de olhar password, trocar o type e o icone

### Dropdown
- [x] Funcionamento basico (React)
- [x] Disabled
- [x] Idle & Empty
- [x] Press
- [x] Idle & Filled
- [x] Error
- [x] Success

### Radio Group
- [x] Feito todos os estados

### Checkbox
- [ ] Falta o background color quando clica

### Textarea (duas variacoes)
- [ ] É Input com prop multiline

### FormFields com icons
- [ ] Colocar no Input

**Comment by LeoNero** [comment]
### Input:
#### Text field boxes
- [ ] disabled
- [ ] idle & empty
- [ ] press
- [ ] idle & filled 
- [ ] error
- [ ] success

#### Text field
- [ ] disabled
- [ ] idle & empty
- [ ] press
- [ ] idle & filled 
- [ ] error
- [ ] success

#### Password 
- [ ] disabled
- [ ] idle & empty
- [ ] press (nao esquecer do icone de olhar password)
- [ ] idle & filled (nao esquecer do icone de olhar password) 
- [ ] error (nao esquecer do icone de olhar password)
- [ ] success (nao esquecer do icone de olhar password)
- [ ] Ao clicar no icone de olhar password, trocar o type e o icone

**Comment by LeoNero** [comment]
### Checkbox
- [ ]

**Comment by LeoNero** [comment]
### Radio Button
- [ ]

**Comment by LeoNero** [comment]
### Dropdown
- [ ]

**Comment by LeoNero** [comment]
### Textarea
- [ ]

**Comment by LeoNero** [comment]
### FormFields com icons
- [ ]
