### ISSUE TITLE
Component: Footer

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#166]
### Contexto
Como um cliente Pagar.me usuário da Dashboard
Eu quero acessar os links sociais do Pagar.me, e as páginas de Documentação, Suporte, Política e Privacidade, e Contato
Para que eu possa encontrar informações relativas a empresa, e obter o suporte necessário

### Requisitos

- [ ] Deve possuir a lista de links
- [ ] Deve possuir a lista de links de ícones

### Exemplo

https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/59f38373625c3afbe77434d8

### Proposta de interface

```jsx
<Footer
  links={[{ title: 'About', onClick: () => undefined }]}
>
  <Button icon={<IconPci />} onClick={() => undefined} />
  <Button icon={<IconFacebook onClick={() => undefined} />} />
</Footer>
```

Tentar usar a `Grid` dentro deste componente para fazer o responsivo.

### Critérios de aceite

- [ ] Deve renderizar uma lista horizontal de links de texto
- [ ] Deve renderizar uma lista horizontal de links de ícone
- [ ] Deve quebrar corretamente no breakpoint de 768

**Comment by felquis** [comment]
O que é isso?

**Comment by LeoNero** [comment]
@derekstavis q tipo de interface vc pensa pra esse component? Composicao? Passar tudo como props?

**Comment by derekstavis** [comment]
atualizei a issue com mais detalhes de interface e hint de implementação!!
