### ISSUE TITLE
Component: Header

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#168]
## Contexto

O Header é responsável por exibir qual página o usuário se encontra e navegar para o nível superior (se existir), permitir que ele acesse as áreas de notificações, ajuda e minha conta, bem como exibir um feedback visual quando o usuário está em ambiente de teste.

### [Telas no Zeplin](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/59f73b6d307f93a2a473f59b)

<img width="909" alt="captura de tela 2018-01-17 as 15 08 04" src="https://user-images.githubusercontent.com/24230714/35056187-48ba94e0-fb98-11e7-9a0a-8c9d3e27af75.png">

## Critérios de aceite

- [ ] Deve exibir a página em que o usuário se encontra
- [ ] Deve exibir o nome do usuário e avatar
- [ ] Deve permitir que o usuário navegue para uma página num nível superior 
- [ ] Deve permitir que o usuário navegue para a área de notificações

## Interface de desenvolvimento

```jsx
<Header>
  <HeaderBackButton icon={} onClick={} />
  <HeaderTitle>Transactions</HeaderTitle>
  <HeaderContent>
    <HeaderLink onClick={}>
      <IconAlert />
    </HeaderLink>
    <HeaderLink onClick={} icon={IconAlert} />
    <HeaderLink onClick={}>
      <img src="" alt="" />
      <label>Nome da Pessoa</label>
      <IconArrowDown />
    </HeaderLink>
    <EnvironmentFlag name="test" />
  </HeaderContent>
</Header>
```

**Comment by felquis** [comment]
O que é isso?

**Comment by gpgabrielpaiva** [comment]
?

**Comment by felquis** [comment]
@vitorvmiguel consegue por uns prints aqui?

**Comment by vitorvmiguel** [comment]
@felquis @gpgabrielpaiva editei o conteúdo da Issue com o exemplo do que é o Header, ainda não está em WIP, será feito nas próximas sprints.
