### ISSUE TITLE
Componentes visuais

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#18]
Entrega final dos componentes visuais

**Comment by mccraveiro** [comment]
@Evilhideki Consegue colocar uma descrição na issue? Assim mais pessoas podem contribuir.

**Comment by Evilhideki** [comment]
@mccraveiro ta ali ué. Depois da publicação na data sugerida, ai  podem ajudar, mas a entrega é totalmente visual. Um PNG, saca? =)

**Comment by mccraveiro** [comment]
@Evilhideki entendi porém ainda acho que poderia melhorar: Porque temos essa necessidade? Como chegamos nesse racional? Qual é o entregável para concluirmos essa issue? O que este PNG deve conter?

Gosto muito do estilo de issue que o felquis está propagando. Colocar o contexto por tras das issues melhora nossa comunicação, principalmente em repositórios open source como este :)

**Comment by derekstavis** [comment]
Eu prefiro que essa issue seja fechada, sendo criada uma issue nova para cada um dos componentes visuais da biblioteca de componentes. Na issue #1 eu detalhei uma proposta de organização de diretórios e de componentes, quais nomes poderão ser usados na criação dessas issues.

@Evilhideki, vc quer criar essas issues ou segunda-feira (24) eu dou o caminho da criação dessas issues pra @alexandralugli? Precisamos definir uma descrição padrão pra essas issues criá-las dentro da milestone!! Com isso já vamos ter as issues pra que a @alexandralugli possa subir o progresso do trabalho dela e entrar no fluxo!! 🎉 

Nesse meio tempo eu me comprometo a criar o pull-request que adiciona a estrutura de diretórios para os assets de UI 😄

**Comment by Evilhideki** [comment]
@mccraveiro cara, respondendo suas perguntas:

**Porque temos essa necessidade?** 
Porque é um site, e todo site tem que ter????

**Como chegamos nesse racional?**
É um design pattern. O racional tá scrito ali em cima com exemplo. Não entendo como posso ser mais objetivo. Aceito sugestões.

 **Qual é o entregável para concluirmos essa issue?**
Um png? (como mencionei antes?

 **O que este PNG deve conter?**
Nem sei como responder essa pergunta.
