### ISSUE TITLE
Matriz de Funcionalidades / Conteúdo

### ISSUE THREAD

**Issue by IedaOtero** [pagarme/pilot#188]
Documento detalhado das funcionalidades/conteúdo da Home, abrangendo os dois perfis de clientes: PSP e somente Gateway.

**Comment by felquis** [comment]
Este conteúdo será Open Source ou para ter acesso ao conteúdo precisará estar dentro do grupo?

**Comment by vitorvmiguel** [comment]
Issue encerrada para tratamento na https://github.com/pagarme/produtos/issues/52
