### ISSUE TITLE
Wireframes de baixa fidelidade com especificação funcional (Desktop)

### ISSUE THREAD

**Issue by IedaOtero** [pagarme/pilot#189]
Mockup navegável da tela inicial da Home para os dois perfis de clientes: PSP e somente Gateway para Desktop.

**Comment by Fausto-Junior** [comment]
Time, 

acabei de subir a página Home no protótipo. 

https://github.com/pagarme/produtos/tree/master/Arquitetura

Documentei algumas pendência para mapearmos. 

Aguardo comentários para melhorarmos essa primeira ideia. 

Abraços.

**Comment by Fausto-Junior** [comment]
@alexandralugli @flaviolee @Evilhideki

**Comment by Evilhideki** [comment]
@Fausto-Junior , minhas observações:

é importante ter ao menos uma notificação emergêncial ai, de destaque. Imagina o cenário onde a versão da API do cliente vai ser descontinuada. Esse cara precisa ver que isso acaba e ele vai quebrar. Veja como softwares Saas notificam clientes para interrupção de serviço (tipo windows quando vc não paga). Acho que podemos planejar isso ai.

Outro ponto é a questão de status do sistema. Por mais que não iremos fazer isso agora, é importante quem olha o projeto já ter essa visibilidade. Logo, acho importante ter um indicador de status de serviços pagar.me, que mostre ao cliente se estamos em pleno funcionamento, se temos instabilidade, ou ainda se estamos em um momento de manutenção programada.

filtros no gráfico inicial, que mude a leitura do tipo de informação. Por exemplo, podemos ter só esse gráfico com evolução histórica financeira, ou podemos usar o mesmo gráfico para representar evolução de chargebacks, inadimplência, etc?
Como podemos oferecer analises melhores na dashboard?

comparação - o cliente precisa ter a comparação por periodo. Como está sendo o mês dele em comparação com o mês passado?

ticket médio e clientes, pode ter mais informações: cresceu ou diminuiu? quantos % isso?

No geral, achei ela simples, mas um pouco pobre de dados gerenciais sobre transações financeiras que um cliente pagar.me pode ter =) Dá uma estressada nesses indicadores ae =)

No entanto, essa estressada pode ser uma evolução disso. @alexandralugli , já coloca essa home no seu roadmap =)

**Comment by Fausto-Junior** [comment]
@Evilhideki @alexandralugli 

Melhorias foram implementadas na home, dei atenção para todos os pontos observados acima. 

Essa nova versão já foi apresentada para toda a equipe do Pilot. 

Aguardo novos comentários. 

Acabei de subir no repositório de produtos :)

**Comment by vitorvmiguel** [comment]
Issue encerrada pelo PR https://github.com/pagarme/produtos/pull/31
