### ISSUE TITLE
Revisão ortográfica de componentes visuais (UI Library)

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#19]
Todos os elementos devem ser revisados. Ortografia, tom de voz e call to actions.

**Comment by alexandralugli** [comment]
Qual é a diferença entre essa issue e a #12?

**Comment by Evilhideki** [comment]
Essa issue é exclusivamente de componentes visuais da entrega da library básica. A issue #12 está relacionada a uma abordagem de conteúdo mais abrangente, como por exemplo, mensagens de erro, textos de apoio, textos informativos, etc.

**Comment by beatriztoccis** [comment]
Foi feita a primeira revisão dos labels, porém ainda entrarão mais nomenclaturas (revisadas) após a entrega final do wire. 
Por enquanto, vou deixar só o arquivo do excel, mas quando tivermos a versão final da revisão, subirei todas as palavras revisadas. 

[Componentes Revisados (1) (1).xlsx](https://github.com/pagarme/pilot/files/1197268/Componentes.Revisados.1.1.xlsx)
