### ISSUE TITLE
Wireframes de baixa fidelidade com especificação funcional (Mobile)

### ISSUE THREAD

**Issue by IedaOtero** [pagarme/pilot#190]
Mockup navegável da tela inicial da Home para os dois perfis de clientes: PSP e somente Gateway para mobile.

**Comment by Fausto-Junior** [comment]
A primeira ideia da versão mobile de home foi apresentada para todo o time de pilot e está no repositório de produtos. 

Esse é o link - http://d0o47m.axshare.com/

Aguardo comentários.

**Comment by vitorvmiguel** [comment]
Issue encerrada pelo PR https://github.com/pagarme/produtos/pull/31
