### ISSUE TITLE
Não tem emoji na descrição do repo

### ISSUE THREAD

**Issue by MarcoWorms** [pagarme/pilot#196]
✈️  ✈️  ✈️  ✈️  ✈️  ✈️  ✈️  ✈️  ✈️  ✈️  ✈️

**Comment by oPorks** [comment]
E o Logo da Pagar.me está atrasado, alguém sabe onde consigo o novo?

**Comment by felquis** [comment]
https://github.com/pagarme/pilot/issues/196#issuecomment-324973890 logo corrigida

**Comment by MarcoWorms** [comment]
kd emoji

**Comment by felquis** [comment]
Não tenho permissão de editar a descrição do repo :( kkkk

**Comment by MarcoWorms** [comment]
kd o PO
