### ISSUE TITLE
Propósito do produto

### ISSUE THREAD

**Issue by oPorks** [pagarme/pilot#197]
Cade o propósito / visão do produto? Deveria estar na primeira linha na minha visão.

**Comment by Evilhideki** [comment]
Minha sugestão:

Ser empreendedor não é uma tarefa fácil. Você deixa de passar tempo com a familia, com  os amigos, para empregar naquilo que você acredita: Seu negócio. Pensando que nossa solução deveria facilitar a sua vida, para que você gaste menos tempo procurando entender sua operação financeira-transacional com meios de pagamentos e mais tempo com o que importa, nós planejamos o Pilot: nossa solução de gestão financeira e transacional de Pagamentos.

Com um time de especialistas em produtos aliadas com um time de elite de desenvolvimento, pensamos em uma solução completa, que entrega relatórios e operações financeiras de forma customizada para cada tipo de negócio, para cada tipo de estrutura, seja o micro e pequeno empreendedor, seja grandes marcas do mercado.


### Dashboard com insights em temp real ###
A página inicial do Pilot, entrega os principais número para que você possa saber em uma primeira visita, um raio X de sua operação nos últimos dias. Volume total de transações, índices de chargebacks, e taxa de crescimento são alguns dos principais indicadores que você irá ver. Além disso, existem indicadores específicos para produtos especificos. Clientes de marketplace, podem visualizar indicadores na página inicial sobre sua operação no marketplace, mostrando os principais recebedores, o volume total transacionado, entre outros indicadores.

### Relatórios on-the go ###
Para clientes que precisam de relatórios mais específicos, será possível criar reports automatizados que serão disponibilizadas no Pilot para download. Além disso, novos tipos de relatórios serão disponibilizados ao longo do tempo de uso.

### Gestão flexivel de times ###
No Pilot, será possível gerenciar times e determinar seus níveis de acesso, indo de acesso administrativo a acesso somente leitura com a possibilidade de ocultar páginas com informações financeiras. Isso garante uma maior flexibilidade para sua operação, com a tranquilidade de que dados sensíveis estarão protegidos.

Esses são apenas alguns pontos em que pensamos em facilitar sua vida, para que você tenha mais tempo para se dedicar ao que realmente interessa: seu negócio.

**Comment by derekstavis** [comment]
Legal @Evilhideki! Gosto dessa descrição, só acho que seria importante deixar um pouquinho mais claro que essa descrição é o que o projeto tem a intenção de ser, só pra não parecer que já está pronto.

**Comment by Evilhideki** [comment]
Yep, concordo @derekstavis . Minha intenção ai foi entregar um propósito mais produto, menos software. Mas eu concordo em ser objetivo e mostrar quais features tem. Pensei em um contexto mais amplo, para estressar o propósito. O exemplo msm que vc deu, é sucinto na linha fina, e descreve em detalhes o produto em seguida. Gosto do modelo.

**Comment by Evilhideki** [comment]
Pilot é a plataforma de gestão financeira e transacional de meios de pagamentos para clientes Pagar.me. 

Insights em tempo real

A página inicial do Pilot, entrega os principais número para que você possa saber em uma primeira visita, um raio X de sua operação nos últimos dias. Volume total de transações, índices de chargebacks, e taxa de crescimento são alguns dos principais indicadores que você irá ver. Além disso, existem indicadores específicos para produtos especificos. Clientes de marketplace, podem visualizar indicadores na página inicial sobre sua operação no marketplace, mostrando os principais recebedores, o volume total transacionado, entre outros indicadores.

Relatórios on-the go

Para clientes que precisam de relatórios mais específicos, será possível criar reports automatizados que serão disponibilizadas no Pilot para download. Além disso, novos tipos de relatórios serão disponibilizados ao longo do tempo de uso.

Gestão flexivel de times

No Pilot, será possível gerenciar times e determinar seus níveis de acesso, indo de acesso administrativo a acesso somente leitura com a possibilidade de ocultar páginas com informações financeiras. Isso garante uma maior flexibilidade para sua operação, com a tranquilidade de que dados sensíveis estarão protegidos.

Esses são apenas alguns pontos em que pensamos em facilitar sua vida, para que você tenha mais tempo para se dedicar ao que realmente interessa: seu negócio.

**Comment by derekstavis** [comment]
Massa, agora ficou mais lean @Evilhideki :+1:

**Comment by Evilhideki** [comment]
Naicer @derekstavis . @beatriztoccis , precisa dar uma revisada nesse texto. Coloca isso na sua lista de tarefas pls?

**Comment by beatriztoccis** [comment]
Pilot é a plataforma de gestão financeira e transacional de meios de pagamentos para clientes Pagar.me. 

**Insights em tempo real** 
A página inicial do Pilot entrega os principais números para que você possa ter, em uma primeira visita, um panorama da sua operação. Volume total de transações, índice de chargeback, e taxa de crescimento são alguns dos principais indicadores aos quais você terá acesso. Além disso, existem indicadores específicos para produtos específicos.  

Clientes de Marketplace podem visualizar em sua página inicial informações referentes ao seu negócio, como principais recebedores, volume total transacionado, entre outros indicadores que fazem sentido para este tipo de operação.  

**Relatórios on the go** 
Para clientes que precisem de relatórios com mais especificidades, será possível criar reports automatizados, que estarão disponíveis para download. Além disso, novos tipos de relatórios serão disponibilizados ao longo do tempo de uso. 

**Gestão flexível de times** 
No Pilot, será possível gerenciar times e determinar seus níveis de acesso. Os níveis são abrangentes e vão desde acesso administrativo a somente leitura, nestes casos é possível ocultar páginas com informações financeiras. Assim, podemos garantir uma maior flexibilidade para sua operação, com a tranquilidade de que dados sensíveis estarão protegidos.  

Estas são apenas algumas das melhorias que pensamos para facilitar o seu dia-a-dia, para que você possa ter mais tempo para se dedicar ao que realmente interessa: o seu negócio. 

@Evilhideki @derekstavis

**Comment by derekstavis** [comment]
O texto tá excelente, mas eu acho ele better suited pra a página de marketing do produto dashboard no site. Eu fiz uma pré visualização de como o formato do texto fica no README e não ficou muito a cara de um projeto do Github.

Para o README o ideal é uma descrição mais curta do produto, de no máximo dois parágrafos de 3 linhas, sumariando a finalidade e filosofia do projeto (criar uma dashboard centrada no usuário e sua operação). Exemplo:

> Pilot é o codinome do projeto de software que compõe a próxima versão da Dashboard Pagar.me. Ele foi concebido desde seu início colhendo o feedback dos usuários (...)

Dentro do README, quando nos referenciarmos aos usuários do produto dashboard, podemos usar o seguinte tom:

> (...) na página inicial o Pilot entrega aos clientes do Pagar.me uma visão (...)

Assim a gente deixa claro que o Pilot precisa do serviço do Pagar.me para funcionar.

Para descrever as features é melhor ter uma lista de ítens mesmo, incluindo apenas os mais importantes, em não mais de 10 ítens, assim a gente dá uma leitura mais objetiva pra quem visita o repositório. Pensei em algo assim:

> * Insights em tempo real
> * Marketplace white-label
> * Relatórios on the go
> * Gestão flexível de times

@beatriztoccis @Evilhideki sorry alongar ainda mais a thread, mas acho importante conseguirmos montar um texto com esse tom para o README!

**Comment by beatriztoccis** [comment]
@Evilhideki @derekstavis , fiz uma nova descrição:  

Pilot é o codinome do projeto de software que compõe a próxima versão da Dashboard Pagar.me. Ele foi criado a partir de feedbacks dos usuários, para que eles possam ter uma experiência cada vez mais positiva com o Pagar.me e consigam focar no seu negócio.  

A home do Pilot entrega aos clientes um panorama da sua operação: é possível visualizar volume total de transações, índice de chargeback, taxa de crescimento, etc. Além disso, são disponibilizados alguns indicadores específicos que fazem sentido para diferentes tipos de operação.  

Funcionalidades:   
Insights em tempo real 
Marketplace white-label 
Relatórios on the go 
Gestão flexível de times

**Comment by darakeon** [comment]
Gente, faz algum sentido chamar o Pilot de sucessor da Dash e não nova versão? Vou usar o android de exemplo.

`Nova versão` me remete a como o `Nougat` está para `Android`. O que estamos fazendo me parece que é mais como se a `Dashboard` fosse o `Marshmallow` e o `Pilot` fosse o `Nougat`...

**Comment by Evilhideki** [comment]
@darakeon , seu raciocinio ta correto, mas a idéia em dar um novo nome, é justamente de trazer a idéia de um novo produto, e não a continuação da dash, que na percepção do cliente, apesar de ser muito friendly, é deficitária, não performa e tem problemas severos.

Ao usar um novo nome, entgregamos um "novo produto" para a operação do cliente, quebrando o vinculo com  a dash antiga =)

**Comment by darakeon** [comment]
@Evilhideki, era disso que estava falando. Não deveríamos passar a dizer então que é sucessor, não uma nova versão dela?

**Comment by Evilhideki** [comment]
seria o caso @darakeon , se o produto fosse um sucesso inquestionável. Tipo, Gol. vc tem "gerações"de gol.  Mas sempre que um produto ganha uma percepção equivocada do cliente, imediatamente muda-se o nome, como por exemplo, o Hotmail ser substituido por outlook, ou openoffice para libreoffice. 

Não se recomenda fazer o contrário por outra razão, porque se o produto ;é um sucesso, as pessoas vão continuar chamando ele pelo nome anterior (lollo > milkbar > lollo denovo).

**Comment by darakeon** [comment]
Mas chamar de nova versão da dash não faz exatamente que a má impressão que a dash tem seja mantida? Tava buscando exatamente um jeito de mostrar que é diferente...

Não quis dizer para manter o nome dashboard, estou falando exatamente o oposto...

**Comment by Evilhideki** [comment]
Concordo @darakeon . @beatriztoccis, podemos falar nesse sentido que o Lucas mencionou? O que vc acha?

**Comment by beatriztoccis** [comment]
@Evilhideki @darakeon acredito que essa mudança deixe mais claro ser um sucessor: 

Pilot é o codinome do novo serviço do Pagar.me. O produto foi criado a partir de feedbacks dos usuários, para que eles possam ter uma experiência cada vez mais positiva com o Pagar.me e consigam focar no seu negócio. 

A home do Pilot entrega aos clientes um panorama da sua operação: é possível visualizar volume total de transações, índice de chargeback, taxa de crescimento, etc. Além disso, são disponibilizados alguns indicadores específicos que fazem sentido para diferentes tipos de operação. 

Funcionalidades: 
Insights em tempo real 
Marketplace white-label 
Relatórios on the go 
Gestão flexível de times

**Comment by darakeon** [comment]
=)

**Comment by derekstavis** [comment]
Perfeito @beatriztoccis! Fiz algumas mudanças, o que acha?

Pilot é o codinome da nova dashboard do Pagar.me. O Pilot foi criado a partir de feedbacks dos usuários, para que eles possam ter uma experiência cada vez mais transparente de sua operação financeira no Pagar.me e consigam focar no seu negócio!

A home do Pilot entrega aos clientes um panorama da sua operação: é possível visualizar volume total de transações, índice de chargeback, taxa de crescimento, etc. Além disso, são disponibilizados alguns indicadores específicos que fazem sentido para diferentes tipos de operação.

Funcionalidades chave:
* Insights em tempo real
* Marketplace white-label
* Relatórios on the go
* Gestão flexível de times

**Comment by beatriztoccis** [comment]
@derekstavis acho só que podemos manter 'o produto' ao invés de Pilot na segunda frase para o texto não ficar repetitivo. Como a segunda frase ficou grande, precisa de uma vírgula depois de 'Pagar.me':

Pilot é o codinome da nova dashboard do Pagar.me. O produto foi criado a partir de feedbacks dos usuários, para que eles possam ter uma experiência cada vez mais transparente de sua operação financeira no Pagar.me, e consigam focar no seu negócio!

A home do Pilot entrega aos clientes um panorama da sua operação: é possível visualizar volume total de transações, índice de chargeback, taxa de crescimento, etc. Além disso, são disponibilizados alguns indicadores específicos que fazem sentido para diferentes tipos de operação.

Funcionalidades-chave:

Insights em tempo real
Marketplace white-label
Relatórios on the go
Gestão flexível de times

**Comment by derekstavis** [comment]
Perfect. Vou adicionar no README! :tada:
