### ISSUE TITLE
Organização do projeto

### ISSUE THREAD

**Issue by glauberfc** [pagarme/pilot#201]
Ao invés de se ter uma organização das pastas do projeto de acordo com as tecnologias (components, containers, etc.) não seria melhor uma organização por features?

Nesse [artigo](http://ryanlanciaux.com/blog/2017/08/20/a-feature-based-approach-to-react-development/) tem uma explicação melhor do que estou me referindo.

**Comment by derekstavis** [comment]
A principio me pareceu que já estamos usando algo parecido com a ideia do artigo. Os componentes tem ambos JSX, CSS e testes no mesmo diretório. Eventualmente poderemos adicionar actions e reducers, quando Redux fizer sentido pro projeto.

A ideia de divisão entre components e containers procura facilitar a divisão de o que é parte de nosso próprio UI toolkit, que pretendemos criar como um pacote separado da dashboard, e o que são componentes já compostos, com possíveis especificidades de regras de negócio.

**Comment by felquis** [comment]
Como a issue já está aberta a muito tempo vou fecha-la para manter a ordem, sobre a organização hoje estamos trabalhando mais em webapp/src/components, teremos também o webapp/src/containers que serão components compostos, e finalmente webapp/src/pages que é onde iremos usar o redux.

Agora estamos trabalhando na página de transações, estão estamos fazendo filtros, tabelas, modais, tooltips, gráficos e está na milestone https://github.com/pagarme/pilot/milestone/21

Até! :D
