### ISSUE TITLE
Erro em rótulo de cor

### ISSUE THREAD

**Issue by darakeon** [pagarme/pilot#205]
No PSD `colors`, em `Cores primárias`, o primeiro item da segunda
coluna está com o rótulo errado (correspondente ao primeiro item da
primeira coluna)

@alexandralugli

**Comment by vitorvmiguel** [comment]
@darakeon essa Issue não foi solucionada? Podemos encerrar?

**Comment by felquis** [comment]
Fechando, @darakeon se algo estiver errado reabra :D
