### ISSUE TITLE
Sitemap da área de minha conta

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#21]

**Comment by ericksahara** [comment]
Referenciando o entregável dessa issue:

https://github.com/pagarme/produtos/blob/master/Arquitetura/Minha%20conta/sitemap/sitemap_minha_conta.png

**Comment by Evilhideki** [comment]
@ericksahara , vamos usar o xmind para fazer sitemap, no repositório, depois suba a versão PNG do sitemap, e a versão editável (xmind) =)
