### ISSUE TITLE
Lista de funcionalidades da Minha conta

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#22]
atualmente, o cliente tem pouca opção para atualização de dados da sua própria conta, e muitas ações ainda dependem de validação de risco para serem feitas, mas em sua totalidade são feitas por ticket via RC.

No projeto Pilot, o cliente poderá enviar o pedido de alteração, que poderá ser acatado na dashboard admin ou não, de acordo com o Risco, que irá receber uma notificação dessa solicitação via lista de solicitações.

A nova área de "Minha conta"permite que o usuário faça o requerimento, ele mesmo enviando documentos como comprovante de conta bancária, comprovante de endereço, ente outros, ficando em "pending"de aprovação.

**Comment by ericksahara** [comment]
Pessoal, a matriz de funcionalidades se encontra no repositório de produtos, nesse diretório:

https://github.com/pagarme/produtos/tree/master/Arquitetura/Minha%20conta/funcionalidades

**Comment by Evilhideki** [comment]
O link está quebrado. @ericksahara , verifica o link novamente?

**Comment by ericksahara** [comment]
Corrigido, @Evilhideki.
