### ISSUE TITLE
Lista de funcionalidades "Configurações"

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#23]
O projeto Pilot apresenta uma nova lógica de comportamento, baseada em entrega de permissões e produtos que o cliente tem acesso. Isso modifica a forma como o cliente usa produtos. Considerando que os produtos consumiveís podem ser apresentado em formato de camadas, o cliente deve ter uma área onde ele possa configurar detalhes do seu uso do Pilot.

**Comment by vitorvmiguel** [comment]
Issue encerrada para tratamento na https://github.com/pagarme/produtos/issues/50
