### ISSUE TITLE
Melhorias no padrão do projeto

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#230]
Pessoal, nessas 3 semanas que estamos desenvolvendo o projeto algumas coisinhas que não tinham sido pensadas inicialmente acabaram surgindo e temos que endereça-las. Criei essa issue pra juntar todas as coisas:

- [x] **stylelint**: permitir até dois seletores
- [ ] ~**stylelint**: permitir apenas camel case~ dash-case é legal pra nomes de classes construídas no JS
- [x] ~**proptypes**: splitar sempre em arquivos separados~

**Comment by LeoNero** [comment]
Sobre splitar propTypes em arquivos separados, é em relação a **todos** os arquivos, incluindo os que o `.propTypes` tem poucas linhas? Qual a vantagem em splitar `.propTypes` pequenos em arquivos separados?

**Comment by felquis** [comment]
https://github.com/pagarme/pilot/issues/230#issuecomment-332201947 nenhuma.

**Comment by darakeon** [comment]
Não pode separar proptypes, não pega erro nele se separar

**Comment by derekstavis** [comment]
Fechando por inatividade.
