### ISSUE TITLE
Mudar jsx-a11y/label-has-for para aceitar nesting

### ISSUE THREAD

**Issue by felquis** [pagarme/pilot#239]
Ao usar um input dentro de um label, o linter me pede para colocar um htmlFor com o ID do input, porém o nesting deveria funcionar numa boa!

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md#rule-details

Vamos mudar essa config para aceitar nesting?

**Comment by derekstavis** [comment]
Fechado na issue #245
