### ISSUE TITLE
Medidor de força de senha

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#26]
## Medidor de força de senhas

Elemento integrante da issue #24 e relacionado a issue #25 

**Resumo do problema**

>Você quer garantir que os dados sensíveis de senhas são suficientemente fortes para prever ataques maliciosos.

**Exemplo:**

![best_old_40](https://user-images.githubusercontent.com/10881626/28190140-bbf5a9ae-67ff-11e7-9246-ab838e400f00.jpg)

**Uso adequado:**

- Use quando é necessário que os usuários escolham senhas para suas contas e acessos que precisam ser difíceis de quebrar com ajuda humana (engenharia social) ou por scripts;
- Use quando você precisar aumentar a complexidade de passwords dos seus usuários para aumentar a barreira de ataques automatizados ao sistema;
- Use quando você precisa garantir que seu usuário saiba que seu sistema exige uma boa lógica de segurança e que seus passwords precisam seguir essa regra.

**Modelo Pilot**
(será adicionado)

**Comment by felquis** [comment]
Related to #28

**Comment by mccraveiro** [comment]
@Evilhideki vamos bloquear senhas fracas? 
Na minha experiência como usuário: esses medidores nunca agregam muito valor e atrapalham a UX. Temos estudos a respeito? Seria legal compartilhar aqui :)

Acredito que uma medida mais eficiente em questão de segurança seria o uso de "two factor authentication" para a dashboard dos clientes (atualmente creio que temos apenas na dashboard admin)

**Comment by Evilhideki** [comment]
@mccraveiro yep.

Vamos pelo começo. Vc, enquanto trabalhador humilde da interwebs, nunca pode se tomar como base para tirar conclusões sobre ux funcionar. Por favor, exclua-se das análises (com exceção das de cores hahaha), porque em experiência de usuário, sempre tomamos por base o usuário mais deficitário em experiência, ou seja um [late majjority](https://en.wikipedia.org/wiki/Technology_adoption_life_cycle) tá de bom tamanho. 

Alguns estudos sobre isso;
[Carnegie Mellon researchers create new password strength meter;](https://www.cylab.cmu.edu/news_events/news/2016/carnegie-mellon-researchers-create-new-password-strength-meter.html)
[
Analyzing Password Strength and Efficient Password Cracking ](https://www.researchgate.net/publication/254670557_Analyzing_Password_Strength_and_Efficient_Password_Cracking)


Além disso, tem uma coleção de reports sobre senha e password mais [abrangente aqui.](https://www.nngroup.com/search/?q=password+strength)

Por fim, 

> Acredito que uma medida mais eficiente em questão de segurança seria o uso de "two factor authentication" para a dashboard dos clientes (atualmente creio que temos apenas na dashboard admin)

Para usuários comuns, 2FA é uma parada insanamente absurda de difícil. Se aqui no Pagar.me o nivel é alto a galera vira e mexe tem seus contratempos, imagina com usuário final. Além disso, isso ajuda a evitar a criação de senhas mais genéricas tipo `senha123`, `passward1!`, dado que mostramos dados altamente sensíveis. Esse tipo de padrão de interação é normalmente usado apenas na hora de criar a conta. No dia a dia, o usuário não precisa usar isso, portanto, é uma maneira de ajudar a aumentar o nível de senha dos usuários =)

Vale ainda citar que, para transações mais sensíveis como por exemplo, transferencias ou saque de dinheiro, seria importante pensar no uso de token via app, que seja mais simples que o 2FA.

**Comment by mccraveiro** [comment]
Concordo com você! Só não posso deixar de incluir isso na discussão: 

![image](https://user-images.githubusercontent.com/782333/28548834-a46dd544-70ac-11e7-8372-822ad9dc7c76.png)

**Comment by mccraveiro** [comment]
Quando formos pensar em 2FA, acredito que a forma mais acessível seja por SMS.
Apesar de não ser a forma mais segura :)

**Comment by Evilhideki** [comment]
Nem mais confiável também. O cara pode simplesmente não receber o sms. Por isso que os bancos recorreram inicialmente ao token digital que era o chaveirinho. 2FA para usuário comum, deve ser o mais simples possível, e ter um app para "chave digital"é perfeitamente justificável.
