### ISSUE TITLE
Matriz de funcionalidades

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#27]
Precisamos mapear todas as informações que usamos hoje para mostrar dados na dashboard e as informações que serão necessárias para os dados que o Pilot precisa exibir. Essa matriz é importante para adiantar modificações que precisarão ser feitas na API para suportar informações adicionais, caso aplicável.

@Evilhideki, tens ideia de como podemos modelar essa matriz?

Em um primeiro momento eu pensei em algo de alto nível como isso:

| Informação | Produção | Pilot | Referência na API |
|---|---|---|---|
| Total de transações | ✔︎ | ✔︎ | https://docs.pagar.me/... |
| Transações aprovadas | ✔︎ | ✔︎ | https://docs.pagar.me/... |
| Transações recusadas | ✔︎ | ✔︎ | https://docs.pagar.me/... |
| ... | ... | ... | ... |
| Produtos contratados | ✘ | ✔︎ | https://docs.pagar.me/... |

Dessa maneira já mapeamos de onde sai cada informação hoje e prever quais endpoints necessitarão de ajuste ou criação.

**Comment by felquis** [comment]
Achei genial essa idea!

**Comment by Evilhideki** [comment]
@derekstavis Eu acho que manter ela simples como vc sugeriu já é o suficiente. No entanto, posso recomendar termos mais algumas colunas, com dados que queremos/ devemos exibir, como por exemplo, volume médio de chargebacks por segmento, assim, o cliente pode visualizar se, segundo a média aritimética de chargebacks no segmento em que ele está, exemplo, alimentação, está baixo, médio ou irregular.

Sendo assim, teríamos mais colunas conteúdo ```informação``` e ```medidor```. Isso ajuda a galera a já pensar no formato visual do mesmo.

Dessa forma, as métricas futuras que recomendo seriam;
- média de volume de chargeback no segmento x o nivel do cliente
- média de transações histórica (dias, semanas, até 3 meses) (com possibilidade de abrir um gráfico especifico se o cliente quiser mais periodo que 3 meses.
- média de estornos do segmento versus o do cliente
- volume de transações reprocessadas
- volume histórico de antecipações ( o quanto ele vem antecipando em dias, semanas e até 3 meses)

Ach que o que me vem a cabeça agora é isso. Com certeza devem ter mais métricas que possamos extrapolar, certo @IedaOtero , @ericksahara e @Fausto-Junior =)

**Comment by derekstavis** [comment]
Trabalho iniciado no pagarme/produtos#4
