### ISSUE TITLE
Component: Filter

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#277]
#### Filtros

- [x] Verificar os alinhamentos, para funcionar direito com DateInput.
- [x] Verificar os calls backs
- [x] Escrever testes
- [x] Definir placeholder do DateInput
- [x] QA dos visual elementos pela galera de UI @flaviolee @nabuchler 

#### DateInput

- [x] Quando mais filtros está aberto o DateInput mistura com os checkboxes, add Z Index
- [x] Feedback visual da data de inicio e fim
- [x] Sidebar não ficou selecionada
- [x] Sidebar, ao ativar a opção DIA continua exibindo dois inputs
- [x] ~Digitar o mês 9 sem zero da erro na mascara~ :warning: 
- [x] Corrigir bug de timezone no dia 15/10
- [x] Add Sombra do DateSelector
- [x] Detalhes de estilo dos week day
- [x] Remover atalhos
- [x] ~Deixar call to action dos atalhos de teclado com nossa UI~

QA1:
**DateInput**

- [x] `font-size: 14px`
- [x] `color: #a0a0a0 ( --color-light-chromium-100)`

**DateSelector** 
- [x] Mês e dias da semana em Inglês
- [x] Menos border radius no dia inicial/final
<img width="65" alt="captura de tela 2017-10-18 as 18 21 27" src="https://user-images.githubusercontent.com/24230714/31741333-a6eec96c-b432-11e7-8f22-cf52d433b65f.png">

- [x] Últimos está sem acento

- [x] Títulos Últimos/Personalizado são mais claros
<img width="126" alt="captura de tela 2017-10-18 as 18 21 20" src="https://user-images.githubusercontent.com/24230714/31741346-b3435930-b432-11e7-8503-0ec491d28b8c.png">

- [x] Date selector está sem a sombra (talvez cagada do Vítor puxando a branch)

**Filtros**
- [x] Botão disabled no estágio inicial, enable somente quando algum filtro é selecionado
<img width="1185" alt="captura de tela 2017-10-18 as 18 04 28" src="https://user-images.githubusercontent.com/24230714/31741429-fa9fb30a-b432-11e7-9734-409624c410ec.png">

- [x] ~Número das parcelas ordenados bizarramente~
<img width="212" alt="captura de tela 2017-10-18 as 18 06 21" src="https://user-images.githubusercontent.com/24230714/31741407-e731079c-b432-11e7-9f6e-9f125e801053.png">

- [x] ~Modelo de negócios com a super área vazia (no mínimo rearranjar para o final)~

**As cores precisam ser revisadas de maneira geral, porém deixamos para quando #176 esteja Done**

**Comment by vitorvmiguel** [comment]
Essa Issue resolve a #165 também.

**Comment by LeoNero** [comment]
O `Corrigir título collapse/expand` eu só preciso confirmar com a galera de produtos depois certinho como ficou :)))))))))))))))))))))

**Comment by vitorvmiguel** [comment]
Adicionei um ponto no checklist pra galera de UI revisar os elementos @LeoNero.

@alexandralugli @flaviolee @nabuchler

**Comment by vitorvmiguel** [comment]
@alexandralugli consegue revisar a UI dos Tags?

<img width="649" alt="captura de tela 2017-10-13 as 15 16 47" src="https://user-images.githubusercontent.com/24230714/31560692-ab85c60c-b02b-11e7-9d6f-14aa7df9bde2.png">

**Comment by LeoNero** [comment]
@vitorvmiguel vlwss :D

**Comment by vitorvmiguel** [comment]
# Review de QA

**Input de busca**

- [ ] `font-size: 14px`
- [ ] `color: #a0a0a0 ( --color-light-chromium-100)`


**Date Selector** 

- [ ] Mês e dias da semana em Inglês
- [ ] Menos border radius no dia inicial/final
<img width="65" alt="captura de tela 2017-10-18 as 18 21 27" src="https://user-images.githubusercontent.com/24230714/31741333-a6eec96c-b432-11e7-8f22-cf52d433b65f.png">
- [ ] Últimos está sem acento
- [ ] Títulos Últimos/Personalizado são mais claros
<img width="126" alt="captura de tela 2017-10-18 as 18 21 20" src="https://user-images.githubusercontent.com/24230714/31741346-b3435930-b432-11e7-8503-0ec491d28b8c.png">


- [ ] Date selector está sem a sombra (talvez cagada do Vítor puxando a branch)



**Card filtros**

- [ ] Botão disabled no estágio inicial, enable somente quando algum filtro é selecionado
<img width="1185" alt="captura de tela 2017-10-18 as 18 04 28" src="https://user-images.githubusercontent.com/24230714/31741429-fa9fb30a-b432-11e7-9734-409624c410ec.png">

- [ ] Número das parcelas ordenados bizarramente
<img width="212" alt="captura de tela 2017-10-18 as 18 06 21" src="https://user-images.githubusercontent.com/24230714/31741407-e731079c-b432-11e7-9f6e-9f125e801053.png">

- [ ] Modelo de negócios com a super área vazia (no mínimo rearranjar para o final)


**As cores precisam ser revisadas de maneira geral, porém deixamos para quando #176 esteja Done**

**Comment by LeoNero** [comment]
`Número das parcelas ordenados bizarramente`. Onde está a coisa bizarra? O fato de não estar:
```
1x    2x
3x    4x
```
?

Se sim, eles não tão ordenados bizarramente. Bizarramente seria se fosse tudo aleatório kk :P

**Comment by vitorvmiguel** [comment]
@LeoNero `Número de parcelas ordenados bizarramente` é justamente não estar no sentido da nossa leitura ocidental, como você exemplificou:

```
1x    2x
3x    4x
```

Realmente aleatório seria mais bizarro!

**Comment by LeoNero** [comment]
Ah sim, com certeza tá errado, mas acho que bizarramente é uma palabra muito forte kk

**Comment by LeoNero** [comment]
`Botão disabled no estágio inicial, enable somente quando algum filtro é selecionado`. Os botoes atual não tem a prop disabled... criarei

**Comment by derekstavis** [comment]
Done in #324
