### ISSUE TITLE
Labels Status de Transação

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#279]
### Contexto

As tabelas e gráficos do Pilot possuem Labels de status de transação exibidos conforme design no Zeplin.

<img width="916" alt="captura de tela 2017-10-13 as 15 09 56" src="https://user-images.githubusercontent.com/24230714/31559908-ad11e846-b028-11e7-926f-c2676aeb2455.png">

Os labels são:

- [x] Boleto pago com valor inferior
- [x] Boleto pago com valor superior
- [x] Chargeback
- [x] Chargeback reapresentado
- [x] Recusada
- [x] Autorizada
- [x] Estorno pendente
- [x] Estornada
- [x] Aguardando pagamento
- [x] Paga
- [x] Processando
- [x] Esperando registro

Atualizando o que falta:
- [ ] nome das cores certinho
- [x] quais são as cores certinho
- [x] arrumar detalhes de design
- [x] criar properties.css
- [x] ver review do Felquis xD
- [x] ter property "noLabel", pra que o texto nao seja mostrado maaaas o texto ainda deve ser obrigatório pra quando a pessoa passar o mouse em cima da abreviacao aparecer o texto
- [x] arrumar testes

**Comment by LeoNero** [comment]
Uma dúvida sobre esse component: se eu clicar em algum, ele vai filtrar o tabela e o grafico?

**Comment by derekstavis** [comment]
A principio os labels nao sao botoes, correto @pagarme/creation ?

**Comment by flaviolee** [comment]
Perfect.
Sem botão. Sem clique. Apenas pra auxiliar a leitura do grafico/tabela.

**Comment by derekstavis** [comment]
Uma interface pra esse componente seria:

```
// The initials are derived from child text

<Legend color="green-accent">Paga</Legend>
<Legend outline color="green-accent">Aguardando Pagamento</Legend>

<Legend small color="green-accent">Paga</Legend>
<Legend small outline color="green-accent">Aguardando Pagamento</Legend>

// But also overrides the derived initials

<Legend initials="BPVS">Boleto pago com valor superior</Legend>
<Legend initials="BPVI">Boleto pago com valor inferior</Legend>
```

**Comment by LeoNero** [comment]
@derekstavis eu só nao colocaria `small` ou qualquer size pq aparentemente tudo é do mesmo tamanho :P

**Comment by LeoNero** [comment]
mara
