### ISSUE TITLE
CardSection

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#280]
### Contexto

Na última revisão dos elementos de UI, vários deles compartilham uma sessão cinza dentro do card, essa Issue pretende construi um componente genérico reutilizável para este elemento.

- [x] Expansível/Colapsável (mais filtros e gráfico)
- [x] Fixa (tabela)
- [x] configurar estilo
- [x] Implementar nova interface
- [x] Colocar exemplos no Storybook
- [x] Criar testes

**Comment by derekstavis** [comment]
### Referencia de design

![screenshot from 2017-10-10 15-24-11](https://user-images.githubusercontent.com/1611639/31403372-4953e198-adcf-11e7-8eab-870b4b33f74d.png)


![screenshot from 2017-10-10 15-24-45](https://user-images.githubusercontent.com/1611639/31403371-4935def0-adcf-11e7-8664-192c278a9783.png)


### Interface proposta

```jsx
<CardSection collapsible title="Title open" collapsedTitle="Title closed">
```

**Comment by LeoNero** [comment]
Vendo aqui, seria bom o pai passar o estado de aberto/fechado... por exemplo, o card de mais filtros usa o `isActivated` em vários lugares :) nao só na parte de abrir e fechar

**Comment by derekstavis** [comment]
Fair enough. Ele nao precisa ter estado interno :+1:

**Comment by derekstavis** [comment]
Atualizei o comentario com uma nova interface proposta
