### ISSUE TITLE
Biblioteca de Ícones

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#285]
### Contexto

A dashboard necessita Ícones em svg nos tamanhos 16x16, 20x20, 24x24, 32x32, necessitamos uma biblioteca de ícones para utilizar no Pilot

### Requisitos

**Menu & Header**
 - [x] Menu
 - [x] Balance
 - [x] Home
 - [x] Extract
 - [x] Transactions
 - [x] Reports
 - [x] Support
 - [x] Configuration
 - [x] Alert
 - [x] User

**Transações e Tabela de transação**
 - [x] Filters
 - [x] Summary
 - [x] Number of transactions
 - [x] Volume of transactions
 - [x] Pagination
 - [x] Reorder column
 - [x] Detalhe da transação 
 - [x] Recebedores
 - [x] Histórico da transação 
 - [x] Detalhe do Cliente

**Botões Tabela de transação**
- [x] Add transaction
- [x] Reverse
- [x] Reprocess
- [x] Rearrange column
- [x] Items per page
- [x] Maximize
- [x] Minimize

**Date Picker**
- [x] Calendar
- [x] Search

**Telas**
- [x] Withdrawal
- [x] Anticipation

**Outros**
- [x] Trash
- [x] Information
- [x] Help
- [x] Print
- [x] Save
- [x] Upload
- [x] Download
- [x] Card
- [x] Lock
- [x] Unlock
- [x] Mail
- [x] Show
- [x] Hide
- [x] Clear
- [x] Order up
- [x] Order down
- [x] Arrow up
- [x] Arrow down
- [x] Arrow left
- [x] Arrow right
- [x] Add
- [x] Remove
- [x] Check
- [x] Clock
- [x] Copiar

## Critérios de aceite

- [x] Os ícones devem estar no formato svg
- [x] Tamanho 24x24
- [x] Tamanho 32x32
- [x] Tamanhos 1x, 2x, 3x para telas de alta densidade
- [x] Ícones das bandeiras
- [x] Ícones no Zeplin
- [x] Pacote de Ícones no `former-kit`

**Comment by felquis** [comment]
@nabuchler foi para done mas a issue ficou aberta?

**Comment by LeoNero** [comment]
Coloquei "In progress" nessa issue... falta so um item da checklist :)

**Comment by derekstavis** [comment]
Disponível em https://github.com/pagarme/emblematic-icons
