### ISSUE TITLE
Arquivos do Photoshop no repositório

### ISSUE THREAD

**Issue by gpgabrielpaiva** [pagarme/pilot#292]
Remover PSDs do repositorio para agilizar o clone do repositório, acho que os PSDs podem ser movidos para uma branch separada.

**Comment by LeoNero** [comment]
Oi! Realmente ter arquivos de photoshop deixa a clonagem mais demorada... nós temos planos de colocar ou o projeto ou os arquivos PSD em outro repositório :)

**Comment by derekstavis** [comment]
A estratégia é a mesma que o @LeoNero falou. Estamos revisando todos os arquivos do Photoshop antes de criar um novo repo e subir eles. Dessa vez com LFS habilitado, se possível.

**Comment by felquis** [comment]
Em nosso kanban board a gente da a tela como terminada quando é feito upload da screen no Zeplin, então é aceito um PR deletando os psds que tem no source.

**Comment by derekstavis** [comment]
Finalizado!! Agora temos um monorepo e não temos mais arquivos PSD!!
