### ISSUE TITLE
Expected linebreaks to be 'LF' but found 'CRLF'

### ISSUE THREAD

**Issue by gpgabrielpaiva** [pagarme/pilot#295]
Esse erro está ocorrendo no Windows devido às configurações do eslint.

Essa solução funcionou para mim no package.json

```diff
  "eslintConfig": {
    "extends": "pagarme-react",
    "env": {
      "browser": true,
      "jest": true
    },
    "rules": {
+     "linebreak-style": 0,
      "react/jsx-filename-extension": 0
    }
  },
```

Posso abrir um PR?

**Comment by derekstavis** [comment]
Hm, isso vai desabilitar a regra, o que é longe do ideal, uma vez que a regra serve pra manter as quebras de linhas consistentes entre arquivos.

Pra corrigir esse problema na raíz o certo é criar um arquivo `.gitattributes` com o seguinte conteúdo:

```
* text=auto
webapp/* eol=lf
```

E depois normalizar qualquer arquivos que venha estar em CRLF pra LF.

**Comment by gpgabrielpaiva** [comment]
Imaginei que desativaria, por isso perguntei. Esse arquivo será criado?

**Comment by derekstavis** [comment]
Se vc tiver interesse em fazer esse pull request, fica a vontade!!

**Comment by andreolvr** [comment]
Sei que a issue já é um pouco antiga, mas o que acham de criar um arquivo .gitattributes e fazer com que ele converta tudo para LF? Dessa maneira, mesmo que o usuário faça o commit de arquivos com CRLF, o git vai mandar pro repositório como LF.

**Comment by felquis** [comment]
@andreolvr  tem um PR que a pessoa da issue criou porém não deu continuidade, se quiseres enviar um outro Pull Request já com as correções sugeridas será muito bem vindo.

**Comment by andreolvr** [comment]
Não tinha percebido que o @derekstavis já tinha dado essa solução, mas posso abrir um PR sim.

**Comment by andreolvr** [comment]
Criei o PR, aproveitando essa issue... O que acham de começar a usar o editorconfig para facilitar os contribuidores à seguirem o padrão de código? A maioria das IDE's suportam ele e evita muita dor de cabeça, se quiserem posso criar uma issue e um PR.
