### ISSUE TITLE
Enhancement: CardSection para exibir subtítulo

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#296]
# Por quê?
O CardSection possui um subtítulo na direita em algumas aplicações, portanto o componente genérico deveria prever esses casos

# Exemplo
<img width="1091" alt="captura de tela 2017-10-24 as 12 50 53" src="https://user-images.githubusercontent.com/24230714/31950295-0a4bd870-b8ba-11e7-80c1-5d8f6fad83ac.png">

**Comment by LeoNero** [comment]
Mara. Esse subtitulo tem só esse estilo? Se sim, daria pra fazer algo mais genéricozinho kk

**Comment by LeoNero** [comment]
Aaaah uma coisa que ficou de ver: cardSection só vai ser usado nos cards da tela de transação? Alguma outra tela usará ele?

**Comment by LeoNero** [comment]
E não só usar ele necessariamente dentro do Card... tipo, vai ter algo Collapsible em algum outro lugar?

**Comment by derekstavis** [comment]
Só tem esse texto mesmo. É uma prop nova que o CardSection recebe chamada de `subtitle`.

**Comment by vitorvmiguel** [comment]
@LeoNero 3 comentários separados? hahaha 

1) O @derekstavis respondeu.
2) A ideia do componente genérico é que seja usado em qualquer tela, não só transações, mas sempre com o mesmo estilo.
3) Vai ter collapsible em outros lugares, exemplo é o menu lateral onde o saldo pode ser expandido para abrir o botão de saque, entretanto possui um estilo diferente do CardSection, se fizer sentido splitar esse componente pra fora do Card vocês que mandam.

**Comment by derekstavis** [comment]
Eu acho desnecessário splitar. O código de um collapsible é tão simples que creio que não justifica criar um componente pra isso.

**Comment by LeoNero** [comment]
Thanks @vitorvmiguel  @derekstavis
