### ISSUE TITLE
Layout: Tabela

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#299]
# Tasks - Sprint 23/10-05/11
- [x] Revisar linha do header
- [x] Mudar cores das labels de status

# Exemplo atual
<img width="75" alt="captura de tela 2017-10-24 as 13 42 05" src="https://user-images.githubusercontent.com/24230714/31953137-2c9fa710-b8c1-11e7-99fe-2188fb2b98c7.png">
<img width="72" alt="captura de tela 2017-10-24 as 13 41 44" src="https://user-images.githubusercontent.com/24230714/31953138-2cc13a24-b8c1-11e7-844e-81ff4e3d380a.png">

**Comment by nabuchler** [comment]
Fechando a Issue. 

Telas no zeplin: 
[](https://zpl.io/25EQAX8)

![screen shot 2017-11-06 at 11 27 51](https://user-images.githubusercontent.com/31291529/32443275-91e721d8-c2e5-11e7-8984-47c0ec36b99a.png)

![screen shot 2017-11-06 at 11 27 55](https://user-images.githubusercontent.com/31291529/32443279-942cc718-c2e5-11e7-95ec-a143e92e81a1.png)
