### ISSUE TITLE
loaders

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#300]
### Contexto

As páginas e elementos necessitam de loaders para apresentarem feedback visual enquanto os componentes são carregados

### Exemplo

https://material.io/guidelines/components/progress-activity.html#

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [x] Loader Global para páginas
- [ ] Loader Local para elementos

**Comment by flaviolee** [comment]
Adiciono aqui uma primeira sugestao de loader feita com o logo.
(Gif no Photoshop. Sem muitos julgamentos, plz.)
![loader_logo](https://user-images.githubusercontent.com/29930809/40073596-a4cc8d30-584d-11e8-84aa-a514883afab4.gif)

Mas deixo também duas outras sugestoes extremamente interessantes do Codepen que parecem solucionar nosso problema:

Minha favorita - https://codepen.io/FilipVitas/pen/aNLgZz
Segunda opcao - https://codepen.io/Vestride/pen/vHzyk

**Comment by flaviolee** [comment]
Loaders locais, como em botoes, nao serao previstos agora por conta da complexidade de implementacao.
