### ISSUE TITLE
Layout: Páginas

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#301]
# Tasks - Sprint 23/10-05/11
- [x] Revisar níveis de navegação (botão voltar)
- [x] Revisar subtítulos

# Exemplo atual
<img width="858" alt="captura de tela 2017-10-24 as 13 55 19" src="https://user-images.githubusercontent.com/24230714/31953950-0aaf063a-b8c3-11e7-9299-9c5d2eabb964.png">

**Comment by nabuchler** [comment]
Fechando a Issue. 

Níveis de página já foi discutido e concluído.
**Ícone menu vai para sidebar, e a partir do segundo nível o ícone de seta para esquerda aparece ao lado do nome da página, no header.** 

![screen shot 2017-11-14 at 13 50 02](https://user-images.githubusercontent.com/31291529/32789680-95c8c84c-c943-11e7-9bd6-2e60a183deac.png)

**Comment by derekstavis** [comment]
Tá muito bonito isso ae <3
