### ISSUE TITLE
Component: Popover (Tooltip e Dropdown)

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#304]
### Contexto

Alguns componentes necessitam informações adicionais quando ocorre o mouseOver ou quando são clicadas e permanecem sobre a tela, como no caso de um dropdown.

### [Dropdown](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5a8f346c9bec222d2ddcddd4) e [Tooltip](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5a8c8403cac15d9401b160f2)

![image](https://user-images.githubusercontent.com/24230714/36699638-06f0157c-1b2c-11e8-8ae7-c9c345414fcb.png)
![image](https://user-images.githubusercontent.com/24230714/36699713-471d3788-1b2c-11e8-8d40-59da642463cf.png)
![image](https://user-images.githubusercontent.com/24230714/36699699-3b74b9c4-1b2c-11e8-8f8e-db2e1e5e22b6.png)

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [x] Deve conter um tooltip Primário
- [ ] Deve conter um tooltip Secundário
- [ ] Deve conter um popover de Sidebar
- [ ] ~Deve conter um tooltip de Gráfico~
- [x] Deve conter um popover de header
- [x] Tooltip acontece `on hover`
- [x] Popover acontece `on click`
- [x] Popover deve renderizar uma lista de links
- [x] Deve renderizar a _seta do balão_ na posição mais conveniente
- [x] O popover de header deve fazer logout
- [ ] O popover pode ter um título

**Comment by LeoNero** [comment]
Ah que component legal :D

**Comment by LeoNero** [comment]
Alguns components pra dar uma olhadinha:
http://react-component.github.io/tooltip/
http://wwayne.com/react-tooltip/

**Comment by LeoNero** [comment]
Qual seria uma interface legal pro Component? Fazer tipo o http://wwayne.com/react-tooltip/:
```
<a data-tip="React-tooltip"> ◕‿‿◕ </a>
<ReactTooltip place="top" type="dark" effect="float"/>
```
ou fazer tipo o react-tippy:
```
<Tooltip
  text="efwewf"
>
  <p>Hover me</p>
</Tooltip>
```
?

E tipo, faremos do zero ou usaremos alguma lib já prontinha?

**Comment by felquis** [comment]
@LeoNero boa pergunta, eu faria do zero para ter que usar o react createPortal ou a função legada. Porém se o component já tem uma implementação que funciona muito bem, recomendo fazer uma interface para servir como facade para a interface do que realmente faz o tooltip. Assim a gente consegue aceitar PRs que mudam a implementação do tooltip sem mudar a implementação da nossa interface.

Gostei bastante da interface react-tippy que vc mandou.

**Comment by LeoNero** [comment]
createPortal é do React 16, nao? Entao acho que não podemos usar ele ainda, mas tem aquela outra funcao `unstable_renderSubtreeIntoContainer` kk...

Eu gosto da interface tipo do react-tippy também, apesar de achar meio estranho ter que ficar colocando um component Tooltip around as coisas...

**Comment by LeoNero** [comment]
mas achar estranho nao significa que nao seja o melhor ne xD

**Comment by derekstavis** [comment]
Tooltip foi merged em pagarme/former-kit#85

**Comment by uselessdev** [comment]
Popover foi merged em pagarme/former-kit#93
