### ISSUE TITLE
Layout: Adicionar nova categoria de filtro

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#308]
# Tasks - Sprint 23/10-05/11
- [x] Adicionar a categoria método de captura e suas respectivas opções aos Filtros.

**Comment by nabuchler** [comment]
Fechando Issue.
Arquivo no Zeplin: 
[](https://zpl.io/2ykwzXq)

**Nova categoria de filtro:**
![screen shot 2017-11-06 at 11 30 29](https://user-images.githubusercontent.com/31291529/32443396-081a193c-c2e6-11e7-9abe-140a521639bc.png)
