### ISSUE TITLE
Inplace Editor

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#31]
## Inplace Editor
Elemento integrante da issue #24 e relacionado a issue #25 

**Resumo do problema**

>O usuário precisa alterar dados de forma rápida sem precisar abandonar a página atual.

**Exemplo:**

![best_old_17](https://user-images.githubusercontent.com/10881626/28225068-ae9309ca-68a7-11e7-9abf-2cf02b39a302.jpg)

**Uso adequado:**

- Use somente quando o dado a ser alterado for único (ou poucos) e não use em muitos;
- Use quando o valor que o usuário precisa editar estiver em formato simples, i.e. string de texto;
- Use se você precisa que o usuário possa editar um valor sem necessariamente ir a uma página de administração.

**Modelo Pilot**
(será adicionado)

**Comment by mccraveiro** [comment]
Aonde isso seria utilizado?

Creio que aparecer para editar apenas no "mouse over" cria uma barreira para dispositivos touch e cria um atrito com usuários novos que ainda não sabem dessa feature.

PS: gosto do editor de títulos daqui do github (tem um botão de editar ao lado)

**Comment by Evilhideki** [comment]
Em áreas em que o usuário poderia editar informações pontuais, que não se justifica criar uma página de edição somente para isso, por exemplo, edição de informações pessoais como nome, CNPJ, etc.
