### ISSUE TITLE
Layout: Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#333]
### Contexto

Finalizados os assets de tela de transações e detalhe de transação, é importante validar com alguns clientes alguns pontos de dúvida.

### Necessidades

- [x] Fluxo de aplicar filtro
- [x] Fluxo de comparar transações
- [x] Fluxo de linha expansível 
  - Clicar na linha e expandir
  - Clicar na linha e ir para detalhe
  - Clicar no botão expandir e ir para detalhe no botão
- [x] Fluxo reordenar colunas
- [x] Fluxo de split (Histórico de transação, Múltiplos recebedores)

### Pendências para o protótipo

- [x] Redesenhar tabela com separador definido para o botão expansível
- [x] Redesenhar expansível no pior cenário (21 labels), e no cenário ideal para visualização

**Comment by vitorvmiguel** [comment]
@IedaOtero e @Fausto-Junior precisamos de ajuda com o roteiro! :)

**Comment by vitorvmiguel** [comment]
## Roteiro de testes 
_Falta lapidar_

### Filtros

- (1) Liste as transações no período De: Até:, quantas com o status “Chargeback” encontrou?
- (3) Encontre uma transação pelo ID XXX, qual o status?
- (4) Liste apenas as transações de “cartão de crétito”, bandeira “visa” e “master”, de hoje, qual o valor da transação XXX?
- (5) Dessa lista exiba somente os itens de bandeira “master”, ???
- (6) Limpe todos os filtros, e encontre os últimos 7 dias
- (7) Encontre as transações estornadas do email XXX

### Lista de transações (tabela)

- (8) Do resultado que você obteve em (7) compare o valor das transações, qual o maior valor capturado entre as transações?
- (9) Compare o endereço dessas transações, são iguais?

### Reorganizar colunas

- (2) Personalize a tabela para exibir a coluna “ID de transação”, qual ID da transação com “Chargeback”?

### Detalhe de transações

- (10) Qual o meio de pagamento?
- (11) Qual a taxa de MDR da transação?
- (12) Quem é o responsável por Chargeback? E MDR?
- (13) Qual o valor líquido que cada recebedor vai receber?
- (14) Qual o status da parcela XXX?
- (15) Qual o MDR da parcela XXX?
- (16) A transação teve chargeback? Qual o valor?

@alexandralugli @Fausto-Junior @IedaOtero

**Comment by Fausto-Junior** [comment]
@vitorvmiguel @alexandralugli 

Essa é a sugestão de roteiro do time de arquitetura. É importante contextualizar o participante sobre o cenário em que ele se encontra. 

Ex:  (Como está) - Liste as transações no período De: Até:
       (Contextualizado) - Imagine que você precisa buscar as suas transações que ocorreram do último dia do mês até hoje.



**Filtros**

(1) Liste as transações no período De: Até:, (Objetivo: entendimento do date picker).
(2) Quantas com o status “Chargeback” encontrou? (Objetivo: entendimento da legenda de status). 
(3) Encontre uma transação pelo ID XXX. (Objetivo: utilização da busca aberta).
(4) Liste apenas as transações de “cartão de crédito”, bandeira “visa” e “master”, de hoje. (Objetivo: seleção de mais filtros).
(5) Limpe todos os filtros, e encontre as transações dos últimos 7 dias. (Objetivo: entendimento do limpar filtros e datas pré selecionadas). 

**Lista de transações (tabela)**

(6) Compare o endereço dessas transações, são iguais? (Objetivo: comparação de dados dentro do expansível).

Reorganizar colunas
(7) Personalize a tabela para exibir “status” na primeira coluna. (Objetivo: utilização do editar colunas).

**Detalhe de transações**

(8) Qual a taxa de MDR da transação? (Objetivo: entendimento das saídas da transação).
(9) Qual loja é responsável pelo Chargeback?(Objetivo: entendimento do compilado do split).
(10) Qual loja é responsável pelo MDR? (Objetivo: entendimento do compilado do split).
(11) Quanto a loja da Maria lucrou com essa transação? (Objetivo: entendimento do compilado do split).
(12) Qual loja foi responsável pelo estorno? (Objetivo: entendimento das saídas no detalhe do split).
(13) Essa transação teve chargeback? (Objetivo: entendimento do histórico da transação).
(14) Qual o valor do chargeback? (Objetivo: entendimento do evento chargeback no histórico da transação).
(15) Quais parcelas foram pagas e quais ainda serão recebidas na loja da Maria? (Objetivo: entendimento das parcelas no detalhe do split).
(16) Alguma das lojas antecipou seus recebíveis? (Objetivo: entendimento do status das parcelas no detalhe do split).


Qualquer coisa é só me falar.

**Comment by nabuchler** [comment]
Segue link com o protótipo da tela de transação: 
https://invis.io/RDF4R4S4Y#/269790896_01

:) 
Testem e me falem se vocês encontram alguma falha, ok? 
Lembrando que as telas seguem o roteiro e não são todas que estão completamente "programadas".

**Comment by nabuchler** [comment]
Segue o link com o protótipo do teste atualizado :) 

https://invis.io/RDF4R4S4Y#/269790896_01

Lembrando que começa com:
- Liste as transações no período **De:15/11 Até: 30/1**1 (ou periodo de 15 dias)

Se tiver algum errinho, vcs me falam? :)

**Comment by vitorvmiguel** [comment]
@nabuchler 

Da forma como está escrito o roteiro não consigo completar 100% das tarefas, o ideal seria reescrever os itens da forma como você implementou para que as tarefas fiquem mais claras.

- O passo (4) é complicado porque é necessário remover o ID da transação;
- O passo (7) se você clica em um X para eliminar um item, você não tem como se recuperar dessa ação, cai numa tela sem nada;
- Na tela de detalhes, você consegue fechar o histórico do Chargeback mas depois não consegue abrir novamente, se o cliente clicar ali ficará preso;
- Nas tabelas que exibem o Split, tem um label `Status da Transação` que está diferente do status global da transação. O status global é *Chargeback*  e nessa tabela é *Estorno Parcial*, sendo assim ou o label `Status da Transação` está errado, seria um `Status da Parcela` ou `Status do Recebedor`, ou então mantendo o mesmo label deveriam exibir o mesmo status.

**Comment by beatriztoccis** [comment]
Gente, a pedido do @vitorvmiguel deixei o teste mais amigável, só colocando o contexto na frente de cada passo que o @Fausto-Junior tinha sugerido acima. Vale ressaltar que o que eu acrescentei são sugestões de contexto, quem estiver aplicando o teste continua conduzindo da maneira que for mais adequada para o momento. 
Qualquer dúvida estou à disposição! 

**Contextualizado – Tela de Transações**

(1) Imagine que você precisa consultar as **transações** que foram realizadas entre os dias **15 e 30**. Como você faria?  (Objetivo: entendimento do date picker). 

(2) Certo! Agora, se alguém lhe solicitar as transações com status **Chargeback** ocorridas nos mesmos dias, como você as identificaria? (Objetivo: entendimento da legenda de status). 

(3) Ok! Vamos supor que em algum outro momento, você precise encontrar uma **transação pelo ID XXXX**, como você faria? (Objetivo: utilização da busca aberta). 

(4) Isso! Se no final do dia, você precisar encontrar todas as transações de **cartão de crédito** feitas com as bandeiras **Visa** e **Master** do dia de **hoje**, como você faria para encontrá-las? (Objetivo: seleção de mais filtros). 

(5) Boa! Você acabou de listar as transações de hoje, mas aconteceu um imprevisto e você vai precisar verificar **todas as transações dos últimos 7 dias**, qual a forma de fazer isso?  (Objetivo: entendimento do limpar filtros e datas pré selecionadas). 

(6) Perfeito! Agora, imagine que uma delas está com suspeita de fraude e você precisa **comparar** os **endereços** delas. Como você faria isso?  (Objetivo: comparação de dados dentro do expansível). 

(7) Boa! Muitas companies costumam colocar o **status** como a primeira coluna da tabela. Se você quisesse fazer isso, você faria? (Objetivo: utilização do editar colunas). 

 

**Contextualizado – Tela de Detalhes da Transação**

Aplicador do teste introduz o teste da tela de detalhes da transação.  

(8) Se você precisar identificar o **MDR** dessa transação, o que você faria? **Qual** é a **taxa** de MDR dessa transação? (Objetivo: entendimento das saídas da transação). 

(9) E qual o **seller responsável** por esse **MDR**?   (Objetivo: entendimento do compilado do split). 

(10) Boa! Se você precisar entrar em contato com o **seller responsável** pelo **Chargeback**, como você saberia qual é o seller responsável pelo chargeback desta transação? (Objetivo: entendimento do compilado do split). 

(11) Perfeito! E o **responsável** pelo **estorno**? Como você faria para verificar quem é nesse caso? (Objetivo: entendimento das saídas no detalhe do split). 

(12) Agora, se você precisasse informar o **quanto** a **loja da Maria lucrou** com essa **transação**, como você faria para consultar esse valor? (Objetivo: entendimento do compilado do split). 

(13) Boa! Imagine que você tenha que verificar se essa **transação recebeu chargeback**, como você confere isso? (Objetivo: entendimento do histórico da transação). 

(14) E qual o **valor do chargeback**? (Objetivo: entendimento do evento chargeback no histórico da transação). 

(15) Perfeito! Imagine que o pessoal da **loja da Maria** precisa saber **quais parcelas foram pagas e quais ainda serão recebidas**, como você verificaria isso pra passar eles? (Objetivo: entendimento das parcelas no detalhe do split). 
(16) Boa! Vamos supor que você precisa saber **se alguma das lojas antecipou os recebíveis**, como você conseguiria essa informação? (Objetivo: entendimento do status das parcelas no detalhe do split).

**Comment by nabuchler** [comment]
Seguindo o roteiro acima (da Bia), segue o link para o protótipo :) 

https://invis.io/X4FCWPV8GBF#/269790896_01

**Comment by vitorvmiguel** [comment]
- No passo (4) após filtrar cartão de crédito a tabela exibe linhas de boleto.
- No passo (6) o expansível das duas transações é exatamente idêntico e não tem endereço que é o que o roteiro pede.
- Após expandir no passo (6) você não consegue fazer o passo (7) com as linhas expandidas, tem que fechar as linhas pra poder ir para o (7). Com as linhas expandidas você vai do (6) para o (8).

Se aplicarmos o teste assim vamos gerar mais problema do que encontrar respostas.

**Comment by nabuchler** [comment]
Segue o link do protótipo com todas as questões acima atualizadas.

https://invis.io/X4FCWPV8GBF#/269790896_01

:)

**Comment by alexandralugli** [comment]
Não consegui avançar do passo 5.

**Comment by beatriztoccis** [comment]
Gente, tinha copiado e colado ao contrário os passos 5 e 6, desinverti ali em cima. Foi mal :(

**Comment by vitorvmiguel** [comment]
A tela de detalhe da transação precisa ser revisada.

**Comment by nabuchler** [comment]
Oi pessoal, 

Segue o link do protótipo. 

Lembrando que o moderador do teste deve lembrar que: 
_(3) Ok! Vamos supor que em algum outro momento, você precise encontrar uma transação pelo ID XXXX, como você faria? (Objetivo: utilização da busca aberta)._ 
Induzir o usuário a apenas buscar pelo Id xxx dentro do período de 15 dias. 

_6) Compare o endereço dessas transações, são iguais? (Objetivo: comparação de dados dentro do expansível)._
Não temos endereço no expansível. Pediremos para comprar o e-mail de cada transação. 

_(7) Personalize a tabela para exibir “status” na primeira coluna. (Objetivo: utilização do editar colunas)._
O item 'status' já vem como default na primeira coluna da tabela. 
Pediremos para o item 'id de transação' ser exibido na primeira coluna. 

Não esquecer de introduzir para o detalhes de transação.
A primeira linha da tabela vai para detalhes de transação. 

_(15) Quais parcelas foram pagas e quais ainda serão recebidas na loja da Maria? (Objetivo: entendimento das parcelas no detalhe do split)._ 
Quais parcelas foram pagas e quais ainda serão recebidas da LOJA DO PEDRO. 

https://invis.io/X4FCWPV8GBF#/269790896_01

**Comment by alexandralugli** [comment]
Link do protótipo navegável em Axure: https://15lrag.axshare.com/#c=2
