### ISSUE TITLE
Enhancement: Suporte a temas

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#335]
### Contexto

O Pilot contém uma biblioteca de componentes que atenderá não só a Pagar.me, mas também empresas irmãs, por isso é necessário que os componentes sejam refatorados para suportar a aplicação de temas, para facilitar a troca de cores e adaptação para outras marcas da empresa.

### Tasks

- [x] Buttons
- [x] Cards
- [x] Alerts
- [x] Switch
- [x] Progress
- [x] Tags
- [x] TabBar
- [x] Dropdown
- [x] Input
- [x] Grid
- [x] SegmentedSwitch
- [x] Legend
- [x] Modal
- [x] DateSelector
- [x] DateInput
- [x] Pagination

**Comment by derekstavis** [comment]
Hoje temos um suporte basico a temas via CSS custom properties. Precisamos fazer uma passada geral por todos os componentes aplicando o [`react-css-themr`](https://github.com/javivelasco/react-css-themr), o que pede um mass rename e padronização de todas os nomes de classes CSS.

É possível ver um bom exemplo de suporte a temas no [`react-toolbox`](https://github.com/react-toolbox/react-toolbox).

**Comment by derekstavis** [comment]
Closed in #347
