### ISSUE TITLE
Layout: Mini Review de UI

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#341]
## Contexto

Após revisão alguns pontos de UI necessitam alteração.

## Requisitos

- [x] Rever ícone estornar
- [x] Rediagramar os inputs do adicionar transação
- [x] Botão de URL do boleto > Link do boleto
- [x] Forma do pagamento > Dados do pagamento
- [x] Tela de transação, no Filtro adicionar número de opções selecionadas
- [x] Mudar link do boleto (no expansível da tabela) para um botão.

**Comment by nabuchler** [comment]
**Tela de transação, no Filtro adicionar número de opções selecionadas:**

![screen shot 2018-01-16 at 17 15 35](https://user-images.githubusercontent.com/31291529/35008908-3adfcde4-fae5-11e7-9958-099400c250ad.png)

**Comment by nabuchler** [comment]
**Mudar link do boleto (no expansível da tabela) para um botão.**

![screen shot 2018-01-16 at 18 08 40](https://user-images.githubusercontent.com/31291529/35012923-aa6cd38e-faf2-11e7-906a-7149e1b4bf9c.png)

**Comment by nabuchler** [comment]
Link para filtro e tabela atualizados: 

https://zpl.io/a8EelEg

<3
