### ISSUE TITLE
Container: Forms

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#350]
### Contexto
Como um desenvolvedor de interfaces utilizando a plataforma do Pagar.me 
Eu quero construir formulários com validação de campos
Para que eu possa coletar inputs dos clientes

### Requisitos

- [x] Deve validar inputs de texto
- [x] Deve validar inputs numéricos
- [x] Deve validar inputs de email
- [x] Deve validar inputs de senha
- [x] Deve agrupar inputs (Ex.: `"address": {"street": "Av Paulista", "number": "123"}`)

### Exemplo
https://github.com/derekstavis/react-vanilla-form

### Proposta de interface

```jsx
TODO
```

### Critérios de aceite

- [ ] Deve

**Comment by derekstavis** [comment]
Done in pagarme/react-scripts-former-kit-dashboard
