### ISSUE TITLE
Enhancement: Split de Pacotes 

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#351]
### Contexto
_Como_ um desenvolvedor de interfaces utilizando a plataforma do Pagar.me 
_Eu quero_ poder utilizar os componentes e temas da Plataforma do Pilot
_Para que_ eu possa construir páginas sem dependências da estrutura do projeto 

### Requisitos

- [x] Deve conter um pacote de Biblioteca de Componentes (Former)
- [x] Deve conter um pacote de Temas (Skin)
- [x] Deve conter um pacote de ícones
- [x] ~Deve conter um pacote de Nova Dashboard Pagar.me (Pilot)~

### Exemplo
https://github.com/pagarme/pilot/tree/package-split

### Proposta de interface

```jsx
TODO
```

### Critérios de aceite

- [ ] Deve

**Comment by derekstavis** [comment]
Done!
