### ISSUE TITLE
Container: Application Shell 

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#352]
### Contexto
_Como_ um desenvolvedor de interfaces utilizando a plataforma do Pagar.me 
_Eu quero_ uma estrutura de aplicação
_Para que_  eu possa construir páginas

### Requisitos

- [ ] Deve conter um gerenciamento de Estado
- [ ] Deve conter um roteamento de páginas
- [ ] Deve conter um Header
- [ ] Deve conter um Footer
- [ ] Deve conter um Sidebar

### Exemplo
![image](https://user-images.githubusercontent.com/24230714/34963059-a14b92f6-fa2d-11e7-8591-ab6aa357a88a.png)

### Proposta de interface

```jsx
TODO
```

### Critérios de aceite

- [ ] Deve

**Comment by LeoNero** [comment]
#353 depende dessa issue, correto?

**Comment by LeoNero** [comment]
@derekstavis essa issue se refere ao component Layout, correto?

**Comment by derekstavis** [comment]
Done
