### ISSUE TITLE
Page: Login

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#354]
### Contexto

Os clientes Pagar.me que utilizarão a nova Dashboard necessitam de uma tela de Login que esteja de acordo com a nova identidade visual do Pilot e atenda às necessidades de usabilidade identificadas na Dashboard atual.

### Requisitos

- [x] Deve conter campos de usuário e senha
- [x] Deve conter campo opcional de 2FA 
- [x] Deve conter campos de esqueci senha
- [x] Deve conter link para tela de cadastro

**Comment by vitorvmiguel** [comment]
@ericksahara consegue compartilhar o wireframe?

**Comment by ericksahara** [comment]
@vitorvmiguel, @alexandralugli 

Segue o link: https://q7hgtx.axshare.com/

Está bem desatualizado, e a proposta de wireframe não foi validada com ningúem ainda.

**Comment by alexandralugli** [comment]
![login_01_1](https://user-images.githubusercontent.com/8549244/35355487-98ca47b8-0134-11e8-8e08-27c2b403f2d7.png)
![login_01_2](https://user-images.githubusercontent.com/8549244/35355488-990f0484-0134-11e8-9347-a908a866d933.png)
![login_02_1_recuperar_senha](https://user-images.githubusercontent.com/8549244/35355489-9945e274-0134-11e8-87be-9314b46b40c6.png)
![login_02_2_recuperar_senha](https://user-images.githubusercontent.com/8549244/35355491-997b9978-0134-11e8-80e4-17c67da69901.png)

Zeplin: https://zpl.io/VxK3JKE

**Comment by Deivis** [comment]
closed in pagarme/formerkit#6
