### ISSUE TITLE
Page: Cadastro

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#355]
### Contexto

Os clientes Pagar.me que utilizarão a nova Dashboard necessitam de uma tela de Cadastro que esteja de acordo com a nova identidade visual do Pilot e atenda às necessidades de usabilidade identificadas na Dashboard atual.

### Requisitos

- [x] Deve possuir campo de nome completo
- [x] Deve possuir campo de empresa
- [x] Deve possuir campo de email
- [x] Deve possuir campo de senha

**Comment by alexandralugli** [comment]
![cadastro_01](https://user-images.githubusercontent.com/8549244/35356809-aded8020-0138-11e8-84a8-4d4a3ff14e2b.png)
![cadastro_02](https://user-images.githubusercontent.com/8549244/35356810-ae2860b4-0138-11e8-8eef-82fcec07a762.png)

@beatriztoccis Poderia revisar os textos dessas telas, por favor?

**Comment by beatriztoccis** [comment]
@alexandralugli segue a revisão da tela acima (só está aqui o que houve alteração):  :)

FUNÇÃO | ORIGINAL | REVISADO
------------ | ------------- | ---------
Parágrafo de descrição  | A Dashboard Pagar.me é um painel de controle de operações. Através dela você pode ter acesso a diversos dados relevantes para seu dia a dia de trabalho, e também pode realizar diferentes ações cotidianas com facilidade, como estornos, consulta de saldo e mais. | A Dashboard Pagar.me é um painel de controle de operações. Através dela você tem acesso a diversos dados relevantes para o seu dia a dia de trabalho, e também pode realizar diferentes ações cotidianas com facilidade, como estornos, consulta de saldo e mais. 
Frase + botão de login   | Já é cadastrado? Faça o login  | Já possui cadastro? Faça o login  
Mensagem de feedback | Pronto! Você receberá um e-mail com as instruções para a ativação de sua conta.  | Pronto! Você receberá um e-mail com as instruções para a ativação da sua conta.
