### ISSUE TITLE
Layout: Minha Conta

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#356]
### Contexto

Os clientes Pagar.me que utilizarão a nova Dashboard necessitam de uma tela de Minha Conta que esteja de acordo com a nova identidade visual do Pilot e atenda às necessidades de usabilidade identificadas na Dashboard atual.

**Comment by alexandralugli** [comment]
![minha conta](https://user-images.githubusercontent.com/8549244/35756342-11234470-0852-11e8-9530-264c333aec3c.jpg)

Zeplin: https://zpl.io/am1zDP6

**Comment by derekstavis** [comment]
Feito!
