### ISSUE TITLE
Layout: Configurações

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#357]
### Contexto

Os clientes Pagar.me que utilizarão a nova Dashboard necessitam de uma tela de Configurações que esteja de acordo com a nova identidade visual do Pilot e atenda às necessidades de usabilidade identificadas na Dashboard atual.

**Comment by flaviolee** [comment]
Layout da pagina no Zeplin.
Segue link: https://zpl.io/b6QONzW

Posto o jpg aqui ASAP. =p

**Comment by flaviolee** [comment]
Jpgs das paginas agora:

![configuracoes - geral](https://user-images.githubusercontent.com/29930809/35805766-40ec3892-0a64-11e8-8557-455cc846d449.jpg)

![configuracoes - geral aberto](https://user-images.githubusercontent.com/29930809/35805770-4532f38c-0a64-11e8-9e3b-06f9fa245fe4.jpg)

![configuracoes - produtos](https://user-images.githubusercontent.com/29930809/35805779-4a47f598-0a64-11e8-9248-50d31c2df4f0.jpg)

![configuracoes - equipe](https://user-images.githubusercontent.com/29930809/35805783-50271df4-0a64-11e8-85af-77ef499c8838.jpg)

**Comment by flaviolee** [comment]
Registrando aqui que discuti alguns pontos com o @ericksahara e temos alterações para fazer no conteudo da aba Equipe.

Ja tenho o wireframe com as novas sugestões.
Vou finalizar assim que fecharmos os estados dos componentes.

**Comment by flaviolee** [comment]
Alterações feitas.
Tudo ok agora.

![configuracoes - equipe aberto](https://user-images.githubusercontent.com/29930809/36432080-05193d8a-1638-11e8-883e-345c8e56fe1c.jpg)

https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5a73714b3cc21579fc347875
