### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#358]
### Contexto

Os devs e uxs que utilizarão o Pilot como base de desenvolvimento de novos produtos, necessitam que tanto o código quanto o styleguide possuam uma documentação compreensível que dê autonomia a eles.

### Requisitos

Documentação Interna (Wiki)
- [ ] Documentação interna do processo de criação 

Material de Divulgação ([exemplo](https://airbnb.design/building-a-visual-language/))
- [ ] Documentação pública do processo de criação (Design Site)

Styleguide Público ([exemplo](https://atlassian.design/))
- [x] Documentação pública do `styleguide`
- [x] Documentação pública do `former-kit`
- [x] Documentação pública do `create-former-app`

Componentes
- [x] Alert/
- [x] Card/
- [x] DateInput/
- [x] Footer/
- [x] LinearProgress/
- [x] RadioGroup/
- [x] Switch/
- [x] Tag/
- [x] ~Typeset/~ Vai ficar junto da doc de ThemeProvider
- [x] Avatar/
- [x] Checkbox/ 
- [x] DateSelector/
- [x] Grid/
- [x] Input/ 
- [x] Modal/
- [x] SegmentedSwitch/
- [x] TabBar/
- [x] Button/
- [x] CheckboxGroup/
- [x] Dropdown/
- [x] Header/
- [x] Legend/
- [x] Pagination/
- [x] Sidebar/
- [x] Table/

### Exemplo

https://github.com/derekstavis/react-vanilla-form

**Comment by ericksahara** [comment]
Uma proposta de estrutura para o nosso guia, contemplando a documentação pública do processo de criação (How we design) e o styleguide:

![design-system-sitemap](https://user-images.githubusercontent.com/2717339/35511463-2a779bf0-04e3-11e8-89f5-04bc6fcff6ae.png)

**Comment by vitorvmiguel** [comment]
Achei legal a estrutura Erick! Você chegou a olhar alguma ferramenta que nos ajude a construir? Sugestão consultar devs e uxs e encontrar uma ferramenta que agrade à todos ;)

**Comment by flaviolee** [comment]
Precisamos também **definir nossos design principles**.
Vamos manter a discussão nessa issue, para evitar achar a melhor forma de fazer isso agora sem afetar o roadmap de todos os envolvidos.

Precisamos principalmente chegar em um consenso sobre **para quem vamos escrever** nossos princípios e **que objetivo desejamos alcançar**.

**Comment by flaviolee** [comment]
Vou começar dando minha sugestão:

Publico: inicialmente nós mesmos. Pessoas da area de tecnologia que vivenciarao o dia-a-dia da companhia e precisam de um norte sobre decisões de design num geral, para criarmos consistência em nossos produtos.

Objetivo: Garantir que todos estejam com o mesmo mindset/na mesma página ao passar pelos processos de criação de nossos produtos.

Referência que mais gosto: https://www.designprinciplesftw.com/collections/paypal-design-principles

Minha sugestão para nossos design principles (Tamanho do texto e linguagem): https://stonepagamentossa-my.sharepoint.com/:w:/g/personal/beatriz_tocci_pagar_me/EZzr2wAF9gREgtq3eWFj-O0BsWZLIf0ShCvZsg04ybdVBg?e=kfh8K8

**Comment by flaviolee** [comment]
@ericksahara @Fausto-Junior @alexandralugli @IedaOtero @flaviamoreira @ananemes @beatriztoccis Bora centralizar aqui a discussão. <3

**Comment by ericksahara** [comment]
Design system

Público (para quem?)
Designers, desenvolvedores e todas as áreas envolvidas na concepção do produto.

Objetivo (Por que?)

Disseminar a cultura e a importância do Design na concepção de produtos, e servir como um guia para orientar todos os times a construirem produtos seguindo os princípios de Design e boas práticas.

**Comment by ericksahara** [comment]
Adicionando o link da documentação dos componentes:

https://stonepagamentossa-my.sharepoint.com/:x:/r/personal/erick_sahara_pagar_me/_layouts/15/WopiFrame.aspx?sourcedoc=%7B24E346CF-8003-495F-AC04-35633D1684D5%7D&file=components-doc.xlsx&action=default

cc: @vitorvmiguel @alexandralugli
