### ISSUE TITLE
Chat para comunicação com a comunidade

### ISSUE THREAD

**Issue by woliveiras** [pagarme/pilot#359]
Olá, pessoal!

Como parte de um movimento pra motivar as pessoas a contribuírem com os projetos open source, normalmente se cria uma espécie de "comunidade" em volta do projeto.

Se for interessante pra vocês e utilizarem o Slack internamente, talvez começar pelo chat seja uma boa.

Daria pra usar o Gitter também, porém a galera já está usando Slack nos celulares. Dificilmente vão querer utilizar mais que um comunicador. 

Dá pra usar o workspace do Slack pra que as pessoas entrem nos canais da Pagar.me, mas sem precisar criar outro domínio/conta no Slack pra isso.

Assim os externos também se sentem mais próximos da Pagar.me, para contribuir, por serem convidados para onde estão todos os devs e devas da empresa. :)

O que acham?

https://get.slack.help/hc/en-us/articles/202518103-Multi-Channel-and-Single-Channel-Guests

**Comment by lucasjs** [comment]
Oi oi!

Internamente usamos o Slack e abertamente usamos o Gitter: [https://gitter.im/pagarme](https://gitter.im/pagarme)

Sobre o Workspace do Slack não sabia não. :frowning:

O que acham pessoal?

**Comment by marquinhoalm** [comment]
Tem o Discord que é bom também. Inclusive o pessoal do React utiliza ele como canal oficial

**Comment by felquis** [comment]
Eu acho o Slack mais fácil de usar do que o gitter, ao msm tempo o gitter
funciona bem. Mas o Slack é melhor para usar vários chats juntos.

Em 17 de jan de 2018 00:12, "Marquinho Almeida" <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
Concordo com o @felquis nesse ponto.

Acho da hora o Slack no celular (apesar dele consumir uma bateria desgracenta)

**Comment by suzanabueno** [comment]
gente, resolvido aqui? vou fechar se acreditarem já terem discutido uma solução.
