### ISSUE TITLE
Refactor: Ícones por props

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#364]
### Contexto

Os componentes necessitam receber ícones por `props` da mesma forma que i18n

### Exemplo

https://github.com/pagarme/pilot/pull/346

### Sugestão de interface

No caso de componentes que recebem apenas um ícone, usar apenas uma prop `icon`.

```jsx
<SomeComponent icon={} />
```

No caso de receberem mais de um ícone:

```jsx
<SomeComponent icons={{
  back: <IconBackArrow />,
  forward: <IconForwardArrow />
}} />
```

### Critérios de Aceite

**Lista de Componentes**

- [x] Buttons
- [x] Cards
- [x] Alerts
- [x] DateSelector
- [x] DateInput
- [x] Inputs
- [x] Pagination
- [x] Avatar
- [x] Dropdown
- [x] HeaderMenu
- [x] Sidebar

Para rever:
- [x] Rever validacao do Sidebar
- [x] No Avatar, nao precisa de size quando passa icon... pq o size ja vai estar no Icon passado. Isso esta certo? O que melhorar?
- [x] DateInput esta com problemas na story e nos testes pq usam DateSelector. O DateInput deve receber os icons e passar pro DateSelector ou o DateInput nao recebe o icons e ele ja passa direto os icons pro DateSelector?

Por fim:
- [ ] Rever components pra garantir que nao faltou nenhum componente que usa icone

**Comment by LeoNero** [comment]
Acho que o first step seria ver quais podem receber mais de um icone...
ou so vai fazendo na ordem que ta na issue e vemos separados pra cada component um por vez xD

**Comment by LeoNero** [comment]
@derekstavis filters vai pra biblioteca de components tambem?

**Comment by derekstavis** [comment]
Não! Vou tirar da lista!!

**Comment by LeoNero** [comment]
Okay

**Comment by derekstavis** [comment]
Pode remover da lista caso tiver algum que não precise. Vale o mesmo pra caso falte algum que precisa na lista!

**Comment by lucasjs** [comment]
@derekstavis O ícone no `cards` fica no `cards title` né? Pelo que analisei já está passando, e no `input` também.
