### ISSUE TITLE
link: layout de telas

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#370]
### Contexto

O Ghostbusters está desenvolvendo uma nova feature para os clientes Pagar.me. Essa feature de `link de pagamentos` consiste em enviar para o cliente o link de uma transação que inicia o checkout para pagamento. O fluxo consiste em:

1. O cliente Pagar.me cria um link de pagamentos via uma página/modal
2. O cliente Pagar.me envia o link para o comprador pagar
3. O comprador recebe o link e ao abrir é direcionado para uma tela de resumo externa (baseada no Pilot), que exibe os itens e valor da transação
4. O comprador clica em pagar/finalizar e é direcionado para o Checkout v1.1 do Pagar.me

### Requisitos
O cliente Pagar.me pode fazer a gestão dos links pela dashboard atual para isso necessita:

- [x] Página com Lista de links (semelhante a transações)
- [x] Detalhe do link (semelhante a detalhe de transações) *** mais energia por novidade 
- [x] Formulário de criação de links (semelhante ao modal de adicionar transação)
- [x] Tela de resumo externa (Pilot)

### precisamos entregar para o Ghostbusters até 15/02, para não atrasar a entrega deles

**Comment by ericksahara** [comment]
Pessoal,

Adicionando o link do protótipo para visualizar as páginas de lista de pagamentos dentro da Dash:

https://usi6xl.axshare.com/
pw: eppagarme

Próximo passo é criar a tela de resumo externa, utilizando os componentes do Pilot.

@zitoloco, @vitorvmiguel, @alexandralugli

**Comment by vitorvmiguel** [comment]
Encerrando Issue duplicada, tratada em https://github.com/pagarme/ghostbusters/issues/53
