### ISSUE TITLE
revisitar arquitetura e layout do extrato

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#376]
### Contexto

A tela de extrato é uma das mais importantes para os clientes do Pagar.me, nela é onde as informações consolidadas para a contabilidade dele. Precisamos de uma arquitetura e layout onde ele consiga encontrar no extrato do Pagar.me a informação equivalente ao que ele vê em sua conta bancária.
> “Quero olhar meu extrato do banco e comparar com o extrato da dashboard do Pagar.me e saber qual o valor líquido eu recebi, quais são as taxas e quanto meus recebedores receberam.” - Alcides (DM10)

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [x] Revisitar a arquitetura e layout do extrato

**Comment by alexandralugli** [comment]
Link para o Zeplin: https://zpl.io/adAdjEp

**Comment by alexandralugli** [comment]
Link para o Zeplin: https://zpl.io/aBO7ddp
