### ISSUE TITLE
sketch symbols 

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#386]
### Contexto

Para ganharmos velocidade de desenvolvimento dos layouts, precisamos utilizar todo o potencial do Sketch com os símbolos. 

### Exemplo

https://sketchapp.com/docs/symbols/

### Requisitos e Critérios de Aceite

- [x] Inputs
- [ ] Dropdown

-------------------------

- [x] Alerts 
- [ ] Radio 
- [ ] Checkbox Group
- [x] Sidebar

-------------------------

- [x] Button
- [ ] ContextSwitch
- [ ] Tooltip
- [ ] Popover
- [ ] Pagination
- [x] TabBar 
- [ ] Date/Time Picker

-------------------------

- [ ] Switch
- [ ] Tags
- [x] Legend
- [ ] Aviso de ambiente teste

-------------------------

- [ ] Cards
- [ ] Modal
- [ ] Loaders
- [x] Footer
- [x] Header
- [ ] Progress steps

**Comment by suzanabueno** [comment]
Ficou irrelevante.
