### ISSUE TITLE
modal reordenar colunas

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#403]
### Contexto

A tabela proposta pela nossa UI não possui a flexibilidade de exibir colunas ocultas a partir do scroll lateral. Portanto é necessário que o cliente possa customizar as colunas na qual ele deseja exibir para que a tabela atenda a necessidade de visualização dele.

#### ---> [Exemplo no Zeplin](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5aa2d62b3dda8c354c1d8466)

![image](https://user-images.githubusercontent.com/24230714/37355311-2ccee5c4-26c2-11e8-95fc-8307581ea024.png)

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ] Deve com overlay sobre a página atual
- [ ] Deve fechar onClick no `X`
- [ ] Deve fechar onClick no `Cancelar`
- [ ] Deve reestabelecer padrão inicial da tabela ao clicar em `Padrão Inicial`
- [ ] Deve aplicar a formatação escolhida ao clicar em `Aplicar`
- [ ] Deve ordenar os itens ao clicar nas setas na esquerda
- [ ] Deve ordenar os itens com drag and drop
- [ ] Deve selecionar o item da coluna com o dropdown
- [ ] **Deve salvar o padrão para os próximos acessos**

**Comment by suzanabueno** [comment]
Provavelmente não vamos mais fazer. Caso mudemos de ideia, podemos reabrir.
