### ISSUE TITLE
layouts telas de assinaturas

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#406]
### Contexto

As telas de assinaturas são exatamente iguais à tela de transações na dashboard atual. Pensando no produto no qual elas pertencem, que é recorrência, podemos oferecer uma arquitetura que contemple essas informações e agreguem valor ao usuário desse produto.

#### Assinaturas
![image](https://user-images.githubusercontent.com/24230714/37356036-d7a38526-26c3-11e8-9f8a-ee5a291e1e5c.png)
#### Detalhes de assinaturas
![image](https://user-images.githubusercontent.com/24230714/37356066-e8bf0f1a-26c3-11e8-9651-dc113cc6c821.png)

### Requisitos e Critérios de Aceite

Seguindo a nova arquitetura proposta precisamos do equivalente a:
- [x] Layout tela de Assinaturas
- [x] Layout da tela de detalhe de Assinaturas

**Comment by alexandralugli** [comment]
Link para o Zeplin:
Lista - https://zpl.io/bAvmNAo
Detalhes - https://zpl.io/brrmyr3
