### ISSUE TITLE
layout tela de planos

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#409]
### Contexto

As telas de planos são exatamente iguais à tela de transações na dashboard atual. Pensando no produto no qual elas pertencem, que é recorrência, podemos oferecer uma arquitetura que contemple essas informações e agreguem valor ao usuário desse produto.

#### Planos
![image](https://user-images.githubusercontent.com/24230714/37355960-b18bd0dc-26c3-11e8-8eaf-3b429721939d.png)
#### Detalhes do plano
![image](https://user-images.githubusercontent.com/24230714/37355974-bc47cca6-26c3-11e8-8188-38eabe9e4524.png)

### Requisitos e Critérios de Aceite

- [x] Layout da tela de Planos
- [x] Layout da tela de detalhes de plano

**Comment by alexandralugli** [comment]
![planos - lista](https://user-images.githubusercontent.com/8549244/38208370-391c0350-3687-11e8-858c-16f916619531.jpg)

![planos - detalhe](https://user-images.githubusercontent.com/8549244/38208369-38f62892-3687-11e8-95fe-88a5b7d8e104.jpg)


Link para o Zeplin:

Planos - lista: https://zpl.io/aXWdZ8l
Planos - detalhe: https://zpl.io/VxBDAWx
