### ISSUE TITLE
implementar google analytics de transações

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#413]
### Contexto

O Google Analytics fornece dados para mensurar a utilização de features e funis de conversão de atividades. Precisamos mapear as ações principais que queremos utilizar analytics e adicionar os eventos do GA nas páginas de transações e detalhes de transações.

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ] Analytics na tela de Lista de transações
- [ ] Analytics na tela de Detalhes de transações
- [ ] Analytics de adicionar transação, abertura e funil de conversão
- [ ] Analytics de estornar transação, abertura e funil de conversão
- [ ] Analytics de reprocessar transação, abertura e funil de conversão
- [ ] Analytics de reordenar colunas, abertura e funil de conversão
- [ ] Analytics de filtro de transações, abertura e funil de conversão
- [ ] Analytics de exportar comprovante de transação, abertura e funil de conversão
- [ ] Analytics de paginação
- [ ] Analytics de expansível da tabela, checkbox da tabela

**Comment by suzanabueno** [comment]
Isso será refeito. Abriremos outras issues.
