### ISSUE TITLE
redesign de marca

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#422]
### Contexto

O grupo Stone.co passa por uma reformulação de marca e a marca e paleta de cores proposta pelo grupo está desconectada do contexto do Pagar.me. Portanto a equipe de marca do grupo deixou a cargo do Green Phoenix a reformulação do logotipo e da paleta de cores.

### Requisitos e Critérios de Aceite

- [x] Novo logotipo
- [ ] Paleta de cores

**Comment by alexandralugli** [comment]
Link para o Zeplin: https://zpl.io/bzYzEn4
