### ISSUE TITLE
Review visual dá página de detalhes de transacão

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#435]
### Contexto

- [x] O botão `copiar` no card de Boleto fica cortado em resoluções pequenas

- [x] A Data não está formatada no card de Boleto

- [x] o botão `ver boleto` ainda não abre a window com a url do boleto

- [x] Após o label vencimento tem um `:` a mais no componente `PaymentBoleto`

![screenshot from 2018-03-27 14-11-06](https://user-images.githubusercontent.com/479495/37983718-c1003f64-31e3-11e8-86b9-57cb77c1d1fb.png)

- [x] no Histórico da transação os status estão em ingles ex: `success`

- [x] o componente `Event` possui `cursor: pointer` mesmo quando não é expansível (Apenas 1 item) dando ideia de ação de clique que na verdade não existe

![screenshot from 2018-03-27 14-30-20](https://user-images.githubusercontent.com/479495/37983999-979db010-31e4-11e8-99b7-49e15ca7d476.png)

- [x] ao clicar em `VISUALIZAR PARCELAS` ocorre um erro (id da transação 2998884 p/ teste, aparentemente apenas quando é boleto)
![peek 2018-03-27 14-47](https://user-images.githubusercontent.com/479495/37984900-01721cb8-31e7-11e8-8026-c7dbd1a942d0.gif)

- [x] Valor liquido parece estar hardcoded sempre vindo como 100.000,00
![screenshot from 2018-03-27 15-11-34](https://user-images.githubusercontent.com/479495/37986215-6b885f10-31ea-11e8-9fdb-a6bb052136ed.png)

- [x] a lista de eventos está um pouco confusa de entender dependendo dos eventos ocorridos, como por exemplo no print abaixo possuem 2 CHARGEBACK e 2 PAGA pouco intuitivos
![screenshot from 2018-03-27 15-43-45](https://user-images.githubusercontent.com/479495/37987911-0a5df1be-31ef-11e8-81c5-4be383726656.png)

- [x] no card de valor liquido a data de recebido em parece estar hardcoded
![screenshot from 2018-03-27 15-50-04](https://user-images.githubusercontent.com/479495/37988176-c92622b0-31ef-11e8-9740-155c9855e7b8.png)

- [ ] na dashboard pilot não é apresentado o valor autorizado da transação. Na dashboard atual esse valor é exibido, algumas vezes até de forma inconsistente quando o valor capturado for diferente do valor autorizado. Acredito que isso possa ser uma inconsistência se o cliente comparar as informações das duas dashboards lado a lado

- [x] o card detalhes da transação não está sendo preenchido
![screenshot from 2018-03-27 16-10-21](https://user-images.githubusercontent.com/479495/37989328-a5d7ab3c-31f2-11e8-83d9-1bd91f47e61c.png)

- [x] o card de metadata está sendo renderizado quando o metadata  está vazio (transaction para teste 2994712)
![screenshot from 2018-03-27 16-12-19](https://user-images.githubusercontent.com/479495/37989415-ea7002c6-31f2-11e8-98fe-5fb20c518522.png)

- [x] na pagina de detalhes de transação o menu `transactions` não fica marcado como selecionado 
![screenshot from 2018-03-27 16-18-43](https://user-images.githubusercontent.com/479495/37989849-103d00ac-31f4-11e8-8d3f-4e4101e37dbb.png)

- [x] na tabela de recebedores a coluna `status da tabela` está em ingles e a data `de:` esta aparecendo quando a parcela não foi antecipada
![screenshot from 2018-03-27 16-28-47](https://user-images.githubusercontent.com/479495/37990266-47d6c286-31f5-11e8-9d45-03cbe783408a.png)

- [x] no histórico da transação, quando tem apenas um ítem o indicador fica incorreto:
![screen shot 2018-03-29 at 10 29 03](https://user-images.githubusercontent.com/1611639/38091549-3c970f28-333c-11e8-90e1-27262279c449.png)

- [x] no card de recebedores quando tem nenhum recebedor está renderizando com tamanho errado, quando não deveria nem estar renderizando:
![screen shot 2018-03-29 at 10 35 30](https://user-images.githubusercontent.com/1611639/38091904-32cf4aae-333d-11e8-8863-743e57a7eea3.png)

**Comment by uselessdev** [comment]
Abrindo uma issue específica pro item de valor autorizado #447
