### ISSUE TITLE
criar a navegação entre a tela de listagem de transações e a tela de detalhes da transação

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#437]
### Contexto
Atualmente é necessário digitar na url o id de uma transação para ter acesso a rota de detalhes da transação. A ideia é criar os devidos links na tabela de listagem de transação que leve a tela de detalhe de transação para a transação correspondente a linha.

### Descrição técnica

- [x] na tabela de listagem de transações criar o link para a pagina de detalhes de transação para cada ilinha

**Comment by Deivis** [comment]
done
