### ISSUE TITLE
query string de filtros na url da tela de listagem de transações

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#438]
### Contexto
hoje ao ser aplicado um filtro nos dados da tela de listagem de transações a url não é alterada, isso impossibilita o compartilhamento destes filtros através do link da página. O ideal seria fazer com os filtros da pagina sejam aplicados como query string refletindo o filtro salvo no redux

### Descrição técnica

- [x] criar o fluxo de atualização da query string com base nos filtros aplicados
- [x] manter a query como fonte de verdade e o redux como cache para fallback

**Comment by Deivis** [comment]
done in 59bed83
