### ISSUE TITLE
Indicador de passos restantes

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#44]
## Indicador de passos restantes

Elemento integrante da issue #24  e relacionado a issue #25 

**Resumo do problema**

>O usuário irá passar por um processo no qual deve ser guiado para o preenchimento correto de todos os campos e deve ser guiado.

**Exemplo:**

![best_screen_shot_2015-01-08_at_09 15 53](https://user-images.githubusercontent.com/10881626/28288815-dcc805d6-6b16-11e7-9f9f-17f816f682ba.png)

**Uso adequado:**

- Use quando o objetivo do usuário pode ser quebrado em diversos passos para ficar simples a execução de uma tarefa naturalmente complexa;
- Use quando os passos de um processo são muito longos e passos menores são melhores exibidos em telas separadas;
- Não use quando houver somente um ou dois passos;
- Não use quando o processo de preenchimento de dados é fácilmente executado.

**Modelo Pilot**
(será adicionado)

**Comment by vitorvmiguel** [comment]
Issue encerrada para acompanhamento na https://github.com/pagarme/produtos/issues/49
