### ISSUE TITLE
aplicar intl na sidebar

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#440]
### Contexto
Atualmente os labels da sidebar estão fixos. O ideal seria aplicar intl na sidebar assim como já é feito na tela de detalhes da transação

### Descrição técnica

- [x] Aplicar Intl na sidebar

- [x] criar o arquivo de intl para a sidebar em pt-br

- [x] criar o arquivo de intl para a sidebar em en-us

**Comment by Deivis** [comment]
done in f7a904c
