### ISSUE TITLE
Corrigir atualização da tela de detalhes da transação

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#442]
### Contexto

Ao navegar via url de uma transação para outra a página não é atualizada.
Este problema parece estar relacionado ao react router e ao estado do redux.

### Requisitos e Critérios de Aceite

- [x] Navegar entre detalhes de transações usando apenas a url

**Comment by derekstavis** [comment]
No caso do detalhes de transação devemos usar o Redux apenas como logging. A fonte de verdade deve ser a URL para não termos problema de duplicidade de estado.

**Comment by Deivis** [comment]
Concordo, a solução até foi simples, apenas usei uma validação  no `componentWillReceiveProps` que dispara uma ataulização de dados no redux quando a url é modificada.
