### ISSUE TITLE
Valor autorizado da transação

### ISSUE THREAD

**Issue by uselessdev** [pagarme/pilot#447]
### Contexto

Na dashboard pilot não é apresentado o valor autorizado da transação. Na dashboard atual esse valor é exibido, algumas vezes até de forma inconsistente quando o valor capturado for diferente do valor autorizado. 

Acredito que isso possa ser uma inconsistência se o cliente comparar as informações das duas dashboards lado a lado.

**Comment by Deivis** [comment]
done
