### ISSUE TITLE
Tabela de lista de movimentações do extrato

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#467]
### Exemplo

![screenshot from 2018-04-04 18-38-37](https://user-images.githubusercontent.com/1611639/38336285-a72993a6-3837-11e8-9f6a-ccba52fa715b.png)

### Descrição técnica

A tabela dever ser criada com base no objeto operations de extrato:
```json

  "operations": {
      "total": 2321313132,
      "count": 98324,
      "offset": 0,
      "rows": [
        {
          "id": 12321321,
          "type": "anticipation",
          "description": "dsfsdfdsfsdfsdf",
          "payment_date": {
            "actual": "2017-01-02",
            "original": "2017-01-01"
          },
          "outcoming": [
            { "type": "payable", "amount": 123131231 },
            { "type": "mdr", "amount": 123131231 }
          ],
          "outgoing": [
            { "type": "refund", "amount": 2312312 },
            { "type": "mdr", "amount": 2312312 },
          ],
          "net": 328409
        }
      ]
    }
```

Usar a tabela já existente e escrever os renderes para renderizar as colunas com os devidos formatos:

- [x] Data com antecipação
- [x] Descrição composta com titulo e descrição
- [x] Coluna de valor líquido com cores vermelho e verde

**Comment by rsmelo** [comment]
resolvido no PR #476
