### ISSUE TITLE
layout: tela de login para ambiente de teste

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#475]

**Comment by derekstavis** [comment]
### Contexto

Decidimos que não suportaremos ambientes de LIVE e TEST juntos na mesma aplicação, dado que isso é confuso pois:

* Não deveria ser possível trocar de ambiente no detalhe de uma transação
* Trocas de configuração em test aplicam em live também, quando user é admin
* Não nos permite avançar em relação a separação dos ambientes

Tendo isso em vista, precisamos de uma diferenciação entre o design do login no ambiente de testes e no ambiente de produção, para evitar a confusão do usuário. Na área logada a gente já tem a label de test, então talvez faça sentido também adicionar um indicativo de live em algum local, mas isso é escopo para outra issue 👍

**Comment by flaviolee** [comment]
Done.

https://zpl.io/am6G7zD

**Comment by flaviolee** [comment]
Done.

Link no zeplin:
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5a67744cc17298671006468b

Fecha a issue e passa a régua.
