### ISSUE TITLE
corrigir histórico da transação para não exibir internal gateway operations

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#513]
### Contexto

O histórico da transação está exibindo `paga` diversas vezes. O problema é, nosso lojista quando vê isso, pra ele o que vem na cabeça é "cobrei meu cliente duplicado!", sei que nosso código nos fornece a informação desse jeito, e que temos que fazer um contorno para exibir isso, mas é extremamente importante que não seja exibido duplicado. **A Dashboard atual filtra as Gateway Operations que tem a flag internal para não ser exibida na timeline de eventos `pagarme operations should not be internal`.**

#### Pilot
![image](https://user-images.githubusercontent.com/24230714/38834759-c4331e88-419f-11e8-89f5-cf560df4c1ef.png)

#### Dash Atual
![image](https://user-images.githubusercontent.com/24230714/38834851-0439ea3e-41a0-11e8-89e5-079f19a1845d.png)

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ] Exibir um histórico da transação filtrado para não exibir status duplicados que não refletem a operação do cliente (separar nosso tratamento interno, do que é relevante para o lojista)

**Comment by vitorvmiguel** [comment]
@LeoNero esse é um problema que a dash atual já resolve. Vale a pena entender a lógica aplicada nela e replicar na nova ;) 

Além disso, tem a ordenação dos eventos `paga` sempre será após `autorizada`, tem que checar a ordenação

A transação dos prints é a de ID 38423184 no login do comercial

**Comment by LeoNero** [comment]
Essa issue ja esta done, nao? @derekstavis

**Comment by suzanabueno** [comment]
@Deivis isso já foi feito, não?

**Comment by Deivis** [comment]
Solved on #599
