### ISSUE TITLE
Exibir ação de reprocessar transação na tela de detalhes

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#532]
### Exemplo

![screenshot from 2018-04-11 15-15-46](https://user-images.githubusercontent.com/479495/38635285-42eb0078-3d9b-11e8-9813-cc6dbcdbf458.png)

### Descrição técnica

- [x] Exibir o botão de `reprocessar` quando a transação tiver `payment_method: 'credit_card'` e estiver com status `refused` ou `chargedback`
- [x] Exibir modal de reprocessar transação quando disparada ação de `onReprocess`

**Comment by LeoNero** [comment]
@derekstavis acho que a logica de quando a transacao pode ser reprocessada deve ser mudada!
https://github.com/pagarme/pagarme-dashboard/blob/30e40150399caa5ecf74764c5d33778cbe50f2ee/app/screens/helpers/transaction.js#L35

https://github.com/pagarme/pagarme-dashboard/blob/3630c11cc93905ba6816e94497cc657fe4566dba/app/screens/transactions/details.js#L331

**Comment by LeoNero** [comment]
Vou add uma funcao chamada "canReprocess" no cockpit na parte de reprocess, que retorna true ou false :)

**Comment by mccraveiro** [comment]
Qual o caso de uso de reprocessamento quando a transação virou chargeback?

**Comment by mccraveiro** [comment]
Ninguém me respondeu 😞

**Comment by Deivis** [comment]
Desculpe @mccraveiro, realmente não prestamos atenção no exemplo,  não tenho certeza se este botão de reprocessar aparece em caso de chargeback, mas posso vir a confirmar isso na segunda :)
