### ISSUE TITLE
Requisição de reprocessamento de transação

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#533]
### Contexto

Necessitamos reprocessar transações. Tendo isso em vista, precisamos adicionar a lógica no `cockpit` para reprocessar uma transação, que consiste em remover os campos desnecessários de uma transação e criá-la novamente.

### Descrição técnica

O cliente do cockpit deve receber uma transação do Pagar.me, como retornado pela rota `/transactions`.

```
cockpit.transactions.reprocess(transaction)
```

O retorno deverá ser a nova transação criada.

### Requisitos e Critérios de Aceite

- [x] Deve receber uma transação completa
- [x] Deve retornar uma nova transação

**Comment by LeoNero** [comment]
Referencia: https://github.com/pagarme/pagarme-dashboard/blob/3630c11cc93905ba6816e94497cc657fe4566dba/app/screens/transactions/details.js#L589

**Comment by rsmelo** [comment]
@LeoNero consegues marcar aqui em qual PR entrou isso?
