### ISSUE TITLE
Componente de detalhes de reprocessamento de transação

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#548]
### Exemplo

![screenshot from 2018-04-25 15-38-06](https://user-images.githubusercontent.com/1611639/39265853-bd47db6c-489e-11e8-9265-b4c195a7532f.png)

### Descrição técnica

```jsx
<ReprocessData
  id="324324"
  cardFirstDigits="123456"
  cardLastDigits="4567"
  amount={23234}
  installments={12}
  holderName="José da Silva"
/>
```

**Comment by uselessdev** [comment]
@derekstavis eu acredito que as props desse componente deveriam ser `labels` e `content` pra seguir o padrão que estamos nos componentes, e as props como estão sendo propostas seriam pro Container, assim o componente ficaria da seguinte forma:

``` jsx
<ReprocessDetails
  contents={{
    amount: '20.000,00',
    cardNumber: '1444 **** **** 4444',
    holderName: 'José da Silva',
    installments: '12x',
  }}
  labels={{
    amount: 'Valor R$',
    cardNumber: 'Número do cartão',
    holderName: 'Portador do cartão',
    installments: 'Qtd de parcelas',
  }}
/>
```
