### ISSUE TITLE
Definir a padronização dos botões de toolbar

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#581]
Hoje temos dois tamanhos de botoes aplicados numa toolbar de tabela. 26 px e 32 px de altura.

Uma alteração nesse padrão pode refletir em todas as telas e em todos os botões que usamos na nova dashboard.

Precisamos definir a melhor solução e fazer as devidas alterações onde for necessário.

**Comment by alexandralugli** [comment]
**- SegmentedSwitch**
. Tamanho tiny (height: 26px; border-radius: 3px; border: solid 1px #c2c5c7; border: solid 1px var(--color-grey-50; se on: background-color: #17c9b2; se off: background-color: #ffffff)
. Adição de ícone: cores dos ícones - on #ffffff / off #858C8F
. Tooltip: tabela / gráfico

**- Dropdown**
. Tamanho tiny (height: 26px; border-radius: 3px; border: solid 1px #c2c5c7; border: solid 1px var(--color-grey-50)
. font-family: OpenSans; font-size: 12px;

**- Botão Tiny**
. Tamanho tiny (height: 26px; border-radius: 3px; border: solid 1px #c2c5c7; border: solid 1px var(--color-grey-50);
