### ISSUE TITLE
analise manual do antifraude na tela de transações

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#586]
- Adicionar um destaque informando que existem transações pendentes de análise manual - Como regra, as transações com **RISCO ALTO** vão ficar disponíveis para análise num período de 48 horas.

**Comment by flaviolee** [comment]
Done.
Faltando apenas o texto final do alerta.
Vou passar todas as necessidades de texto para a equipe de comunicação depois de olhar todas as necessidades nas demais telas.

Link no zeplin:
https://zpl.io/VK0ZzR7
