### ISSUE TITLE
análise manual do antifraude na tela de detalhes da transação

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#587]
- Adicionar destaque com o motivo da recusa e botões "aprovar" e "reprovar".
Ao clicar em "aprovar", abrir um modal com informações que o cliente deve se atentar na tela antes de confirmar a aprovação.
- Adicionar status "pending review".

**Comment by flaviolee** [comment]
Tela no zeplin.
Faltando apenas o modal agora.

https://zpl.io/VK0ZZv6

**Comment by flaviolee** [comment]
Modais inclusos. 
Link da seçao no zeplin com todas as telas: https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5ab16eb8f7719b4c81ab604c

Observação: Ao aprovar uma transação manualmente, o fluxo dela volta ao de sempre, logo, o próximo passo no histórico seria PAGA.

Como o usuário acaba de realizar uma ação de aprovar a transação, pode ser que ele sinta falta de um feedback direto no histórico.

Dado isso, sugeri incluir mais um passo (vide layout) onde ficaria claro e devidamente documentado que o cliente resolveu aprovar a transação.

Falta agora tirarem os restantes das dúvidas tecnicas de desenvolvimento se isso é possível de ser feito.

**Comment by alexandralugli** [comment]
Podemos usar a mesma lógica das funcionalidades "estornar" e "reprocessar". Na conclusão do modal, existe a possibilidade de "Visualizar transação", que envia o usuário para a transação paga.
