### ISSUE TITLE
Tela/modal de mudar de recebedor

### ISSUE THREAD

**Issue by LeoNero** [pagarme/pilot#612]
TBD

**Comment by rsmelo** [comment]
quando for fazer essa da uma olhada no branch `add/recipient-selection` eu comecei algo que foi abandonado por que não precisou usar em extrato

**Comment by suzanabueno** [comment]
@rsmelo essa tarefa ainda é relevante ou podemos fechar?

**Comment by suzanabueno** [comment]
Fechando por inatividade e falta de contexto.
