### ISSUE TITLE
Definir cores e siglas dos status dos recebedores

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#616]
Abaixo, a lista com os status:

- [ ] Ativo
- [ ] Recusado
- [ ] Temporariamente suspenso
- [ ] Em credenciamento
- [ ] Em afiliação
- [ ] Permanentemente desativado
- [ ] Temporariamente bloqueado

**Comment by flaviolee** [comment]
Done!

https://zpl.io/aRowr0N
