### ISSUE TITLE
adicionar recebedor - conta bancária

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#622]
- [x] Ajustar a solução de adicionar conta bancária (mesma solução da página "Detalhe do recebedor (Configurações)".
- [x] Rever a posição dos botões "voltar/cancelar"

**Comment by flaviolee** [comment]
All done.

https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5aeb6471acf1cef626d39293
