### ISSUE TITLE
estudo de grafismos

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#624]
O objetivo é separar um grupo de grafismos que se encaixem na dash com um todo, inclusive para empty states. Exemplo:

![image](https://user-images.githubusercontent.com/8549244/40068010-f0d7ee0a-583d-11e8-8582-2bdf0ca60e7b.png)

**Comment by flaviolee** [comment]
Estamos usando esse pacote de ilustrações como referencia principal:

https://www.shutterstock.com/g/BadBrother

Isso nos ajudou a pensar numa série de detalhes de como seguir com nossas ilustracoes, como traço, cores, aplicação de fundo e como lidar com personagens para reforçar a mensagem desejada.
