### ISSUE TITLE
mudar comportamento do date selector

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#626]
![image](https://user-images.githubusercontent.com/8549244/40073288-cec2d80c-584c-11e8-8078-bd4d14e0fb96.png) 
![image](https://user-images.githubusercontent.com/8549244/40073305-dc3d6b14-584c-11e8-94be-56f6cc18f6ce.png)

No comportamento atual, o usuário deve necessariamente escolher um período na lateral esquerda e aí definir o dia no calendário. Porém, pelo que temos visto nas gravações de tela, o usuário vai direto no calendário e só depois descobre que tem de selecionar o período.

Vamos alterar o componente para que, assim que o usuário clicar no input de data, apareça primeiro a lateral e assim que ele selecionar uma das opções apareça o calendário ao lado, ficando mais ou menos assim:

![image](https://user-images.githubusercontent.com/8549244/40073605-a80a888a-584d-11e8-96f9-d27b2326a612.png)

E então:
![image](https://user-images.githubusercontent.com/8549244/40073681-ea9029a8-584d-11e8-90f8-6c71db91d2bb.png)

**Comment by flaviolee** [comment]
Layout redesenhado.
Falta só ajustar no código agora.

https://zpl.io/a3xANRl

**Comment by flaviolee** [comment]
Done.

Adicionei uma seta no bg da sidebar para sempre ficar claro a relaçao dela com o campo que a ativa, ja que por aparecer sozinha num primeiro momento, pode ficar voando sobre o conteudo. Assim diminuimos o estranhamento.

O comportamento passa a ser assim agora:
Ao clicar no input de data, abre só a sidebar.
O usuário escolhe seu período. Ao selecionar "qualquer data", nada acontece e o filtro fica neutro.
Ao selecionar as demais opções, o restante do calendário é exibido e o usuário procede escolhendo os dias desejados.

Não havera mais botão de confirmação ao escolher. Ao clicar fora do componente, ele fecha, registrando os dados inputados até então.

Link no zeplin para conferencia:
https://zpl.io/a3xANRl
