### ISSUE TITLE
Adicionar no linter regras recorrentes em reviews

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#641]
### Contexto

Algumas regras do linter não estão sendo validadas, quando deveriam, o que gera comentários nos pull requests que poderiam ser feitos pelo próprio linter, evitando reviews humanos dessas coisas.

### Requisitos e Critérios de Aceite

O linter deverá enforçar as seguintes regras:

- [x] Ordem alfabética das props
- [x] Limite de 80 colunas
- [x] Linha em branco no final do arquivo
- [x] Padrão para retorno em ternários
- [x] Máximo de linhas em branco para 1

**Comment by lucasjs** [comment]
@derekstavis feito:
https://github.com/pagarme/react-style-guide/pull/11

**Comment by uselessdev** [comment]
Esse do ternários eu não sei se temos algum padrão definido pra isso mas acho legal ter alguma coisa definida como quebrar ou não a linha depois de `?` e `:`

**Comment by macabeus** [comment]
Sobre os ternários, o que eu estava aplicando é:

Quando for somente uma linha para as condições do ternário, não quebro as linhas

```js
action === 'approve'
? t('pages.manual_review.model_approve_title')
: t('pages.manual_review.model_refuse_title')
```

Já quando for várias linhas as condições, quebro em várias linhas:

```js
stepStatusResult === 'error'
  ?
    <Button
      fill="outline"
      onClick={onRetry}
    >
      {t('pages.manual_review.result_error_try_again')}
    </Button>
  :
    <Fragment>
      <Button
        fill="outline"
        onClick={onViewTransaction}
      >
        {t('pages.manual_review.result_success_view_transaction')}
      </Button>
    </Fragment>
```

**Comment by suzanabueno** [comment]
@lucasjs sabe me dizer o estado disso aqui?

**Comment by lucasjs** [comment]
@suzanabueno refatorei de acordo com os checks da lista do Derek. Só precisa linkar com os repos e ver o que precisamos arrumar. Quanto aos itens que não completei, na época não achei como fazia.

**Comment by tisoap** [comment]
Atualizei o PR para incluir as regras de ternário e linhas brancas. Também adicionei regras de ordenação de chaves de objeto, que também aparecem recorrentemente em reviews.

**Comment by Deivis** [comment]
Solved on https://github.com/pagarme/react-style-guide/pull/11
