### ISSUE TITLE
Refatorar os textos do componente DetailsHead

### ISSUE THREAD

**Issue by lucasjs** [pagarme/pilot#642]
### Contexto
O componente está sem cores de texto e tamanho de fonte.

### Exemplo
No zeplin:
![image](https://user-images.githubusercontent.com/14945222/40319671-7595c412-5d18-11e8-9480-f2f02c2983f1.png)

No storybook:
![image](https://user-images.githubusercontent.com/14945222/40319433-aaba573a-5d17-11e8-884d-cbfcf6b0d5a8.png)

### Requisitos e Critérios de Aceite

- [x]  Cores de texto
- [x] Tamanho de fonte

**Comment by oieusouamiguel** [comment]
Tô em dúvida em qual a versão correta: a atual ou a que está no Zeplin? @flaviolee @alexandralugli 

Atual: 
![image](https://user-images.githubusercontent.com/20358128/43929473-85624280-9c0b-11e8-8b9e-5e56b2911dc2.png)

Zeplin:
![image](https://user-images.githubusercontent.com/20358128/43929483-8e6c8fe8-9c0b-11e8-8a32-da358e5bcfc9.png)

Link do Zeplin: https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5ade56fd908f3c5565414781

**Comment by flaviolee** [comment]
A que está no Zeplin. =)

**Comment by oieusouamiguel** [comment]
ok, @flaviolee!

@rsmelo, acho que vamos ter que criar um novo componente com um novo css para organizar a informação da maneira que está no Zeplin, certo?
