### ISSUE TITLE
Pauta da weekly de 28/05/2018

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#644]
### Contexto

Teremos uma weekly meeting de todos os times que estão trabalhando no Pilot. A próxima será no dia 28/05. Essa issue será usada para catalogar todas as pautas de discussão.

Fique livre para editar esse post e adicionar seu ítem.

## Desenvolvimento

- [ ] Expansível da tabela, como vamos permitir conteúdo customizável
- [ ] `CardSectionDoubleLineTitle` e a polêmica das actions
- [ ] Padrões de validações de formulário
- [ ] Linhas com propriedade de ênfase (linhas amarelas)

**Comment by derekstavis** [comment]
###  Expansível da tabela, como vamos permitir conteúdo customizável

Hoje usamos a prop `renderer` para permitir renderizar um conteúdo customizado.

```jsx
<Table
  columns={[
    { renderer: () => <VisaLogo /> },
  ]}
/>
```

Poderíamos usar o mesmo padrão para renderizar um expansível customizado, por inteiro ao invés de por coluna.

```jsx
<Table
  expansibleRenderer={(row) => <VisaLogo />}
/>
```

**Comment by derekstavis** [comment]
####  Linhas com propriedade de ênfase (linhas amarelas)

@pagarme/gladiators decidiu que não é prioritário, então coletarão feedback dos clientes sobre e caso se torne um problema, será priorizado

**Comment by derekstavis** [comment]
#### `CardSectionDoubleLineTitle` e a polêmica das actions

A princípio esse componente não recebe ações. Precisamos de uma interface que permita mostrar estas ações e que sejam flexíveis a ponto de permitir `<Popover />`s.

![screenshot from 2018-05-28 15-53-31](https://user-images.githubusercontent.com/1611639/40626584-ee59e410-628f-11e8-9b74-43f9ec9e963d.png)

A interface sugerida é a seguinte:

```jsx
<CardSection>
  <CardSectionDoubleLineTitle
    title="Lorem ipsum"
    subtitle="Dolor sit amet"
    actions={
      <Fragment>
        <Popover content={renderMenu(props)}>
           <Button icon={<Icon />} />
        </Popover>
      </Fragment>
    }
  />
</CardSection>
```

**Comment by derekstavis** [comment]
#### Padrões de validações de formulário

O @rsmelo levantou a questão de que os formulários estão ficando levemente diferentes em questão de usabilidade (cc @pagarme/ux). Temos que estabelecer um padrão para os seguintes pontos.

##### Em que momento as validações devem ser executadas (`change`, `blur` ou `submit`)
##### Limpar o erro no "onChange" caso o evento de validação seja o `blur`

O @Fausto-Junior levantou que existe uma boa prática de rodar as validações apenas no evento `blur` (ao sair do campo), isso evitaria de deixar o usuário confuso enquanto o valor de um CPF, por exemplo, está inválido.

Para suportar isso é necessário adicionar uma propriedade para configurar o evento de validação do vanilla form. A interface sugerida é a seguinte:

```
<Form
  validationEvent="blur"
/>
```

Ficou definido que iremos utilizar o evento de blur e quando mudar o valor do input irá apagar a mensagem de erro.

##### Estado de `disabled` do botão de submit

O botão deverá ficar desabilitado enquanto os campos obrigatórios não estão preenchidos ou com erros.

**Comment by derekstavis** [comment]
Criaremos as issues nos repositórios, linkaremos aqui e depois fecharemos essa issue.

**Comment by flaviolee** [comment]
@pagarme/gladiators / @derekstavis Fiquei confuso com o comentário sobre a exibição das linhas de transações passíveis de revisão manual. Porque a forma de exibição delas na tabela deixou de ser prioridade?

Qual foi o racional por trás dessa decisão?

Levando em consideração que é uma alteração no layout proposto, não deveríamos ter sido envolvidos na discussão?

**Comment by mccraveiro** [comment]
@flaviolee Concordo 100% que deveríamos ter incluído vocês. Falha minha. 

Não abandonamos essa implementação. Ela será feita! Inclusive está incluída no pacote para o beta.
Porém surgiram outras coisas que nosso time teve que priorizar e fechamos o alfa da revisão manual sem o highlight na tabela de transações.

**Comment by flaviolee** [comment]
Agora ficou mais claro. Tinha entendido que não ia sair, e voces esperariam algum tipo de feedback do cliente pra implementar. Algo como "se alguém reclamar, a gente inclui".

Ufa!
Obrigado.
Eu me perdi um pouco com a weekly dessa semana, mas estarei presente nas próximas pra ajudar nessas discussões quando surgirem.

Valeu!
