### ISSUE TITLE
Falta espaçamento no alerta de análise manual

### ISSUE THREAD

**Issue by macabeus** [pagarme/pilot#661]
### Contexto

No PR #638 foi implementado o alerta na tela de transações avisando que há transações aguardando revisão manual e quantos são.
Apesar de nos printscreen do pull request estar com espaço entre a exclamação e o texto, não é isso o que acontece atualmente.

### Exemplo

![image](https://user-images.githubusercontent.com/9501115/40617946-4fb311f2-6266-11e8-8a03-763222654390.png)

### Requisitos e Critérios de Aceite

- [x] Haver espaçamento entre a exclamação e o restante do texto

**Comment by derekstavis** [comment]
Closed by #662
