### ISSUE TITLE
Pauta da weekly de 04/06/2018

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#663]
## UI/UX

- [x] Notificações e como desenrolar

## Desenvolvimento

**Comment by macabeus** [comment]
@mccraveiro Devemos incluir nessa weekly, ou numa futura após o score pagarme, a feature de sininho de notificação?

https://github.com/pagarme/gladiators/issues/312
![image](https://user-images.githubusercontent.com/9501115/40673246-9f035474-6347-11e8-8031-92a730c98e0f.png)

**Comment by IvanMicai** [comment]
## Componentização no D0

Criar os componentes no D0 tem gerado uma quantidade elevada de retrabalho, pois como eles foram desenvolvidos no momento em que as páginas e o entendimento do projeto não estavam maduros o suficiente, os mesmos não atenderam às necessidades, gerando uma quantidade de retrabalho e impactando os times que dependem deles, seria interessante se todos os times tivessem liberdade de fazer as telas sem utilizar os componentes inflexíveis, assim atendendo melhor o que foi alinhado com UI/UX, utilizando Atomic Design e focando na experiência do usuário, ao invés de focar na questão puramente técnica.

## Desenvolvedores fazem mudanças de UI/UX sem pesquisa prévia

Telas que foram desenhadas pelos time de UI/UX sofrem alterações para se adequar aos componentes já desenvolvidos, ficando evidente que não conseguimos colocar em prática o que foi estudado junto com os clientes que seria melhor para o usuário, devido a componentização que limita nosso desenvolvimento.

## Tamanho/Complexidade dos Componentes

Ter componentes muito genéricos que tentam resolver um problema como um todo, assim gerando um aumento de complexidade desnecessário, poderíamos  quebrar em libs compartilhada entre as Pages.

## Gargalo Green Phoenix

Os times ainda não tem autonomia para seguir o desenvolvimento das telas, seria importante que os times tenham autonomia para fazer o review e decidir o que é melhor para entregar no prazo alinhado e no padrão que foi desenhado pelo time de UI/UX.

## Weekly mais Asincrona 

Utilizar nosso tempo junto para focar em problemas de integração entre os times, evitando discussões técnicas, ou melhor, mover as discussões técnicas para o Github. Eventualmente envolver apenas uma pessoa por time.

**Comment by derekstavis** [comment]
>Telas que foram desenhadas pelos time de UI/UX sofrem alterações para se adequar aos componentes já desenvolvidos, ficando evidente que não conseguimos colocar em prática o que foi estudado junto com os clientes que seria melhor para o usuário, devido a componentização que limita nosso desenvolvimento.

Não concordo que isso ocorra com toda essa intensidade e gere todos esses impactos.

O time de UI/UX criou um design system para usar de forma **consistente** e **facilitar** o desenvolvimento de novas áreas **reutilizando** padrões e evitando criar variações, com o intuito de manter a consistência do projeto. Entretanto, muitas vezes os protótipos de alta fidelidade do Zeplin acabam por diferir dos componentes já desenvolvidos por alguns motivos:

1. **Pela necessidade de se adicionar algo ou modificar algo:**

**Exemplo**: `CardSection` que agora pode ter ações.

A abordagem nessas situações, independente de se o componente está no FormerKit ou no `components` do Pilot, deveria ser modificar o componente para atender as novas necessidades. É responsabilidade do time de UI/UX garantir que essa modificação não afetará negativamente outros usos. 

2. **Pelo processo de atualizar todas as telas ser um moroso:**

**Exemplo**: Existem divergências entre telas de um mesmo fluxo.

A abordagem nessas situações é comunicação. Os desenvolvedores podem levantar junto com o time de UI/UX essas divergências e entender qual estratégia deve ser tomada, **sempre** com o **mindset de consistência**.

3. **Pelo desenvolvimento precisar ser quebrado em etapas:**

**Exemplo**: A informação presente em um Card não está na API ainda.

Um ponto importante é que as telas presentes no Sketch representam o estágio final do desenvolvimento de uma área, entretanto, pode ser necessário quebrar o desenvolvimento em etapas.. A ideia é que quando isso ocorra na planning técnica, seja conversado com o time de UI/UX para que o desenrolar do desenvolvimento seja feito de maneira com que não prejudique a experiência final do usuário.

**Comment by flaviolee** [comment]
Animais os pontos levantados pelo @IvanMicai .
Vou falar um pouco sobre as questões de design que me cabem comentar.

Realmente a discrepância entre código e layout é algo que incomoda, mas acredito que ainda estejamos no meio do caminho, mirando num ponto em que os dois serão o mais próximo de 100% idênticos possível.

É aceitável uma certa divergência numa fase inicial, mas é sempre preciso lembrar que quando chegar no lançamento, essas diferenças vão precisar ser reduzidas ao mínimo possível.

Uma questão importante de ressaltar é a nossa falha em atualizar o desenho dos componentes, na medida em que vão surgindo necessidades novas nos cenários de cada tela.

Usamos os layouts desenhados inicialmente como ponto de partida, nos deparamos com situações diferentes onde mudanças precisavam ser feitas e não conseguimos dar vazão nas devidas atualizações em todos os canais possíveis de design. Isso realmente contribui para que haja essa discrepância também.

Está no nosso radar um review e uma atualização de tudo para fazer nossa parte e ajudar a garantir a padronização.

Seu raciocínio foi extremamente construtivo e ao meu ver, esse mindset é muito importante pro projeto ser concluído com sucesso e entregarmos um produto de qualidade pros nossos clientes.
