### ISSUE TITLE
Discutir alterações no layout do fluxo de antecipação.

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#666]
Na ultima planning tecnica os devs apontaram uma serie de situações a serem discutidas no layout dessa tela.

Resta agora ver se fazem sentido ou não e efetivamente alterar o que foi interessante.

Link no zeplin com anotações e comentários das sugestoes:
https://zpl.io/2vlOBoY

**Comment by suzanabueno** [comment]
@flaviolee isso aqui já foi feito, não?

**Comment by flaviolee** [comment]
Sim! Fechandoa issue right now.
