### ISSUE TITLE
Article list

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#67]
## Article list

Elemento integrante da issue #24  e relacionado a issue #48 

**Resumo do problema**

> O usuário precisa de acompanhamento em encontrar conteúdo editorial interessante, com uma hierarquia de navegação que permita que ele sozinho consiga encontrar o conteúdo necessário.

**Exemplo:**

![best_539](https://user-images.githubusercontent.com/10881626/28339270-f39e1360-6be1-11e7-97dd-cd03b48d19a9.jpg)

**Uso adequado:**

- Use para permitir que os usuários encontrem informações que são interessantes para ele;
- Use quando o conteúdo do sistema baseado em uma organização temporal (atualizações) possa ser localizado sem muita dificuldade;
- Não use em formato de storytelling.

**Modelo Pilot**
(será adicionado)

**Comment by vitorvmiguel** [comment]
Issue encerrada para acompanhamento na https://github.com/pagarme/produtos/issues/49
