### ISSUE TITLE
Separar telas no Zeplin em Ideal e Factível

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#671]
Hoje desenhamos por padrão as telas no cenário ideal para a melhor experiência dos nossos clientes, porém, por limitações da API, não conseguimos executar uma série de comportamentos previstos.

Para melhor a comunicação e garantir o alinhamento dos times, vamos separar as telas do Zeplin, deixando claro o que é possível ser feito agora, e o que é o cenario ideal, onde precisamos chegar o quanto antes.

**Comment by lucasjs** [comment]
Gosto muito!

**Comment by oieusouamiguel** [comment]
Isso já foi feito, certo? Pode fechar a issue?

**Comment by flaviolee** [comment]
Foi feito mais ou menos. Acho que por enquanto serve.
Vamos fechar e se for o caso abrimos outra depois.
