### ISSUE TITLE
layout: auto credenciamento - dados iniciais

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#672]
**Etapa 1**
Pediremos os mesmos dados exigidos na dash atual:

- Texto de introdução;
- Nome;
- Sobrenome;
- Empresa;
- E-mail;
- Senha;
- Confirmar senha;
- Indicador de steps (bolinhas).

Em senha e confirmação de senha, temos de deixar mais claro que são dados para login.

**Comment by flaviolee** [comment]
Done!

Link no zeplin:
https://zpl.io/amn8jB3

Lembrando que falta colocar o texto final. Não temos ainda.
