### ISSUE TITLE
layout: auto credenciamento - validação de cnpj

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#673]
### Etapa 2

No fluxo de qualificação, o usuário deverá possuir CNPJ ativo. Caso contrário, enviaremos uma mensagem de agradecimento. Ex.: "Obrigado! Não conseguimos atender empresas que não possuem CNPJ no momento. Adicionamos seus contatos em uma lista para te avisar quando isso for possível"

Essa tela será composta por:
- Texto de introdução;
- Pergunta: Você possui CNPJ ativo?;
- Caso possua CNPJ, abrir um input para inserção desse dado;
- Indicador de steps (bolinhas).

**Comment by flaviolee** [comment]
Feito. Link da seção no zeplin com todo esse fluxo:
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5b1fe8630df8d0e969ffdb4a
