### ISSUE TITLE
layout: auto credenciamento - negócio e expectativa de faturamento

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#674]
### Etapa 3
Estrutura da página:

- Texto de introdução: já vende pela internet?
- Opções de resposta: SIM | NÃO

- Se **sim**
. Aparece a pergunta: Qual seu volume de vendas ou expectativa de faturamento?
. Opções de resposta
        a) R$0 a R$20.000
        b) R$20.000 a R$30.000
        c) R$30.000 a R$50.000
        d) Acima de R$50.000

- Se **não**
. Aparece a pergunta: Pretende abrir uma loja virtual ou negócio digital?
. Opções de resposta:
        a) Sim, mas ainda é um projeto
        b) Meu negócio já está pronto
        c) Pretendo iniciar as vendas daqui 30 dias
        d)Pretendo iniciar as vendas dentro de 60 dias
. Se resposta = opção b) - Aparece a pergunta: Qual seu volume de vendas ou expectativa de faturamento?
. Opções de resposta:
        a) R$0 a R$20.000
        b) R$20.000 a R$30.000
        c) R$30.000 a R$50.000
        d) Acima de R$50.000

**Comment by flaviolee** [comment]
Also done.

Link com todas essas telas no zeplin aqui: https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5b1fe8630df8d0e969ffdb4a
