### ISSUE TITLE
layout: auto credenciamento - dados da empresa e proprietário

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#675]
### Etapa 04
Estrutura da página

**- Dados do Proprietário**
. Nome + Sobrenome;
. Nome da Mãe;
. Data de Nascimento;
. Celular;
. CPF;
. E-mail.

**- Dados da Empresa**
. Nome Fantasia
. Razão Social
. CEP
. CNPJ
. Telefone comercial
. Site (opcional)
. Modelo de negócio (lista com 5 opções)

Nessa etapa, o usuário pode ter o credenciamento não autorizado, então também enviaremos uma mensagem amigável de negação do credenciamento.

**Comment by flaviolee** [comment]
Essa parte do fluxo sofreu pequenas alterações.
Ao invés de estar junto com os demais passos, ficou num modal dentro da dashboard, ja que agora ao completar o cadastro o cliente cai direto na área de testes.

Teremos um aviso lá dentro pedindo para que ele complete seu credenciamento, e após enviar mais esses dados e ser avaliado pelo risco ele terá ou não a liberaçao para usar a dashboard live.

Link no zeplin com o design desses modais aqui:
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5b1fe8630df8d0e969ffdb4a
