### ISSUE TITLE
layout: auto credenciamento - feedback

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#676]
### Tela de feedback

- Se o usuário não possuir CNPJ:
Enviaremos uma mensagem de agradecimento. Ex.: "Obrigado! Não conseguimos atender empresas que não possuem CNPJ no momento. Adicionamos seus contatos em uma lista para te avisar quando isso for possível".

- Se o usuário for recusado por motivos de risco:
Inserir mensagem de agradecimento ainda a ser desenvolvida.

**Comment by flaviolee** [comment]
Tudo certo no design.
Link da seção no zeplin: https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/dashboard?seid=5b1fe8630df8d0e969ffdb4a

Faltam os textos corretos de cada cenário ainda.
