### ISSUE TITLE
Logotipos

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#68]
Precisamos dos seguintes logotipos em formato vetorial:

* Pagarme
* Twitter
* Facebook
* Linkedin
* PCI

Conforme #1

**Comment by flaviolee** [comment]
@derekstavis Queria propor uma correção semântica.

Logomarca é um termo incorreto que se popularizou no mundo da publicidade brasileira.

O correto seria logotipo quando queremos nos referir aquilo que representa a cara de uma empresa ou produto.

Logomarca seria a junção das palavras logo + marca. "Logos" vem do grego e significa conceito. Marca viria do germânico  "marka" e também significa conceito. Sendo assim, logomarca é redundante. "Conceito do conceito. Significado do significado."

Já logotipo é a junção de logos + typo, ambas do grego, e respectivamente significam conceito e figura. "A figura que representa o conceito".

Aqui tem um link de um infografico que sintetiza bem a coisa toda: https://cdn-images-1.medium.com/max/1600/0*WLEZReq6uTmGr8g_.jpg =)

**Comment by derekstavis** [comment]
Opa @flaviolee vamos arrumar isso :+1:

Se "Logomarca" é o correto, assim será nomeado! Muito obrigado pelo toque! Fique a vontade para interagir por aqui quando encontrar outros erros como esse!!
