### ISSUE TITLE
Ajuste nas telas de recebedores

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#692]
@Fausto-Junior sugeriu algumas mudanças nessa tela.
São elas:

- [x] No passo 1 - Ao habilitar os dados de empresa e sócios:

Na parte de sócios, incluir dropdown com quantidade de sócios a serem inseridos, de 0 a 10. 0 será o estado inicial.
Isso vai automaticamente criar um numero de inputs com Nome+cpf+email de acordo com a quantidade previamente selecionada.

Esse metódo de exibição será necessário por conta do funcionamento do desenho atual, que geraria problemas com os campos obrigatórios antes de submeter o formulário todo, porque esse caso é cheio de condicionais bem específicas, do tipo, campo B é obrigatório se A for preenchido, mas se A ficar em branco, tudo passa a ser opcional. @_@

- [x] Passo 2 - Mudar a seleção de tipo de conta para dropdown ja que tem opção pra cacete.

- [x] Passo de conclusão - prever um cenário de erro com problemas na hora de validar os dados na API, e retornar de forma objetiva em que passo aconteceu o problema com um botão rápido para o cliente voltar e corrigir os erros.

**Comment by Fausto-Junior** [comment]
@IvanMicai @tisoap

**Comment by flaviolee** [comment]
Quase lá.
Preciso só de algumas informações do Fausto agora pra desenhar o cenário de conclusão com o erro desejado.

**Comment by flaviolee** [comment]
Done!
A estrutura do layout será essa. Faltam ilustrações e textos finais, apenas.

https://zpl.io/2pdNGp8
