### ISSUE TITLE
Tela de saque - Mensagem de erro ambígua

### ISSUE THREAD

**Issue by macabeus** [pagarme/pilot#703]
### Contexto
Ao inserir um valor de saque menor do que o custo da transferência (por exemplo, inserir R$ 1.00 enquanto o custo de saque é R$ 3.67), aparece a mensagem de erro "Valor de transferência negativo", porém, o valor que inseri é positivo (1 real) mas a mensagem da a entender que eu inseri um valor negativo.

O correto seria algo como "Valor líquido a ser transferido é negativo".

### Exemplo

![image](https://user-images.githubusercontent.com/9501115/41630724-dd9633d0-7406-11e8-8755-4a733b5f3253.png)

### Requisitos e Critérios de Aceite

- [ ] Mensagem de erro não ambígua

**Comment by rsmelo** [comment]
@ananemes @beatriztoccis qual vocês acham que deveria ser a mensagem nesse caso?
eu pensei em `Valor a ser transferido negativo`, visto que `valor a ser transferido` é a label na tela

**Comment by beatriztoccis** [comment]
O valor da transferência é menor do que o valor do custo. Confira as informações acima e tente novamente :)

@rsmelo 

Mensagem adblock: 
Olá, para você poder visualizar as informações do seu extrato é necessário que as extensões do tipo AdBlock estejam desabilitadas. 

@Deivis

**Comment by rsmelo** [comment]
> O valor da transferência é menor do que o valor do custo. Confira as informações acima e tente novamente

essa mensagem ficou um pouco grande pro tamanho do input, sera que apenas `O valor da transferência é menor do que o valor do custo`seria suficiente? ela deve caber abaixo do input =(
@beatriztoccis

**Comment by beatriztoccis** [comment]
Pode ser, mas o ideal seria darmos uma instrução pro usuário, a mensagem não fiz muita coisa :(

**Comment by rsmelo** [comment]
@beatriztoccis seria legal ver com o pessoal de ux/ui se é possível adicionar essa instrução de outra forma talvez? @alexandralugli

**Comment by alexandralugli** [comment]
Pessoal, idealmente, as instruções devem vir antes do erro ou deixamos a interface clara o bastante para que o usuário entenda a tarefa a ser realizada. No input devemos colocar a mensagem clara e sucinta, com a menor quantidade de caracteres possível.

**Comment by rsmelo** [comment]
conversando com a @alexandralugli   definimos que por enquanto a mensagem será alterada para `Valor solicitado é menor do que o custo`
