### ISSUE TITLE
Alterações no componente DateSelector

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#710]
Épico: pagarme/roadmap#564

Fizemos alguns ajustes com base em gravações do full story e feedbacks sobre o comportamento do componente DateSelector.

**1. Excluímos os botões "Cancelar" e "Confirmar período"**
O filtro possui apenas uma requisição, que é ao clicar em "Filtrar" - independentemente de quantos filtros o usuário selecionar. Retiramos o botão do calendário para não dar a impressão errada de que ao clicar, o filtro de data ocorra.

**2. Divisão de tarefas**
Para que o calendário "habilite" um range de datas é preciso que o usuário necessariamente escolha um período aberto ou pré-setado, porém muitas vezes os usuários tentam selecionar direto no calendário e só depois percebem que essa seleção lateral deve ocorrer.
Mudamos o comportamento para que quando ocorra o clique no input de data, apareça primeiro a lateral esquerda com as opções e depois do clique abra o lado do calendário.
Com a nova solução pretendemos reduzir tempo de preenchimento e diminuição da curva de aprendizado.

**3. Alteração nas datas pré-estabelecidas**
Qualquer data / últimos - 7 dias, 15 dias, 30 dias, 60 dias / personalizado - dia, período

Componente alterado:

![image](https://user-images.githubusercontent.com/8549244/41677834-db937d24-749f-11e8-8090-7a0df7fd8ae1.png)

Zeplin: https://zpl.io/a3xANRl

**Comment by lucasjs** [comment]
O Deivis já criou o componente `Calendar`. Falta só o aside.
https://pagarme.github.io/former-kit/storybook/?selectedKind=Calendar

**Comment by vagnervst** [comment]
Calendário deve fechar sempre que for feito um clique fora da caixa (incluindo em outros elementos).
