### ISSUE TITLE
Corrigir cor do input quando estiver preenchido.

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#726]
## Contexto

Os inputs não estão com a cor certa quando são preenchidos e mudamos o foco, como nesse exemplo:
![login](https://user-images.githubusercontent.com/29930809/41745513-8c827e0e-757d-11e8-9b7f-1b53d80266dc.gif)

## Solução

- [ ] Usar a cor correta no estado preenchido do input.

**Comment by oieusouamiguel** [comment]
Galera, eu e o @lucasjs conversamos sobre e resolvemos fechar a issue. O código tá normal (um input com `hover` e outro com `focus`) e esse comportamento apenas acontece ao utilizar o `tab` invés de clicar no input.
