### ISSUE TITLE
Adicionar ações de saque e antecipação na tela de extrato

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#729]
### Contexto
A página de extrato é o principal acesso as páginas de saque e antecipação. Para isso é necessário adicionar as ações que levam a estas páginas nos cards de totais.
Com este ajuste não será mais necessário o link de acesso a estas páginas diretamente na sidebar, estes acessos devem estar em subitens de menu abaixo do nome da company vide #730 

### Exemplo

![extrato_mvp pilot cenarios atuais zeplin](https://user-images.githubusercontent.com/1773766/41792802-6efca338-7630-11e8-8b61-32a41cb07b12.png)

**Comment by uselessdev** [comment]
resolved in #747
