### ISSUE TITLE
Adicionar saque e antecipação ao submenu de company na sidebar

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#730]
### Contexto
Na sidebar o primeiro item deve ser o nome da company acompanhado de um submenu que disponíbiliza 
os totais disponíveis para saque e antecipação bem como botões para acessar as devidas páginas

### Exemplo
![screenshot from 2018-06-22 15-25-48](https://user-images.githubusercontent.com/1773766/41792854-9f5f4bac-7630-11e8-9b5c-9667c1a7547d.png)

**Comment by lucasjs** [comment]
Peguei
