### ISSUE TITLE
Box de mensagem com largura automática na modal de revisão manual

### ISSUE THREAD

**Issue by flyingluscas** [pagarme/pilot#738]
### Contexto

A box com mensagem de conclusão que é exibido na modal de revisão manual está largura automática.

![screenshot from 2018-06-25 15-49-01](https://user-images.githubusercontent.com/6232791/41869993-1eaae314-7891-11e8-91c2-a2942523f5f0.png)

### Requisitos e Critérios de Aceite

Conversando via slack com o @rsmelo ele disse que esse box deveria ter uma **largura de 100% na modal**.

**Comment by lucasjs** [comment]
O modal não precisa de uma div em volta com flex: 1 mais. Só deixar ele direto em uma col com size 12.

**Comment by flyingluscas** [comment]
cc @macabeus
