### ISSUE TITLE
Filter: Ajustes no espaço do input e nas fontes

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#743]
Listagem de itens que precisam de ajustes, identificados na planning de uxd:

**Imagem do Zeplin:**
![image](https://user-images.githubusercontent.com/8549244/43972118-c2628f84-9ca9-11e8-8d2c-03d11d3e59e8.png)

**Dash alpha:**
![image](https://user-images.githubusercontent.com/8549244/43972137-d02b7432-9ca9-11e8-87de-1ac71edff1cd.png)

- [ ] As fontes estão com cores diferentes no placeholder do input. Mudar para #757575
- [ ] As fontes nos inputs devem ter tamanho 14px
- [ ] Espaçamento: adicionar spacing. A distância entre os itens dos filtros é de 16px. Entre o botão "mais filtros" e "limpar filtros"/"filtrar" é de 48px:

![image](https://user-images.githubusercontent.com/8549244/43972339-6404b222-9caa-11e8-80c3-184ab83a41e4.png)
![image](https://user-images.githubusercontent.com/8549244/43972347-6c85920e-9caa-11e8-9931-fcb2a8b1629b.png)

**Comment by oieusouamiguel** [comment]
Fiz uma issue mais detalhada sobre em #879.

**Comment by lucasjs** [comment]
@alexandralugli A cor do texto no Button com baixa relevância mudará no escopo atual?

**Comment by rsmelo** [comment]
publicado na release https://github.com/pagarme/pilot/releases/tag/v0.8.0
