### ISSUE TITLE
Ajustes nos cards

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#745]
Listagem de itens que precisam de ajustes, identificados na planning de uxd:

- [ ] Payment card: rever alinhamento
- [ ] Customer card: Temos de trocar a cor no estado campo vazio (uxd)
- [ ] Withdraw summary: ajustar espaçamentos e tamanho de fonte
- [x] Balance total display: colocar os botões que já estão no componente - sacar e antecipar
- [ ] Cardsection de configurações: adicionar cor e tamanho nas fontes
- [x] DetailsHead: está sem formatação de fonte (pilot)
- [ ] TotalDisplay: Adicionar cor no Amount / Fonte: ajustar tamanho dos títulos e valores

**Comment by oieusouamiguel** [comment]
Separei essa lista em pequenas issues. Logo, não existe a necessidade de essa issue existir.
