### ISSUE TITLE
Adicionar ação para cancelar antecipação em extrato

### ISSUE THREAD

**Issue by uselessdev** [pagarme/pilot#749]
### Contexto
Em extrato tem uma lista com antecipações pendentes, no zeplin tem um botão para cancelar a antecipação, mas ainda não foi implementado na página de Extrato essa ação

### Exemplo
![screenshot from 2018-06-26 14-47-21](https://user-images.githubusercontent.com/6943919/41929952-0fc0d2c2-7950-11e8-99f6-c13a4cbb4533.png)

### Descrição técnica
Adicionar um botão que dispara a ação de cancelar antecipação.

### Requisitos e Critérios de Aceite
- [x] Ao clicar deve cancelar a antecipação.
- [x] Ao cancelar a antecipação deve remover da lista.

**Comment by suzanabueno** [comment]
@uselessdev Você tava mexendo nisso né? O que falta aqui?

**Comment by uselessdev** [comment]
Resolvido aqui #910
