### ISSUE TITLE
Corrigir a cor do estado ATIVO da sidebar

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#751]
## Contexto

A sidebar não está com a cor correta quando fica no estado ativo.

Ela está assim, com linhas verdes, igual ao estado hover e focus:

![image](https://user-images.githubusercontent.com/29930809/41932332-1ecdec6c-7957-11e8-97f9-a83bf045ebde.png)

quando na verdade deveria estar assim:
![image](https://user-images.githubusercontent.com/29930809/41932280-f58d6f58-7956-11e8-83cf-67293db5e93f.png)

## Critérios de aceite
Corrigir a cor de acordo com o zeplin.

**Comment by uselessdev** [comment]
@flaviolee essas bordas não é do `focused`?

**Comment by flaviolee** [comment]
Nope. Vide print: Active/pressed.

Tem o componente no zeplin também para conferir, se preferir: 
https://zpl.io/bL4Yvy6
