### ISSUE TITLE
Refatorar componentes

### ISSUE THREAD

**Issue by lucasjs** [pagarme/pilot#761]
https://github.com/pagarme/roadmap/issues/564

### Contexto
Após a planning de UXD, listamos vários componentes que precisarão de refatoração no former-kit e pilot.

#### Pilot
- [x] PaymentCard https://github.com/pagarme/pilot/issues/745
- [x] CustomerCard https://github.com/pagarme/pilot/issues/745
- [x] Withdraw summary https://github.com/pagarme/pilot/issues/745
- [x] Balance total display https://github.com/pagarme/pilot/issues/745
- [ ] CardSection de configurações https://github.com/pagarme/pilot/issues/745
- [x] DetailsHead https://github.com/pagarme/pilot/issues/745
- [x] TotalDisplay https://github.com/pagarme/pilot/issues/745
- [x] Sidebar https://github.com/pagarme/pilot/issues/730
- [x] Filtros https://github.com/pagarme/pilot/issues/743

#### Former-kit
- [x] Card https://github.com/pagarme/former-kit/issues/150
- [x] Tabela https://github.com/pagarme/pilot/issues/742
- [x] Sidebar https://github.com/pagarme/pilot/issues/741 https://github.com/pagarme/pilot/issues/751 https://github.com/pagarme/pilot/issues/752
- [x] Header https://github.com/pagarme/pilot/issues/740
- [x] SegmentedSwitch https://github.com/pagarme/pilot/issues/750
- [x] Input https://github.com/pagarme/pilot/issues/726
- [ ] DateSelector https://github.com/pagarme/pilot/issues/710
- [x] Popover https://github.com/pagarme/pilot/issues/762

**Comment by suzanabueno** [comment]
Quebramos ela em um monte de issues menores.
