### ISSUE TITLE
Ajustes no popover

### ISSUE THREAD

**Issue by lucasjs** [pagarme/pilot#762]
### Contexto

Refatorar o componente para ser usado dentro da `Sidebar`.

#### Na pilot
<img width="218" alt="screen shot 2018-06-29 at 14 39 16" src="https://user-images.githubusercontent.com/14945222/42106388-468f9728-7baa-11e8-8d4d-ad5a390c1501.png">

#### No zeplin
<img width="213" alt="screen shot 2018-06-29 at 14 39 36" src="https://user-images.githubusercontent.com/14945222/42106391-4872b5f2-7baa-11e8-8326-93bfd7114018.png">

### Requisitos e Critérios de Aceite

- [x] tirar o `border none *`
- [x] tirar gradiente do `:before` right
- [x] `z-index` deixar acima do header
~- [ ] mudar a posição da seta, ser relativa ao elemento pai do popover~(movida para o former-kit-skin https://github.com/pagarme/former-kit-skin-pagarme/issues/106)
- [x] colocar o border-top em geral, e no `:first-child`, colocar `none`

**Comment by rsmelo** [comment]
@lucasjs acho que essa issue deveria ser aberta no projeto do [former-kit](https://github.com/pagarme/former-kit)
