### ISSUE TITLE
Implementar botão para alternar entre dash antiga e Pilot na sidebar e botão de feedback + ambiente Live/test no header.

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#766]
## Contexto
Precisamos fazer o cliente conseguir alternar entre as versões novas e antigas da dash para o Alpha.

Para isso, previmos um botão no sidebar que precisa ser implementado.

Também precisamos permitir que o cliente envie feedbacks e saiba quando está em modo live ou teste, adicionando o botão de feedback e indicador de modo da dashboard no header.

Link do zeplin com layout: https://zpl.io/aRY94rp

## Critérios de aceite
- [x] Implementar botão de alternar entre dash nova e antiga na sidebar https://github.com/pagarme/pilot/pull/780
- [x] Implementar botão de feedback no header
- [x] Implementar icone indicador de live/test no header.

**Comment by lucasjs** [comment]
https://github.com/pagarme/pilot/pull/780
