### ISSUE TITLE
Botão de "Capturar" não aparece na Pilot

### ISSUE THREAD

**Issue by macabeus** [pagarme/pilot#773]
### Contexto
Ao ser criada uma transação com parâmetro `"capture": false`, a transação entra no status `Autorizado` e então o lojista precisa a capturar manualmente.

Lojistas, como a Barato Coletivo, atualmente fazem isso pela dashboard, clicando no botão `Capturar` presente na tela de detalhes de transação.
Porém, esse botão não está implementado na pilot.

### Exemplo
Tela de detalhes de transação na dashboard antiga, com a transação no status `Autorizado`. Nela, é possível visualizar o botão `Capturar`.
![image](https://user-images.githubusercontent.com/9501115/42391935-643a03da-8127-11e8-83fd-9137c61db8f5.png)

Tela de detalhes de transação na dashboard antiga, com a transação no status `Autorizado`. Nela, não tem o botão `Capturar`.
![image](https://user-images.githubusercontent.com/9501115/42392073-f025689e-8127-11e8-81d9-429628fbd95c.png)

### Adendo
Esse fluxo é agnóstico à feature de revisão manual. Porem, se transação tiver sido criada com `capture false` e cair em revisão manual, o lojista precisaria primeiramente aprová-la para então capturá-la.
**Talvez** faça sentido **adicionar** um botão, chamado "Aprovar e Capturar".

Enviamos uma pergunta para a Barato Coletivo se existem situações em que é preciso aprovar uma transação sem que a capture imediatamente.

![image](https://user-images.githubusercontent.com/9501115/42392387-08103e42-8129-11e8-8a2b-e63678b64e71.png)

### Requisitos e Critérios de Aceite
- [ ]  Visualização do botão `Capturar` quando a transação estiver no status `authorized`
- [ ]  Implementação da lógica do botão `Capturar`

**Comment by suzanabueno** [comment]
Comentário da @alexandralugli 

>Oi gente. Temos 2 cenários pra isso:

>1. O botão “Capturar” não é específico de antifraude. Ele deveria aparecer toda vez em que a transação for autorizada e o capture = false;

>2. Nem sempre o cliente captura a transação no momento em que ela for aprovada, ele pode escolher fazer isso depois.

>Sendo assim, sugiro deixarmos 2 botões.

Fora isso, foi comentado por @jonatasmaxi que isso não se aplica a transações criadas pelo Checkout ou por Link de Pagamento. Então, precisamos puxar a referência de Checkout no contexto ao desenvolver.

**Comment by alexandralugli** [comment]
Pessoal, layout resolvido na issue #774
