### ISSUE TITLE
layout: fluxo de captura de uma transação

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#774]
Essa issue está em consonância com a #773 

### Contexto
Ao ser criada uma transação com parâmetro `"capture": false`, a transação entra no status `Autorizado` e então o lojista precisa a capturar manualmente.

Alguns clientes atualmente fazem isso pela dashboard, clicando no botão `Capturar` presente na tela de detalhes de transação.
Porém, esse botão não está contemplado no Pilot.

### Exemplo
Tela de detalhes de transação na dashboard antiga, com a transação no status `Autorizado`. Nela, é possível visualizar o botão `Capturar`.
![image](https://user-images.githubusercontent.com/9501115/42391935-643a03da-8127-11e8-83fd-9137c61db8f5.png)

Requisitos e critérios de aceite:

- [x] Botão "Capturar" 
- [x] Modal com escolha do valor de captura
- [x] Mensagem de feedback da transação capturada

**Comment by flaviolee** [comment]
Layout prévio no Zeplin.
Vamos discutir a melhor forma de passar feedbacks logo mais, dai atualizo aqui com o resultado final.

https://zpl.io/Vk5qQ7M

**Comment by flaviolee** [comment]
Tudo certo.
Feedbacks definidos mas ainda não atualizados no layout. Isso será feito em breve, mas já da pra seguir com essa demanda aqui.

@flyingluscas e @macabeus
