### ISSUE TITLE
Criar container de edição de documentos

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#793]
### Contexto
Criar componente de edição de documentos da empresa com as opções de visualizar e assinar os documentos.

### Exemplo
![screenshot from 2018-07-12 17-09-32](https://user-images.githubusercontent.com/1773766/42656761-a4cd4050-85f6-11e8-99a4-23206189574c.png)

### Requisitos e Critérios de Aceite
- [ ] Permitir a edição dos documentos via upload de documentos
- [ ] Permitir a assinatura de documentos

**Comment by daniantar** [comment]
Agora que possuímos o Autocredenciamento, não é mais necessário aplicar esse fluxo.
