### ISSUE TITLE
Prototipo de baixa fidelidade: Minha conta

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#8]

**Comment by ericksahara** [comment]
Pessoal, subi uma versão atualizada do wireframe de Minha conta, contemplando a funcionalidade de adicionar múltiplas contas bancárias.  Esta funcionalidade está associada ao fluxo de saque da issue #91

Os arquivos do wireframe se encontram neste repositório:
https://github.com/pagarme/produtos/tree/master/Arquitetura/Minha%20conta
