### ISSUE TITLE
Create a demo app?

### ISSUE THREAD

**Issue by pedrofurtado** [pagarme/pilot#814]
It will be great if the repo have a demo app (hosted in Heroku or others cloud providers), to be able to the users see this code in action, without need to clone and build and repo locally 👍

**Comment by rsmelo** [comment]
hello @pedrofurtado thank you for your suggestion. This repository (`pilot`) is the repo to the new pagar.me dashboard and it will be deployed soon. This project uses some tecnhologies develop by us as open-source. If you want to see a demo i recommend you to acesss https://pagarme.github.io/former-kit/storybook/ where you can see a demo of former-kit components (https://github.com/pagarme/former-kit). Take a look at our repositories we a have a lot of open-source projects, enjoy

**Comment by pedrofurtado** [comment]
@rsmelo Thanks for feedback!
