### ISSUE TITLE
Revisar e padronizar unidade de valor

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#816]
Precisamos padronizar a unidade real de valor. Atualmente, estamos mostrando de 2 formas:

1. LABEL com (R$) na primeira linha e resultado de valor na segunda. Exemplo na imagem:
![image](https://user-images.githubusercontent.com/8549244/42788127-1b721ac4-8934-11e8-825a-2e886ffc8ae1.png)

2. LABEL na primeira linha e (R$) com valor na segunda. Exemplo na imagem:
![image](https://user-images.githubusercontent.com/8549244/42788118-07bd8df6-8934-11e8-99c5-8e234fff9d08.png)

**Requisitos e critérios de aceite**

- [ ] Revisar as seções que possuem unidade de valor e definir uma regra de utilização;

**Comment by flaviolee** [comment]
Boa.
Pelo que eu lembro, haviamos definido há seculos atrás que quando um campo é editável, o R$ ficaria no label, pro usuário sempre digitar apenas os valores numéricos.

Quando fosse um campo somente informativo, o R$ apareceria junto do valor pra facilitar a leitura.

Ainda podemos seguir com esse padrão?

Se pudermos, vai ser só identicar os cantos que estão fugindo dessa regra e alterar.

**Comment by flaviolee** [comment]
Done!
Cenarios alterados de acordo com a regra mencionada acima.
