### ISSUE TITLE
Padronizar uso do R$

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#820]
## Contexto

Desenhamos as telas do Pilot sem um padrão correto para uso do R$. Agora implementamos uma regra que irá nortear seu emprego, e assim garantiremos a coesão na dashboard.

Precisamos então reviar as telas que já estão feitas para se adequarem a regra e ter atenção para as novas que surgirem para que todas se enquadrem no padrão.

A regra é:

quando um campo é editável, o R$ fica no label, pro usuário poder digitar apenas os valores numéricos.

Quando for um campo somente informativo/leitura, o R$ aparece junto do valor pra facilitar a visualização.

## Critérios de aceite
• Padronizar todo uso do R$ na dashboard.

Abaixo vou listar alguns lugares onde isso precisará ser revisado:

- [x] Extrato - totais que aparecem ao lado da data filtrada acima da tabela
- [x] Detalhes da transação - totais que aparecem no topo da pagina ao lado das infos de cartao/boleto
- [x] Recebedores - mesmo local de Extrato
- [x] Saque - card sections com valores do saque
- [x] Antecipação - card sections com valores da antecipação

ACHO que é só, mas mesmo assim, fiquem atentos para essa regra e qualquer coisa aplicada fora dela, por favor, padronizem!

Valeuzao!

**Comment by flaviolee** [comment]
@Fausto-Junior PSC. =p

**Comment by oieusouamiguel** [comment]
@flaviolee, você poderia postar um print da parte de recebedores? Não consegui identificar onde deve ser feita a alteração

**Comment by rsmelo** [comment]
oi @flaviolee ,

o Currency Input está sendo alterado no pr #866 pela @oieusouamiguel , no caso da modal de estorno, como deveria ficar? Deve adicionar o (R$) ao lado do label `valor do estorno`?

![screenshot from 2018-08-07 13-23-58](https://user-images.githubusercontent.com/479495/43789178-b7121a16-9a45-11e8-858d-5b078aca6b4e.png)
![screenshot from 2018-08-07 13-25-12](https://user-images.githubusercontent.com/479495/43789180-b7336810-9a45-11e8-9609-4580733e2afd.png)

**Comment by flaviolee** [comment]
Isso @rsmelo ! Sempre que precisar inputar valor monetário, o R$ fica no label!

**Comment by oieusouamiguel** [comment]
ok! consertei! valeu @flaviolee
