### ISSUE TITLE
Micro interação: loader global

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#828]
**Contexto**
As páginas necessitam de loaders para apresentarem feedback visual enquanto os componentes são carregados.

**Exemplo**
https://codepen.io/Michiel/pen/dfejE

**Comment by flaviolee** [comment]
Essa issue também foi abordada na #300 .

**Comment by flaviolee** [comment]
Registrando aqui o que acertamos nas ultimas reuniões:
Esse modelo do codepen https://codepen.io/Michiel/pen/dfejE é que vamos usar como base para nosso loader global, até que sobre um tempo para criarmos algo com nosso próprio logotipo, como sugerido na issue #300 .

## Descrição da animação

Nesse modelo do codepen, basicamente os quadrados se animam um a um num processo de fade in e fade out. Primeiro cada um dos 9 quadradinhos que formam o todo aparecem em separado, e depois somem também um por um no processo inverso. 

O tempo total dessa animação não deve ser maior que 5,5 segundos para o processo todo. Ela pode se manter em loop o quanto for necessário até que a página carregue por completo.

## Aplicação

• Na tela de login, antes de tudo carregar, quanto necessário.
• Em qualquer outra situação onde seja necessário carregar elementos na tela inteira sem que nada já esteja apto a ser exibido.

**Comment by alexandralugli** [comment]
Esse foi o loader global que eu apliquei nossas cores e o Deivis codou para o projeto Bookcover:

![image](https://user-images.githubusercontent.com/8549244/43488243-6b5030a0-94ef-11e8-9299-e9dbf6b9b483.png)

**Comment by alexandralugli** [comment]
@Deivis
