### ISSUE TITLE
Micro interação: loader local

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#829]
Épico: pagarme/roadmap#564

**Contexto**

Precisamos contemplar os cenários de **loaders locais** para apresentarem feedback visual enquanto as informações são carregadas.

**Comment by flaviolee** [comment]
Aqui seria nesses casos, tipo conteudo de cards que levam mais tempo pra carregar, certo?

![image](https://user-images.githubusercontent.com/29930809/43164579-e067ddee-8f67-11e8-88ef-34460d3d5bbf.png)

Sendo isso, será que conseguimos resolver dessa forma?

https://codepen.io/viktorstrate/pen/yoBRLy

Ou acaba sendo o mesmo problema de uma tela inteira no Skeleton State?
@Deivis

**Comment by suzanabueno** [comment]
@Deivis você tava vendo isso já? se sim, poe em In Progress por favor

**Comment by suzanabueno** [comment]
Quando estiver aplicando: por favor adicione também nos botões de Exportar, pois o download pode demorar bastante.

**Comment by uselessdev** [comment]
Dúvidas sobre esses loaders:

Eles são aplicáveis ao `Card` onde pode ocorrer a ação ou carregar dados, depois de determinada ação.

No exemplo de antecipação onde a ação de `Calcular` ocorre no card da esquerda, mas os dados carregados são aplicados no Card da direita, esse Card da direita receberia o loader, certo?
