### ISSUE TITLE
Comprovante de estorno para boleto

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#850]
**Cenário**

Ao gerar o comprovante de estorno de uma transação de boleto, não apresentamos os dados do favorecido.

**Exemplo**
![image](https://user-images.githubusercontent.com/8549244/43475060-f43f5190-94ca-11e8-9418-6b1e6a3451ca.png)

**Requisitos e critérios de aceite**

- [x] Adicionar os dados do favorecido semelhante ao comprovante de estorno de cartão de crédito
- [x] Layout novo para esse tipo de comprovante

**Comment by flaviolee** [comment]
Segue uma primeira versão para solucionar essa questão.
Não sei se algum texto extra é realmente necessário.

![comprovante_de_estorno](https://user-images.githubusercontent.com/29930809/43604839-29ca8304-966d-11e8-84ea-6d052cd3e7c0.jpg)

**Comment by alexandralugli** [comment]
@flaviolee , subi novamente com o ajuste de cor e inseri o mesmo título do comprovante atual:

![image](https://user-images.githubusercontent.com/8549244/43777096-3061bde0-9a28-11e8-9d41-4b8d0a0947e3.png)

Zeplin: https://zpl.io/V0yG05Q
