### ISSUE TITLE
Padronizar telas de configuração

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#851]
## Contexto
Hoje temos configurações em dois cenários: um macro e um dentro de recebedores.

Esses dois layouts podem ser identicos, dado que as informações e funcionalidades são muito próximas.

## Solução
Ajusta as diferenças e deixar as duas telas o mais próxima o possível para seguirmos nosso padrão.

**Comment by oieusouamiguel** [comment]
Você pode detalhar melhor com exemplos do Zeplin (prints e link)? @flaviolee

**Comment by flaviolee** [comment]
Boa!
A questão aqui eram diferenças de layout.

Ja analisamos e padronizamos ao maximo esses dois cenarios.

O resultado final ficou assim:

- Recebedores / Configuracoes

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/29930809/43973988-8a256190-9caf-11e8-95e5-3083dfb365b8.png">

https://zpl.io/29ZJZEB

- Configuracoes

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/29930809/43974045-ad50dd52-9caf-11e8-8c00-0bbc0fb3425a.png">
