### ISSUE TITLE
Micro interação: sidebar

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#854]
Épico: pagarme/roadmap#564

Vou descrever aqui o comportamento do sidebar.

## Descrição da animação
• Seguiremos o mesmo modelo do material design, usando como referencia a Mini Variant Drawer com abertura da esquerda para direita (open left) visto nesse link: https://material-ui.com/demos/drawers/

## Aplicação
• No nosso sidebar, seja no estado fechado ou aberto.

**Comment by flaviolee** [comment]
Exemplo em gif do link acima mostrando o comportamento do componente:
![sidebar](https://user-images.githubusercontent.com/29930809/43543435-5bf1943e-95a6-11e8-80fb-24fdeecf1a9c.gif)

**Comment by miguelssrs** [comment]
Qual seria a melhor abordagem pra utilizar essa animação na Pilot? Vou testar com nosso componente de  `<Transition />` e com css. Porém, se alguém tiver alguma sugestão, é nóis @Deivis @rsmelo @uselessdev @alalbux @vagnervst!
