### ISSUE TITLE
Micro interação: pop over

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#856]
Épico: https://github.com/pagarme/roadmap/issues/564

Vou descrever aqui o comportamento de nossos pop overs.

## Descrição da animação
• Seguiremos o mesmo modelo do material design, visto nesse link: https://material-ui.com/demos/menus/

## Aplicação
• Todos os nossos pop overs

**Comment by flaviolee** [comment]
Gif do link acima para ilustrar movimento e posição do popover:
![popover](https://user-images.githubusercontent.com/29930809/43543174-8b84dd56-95a5-11e8-9399-d89e99847737.gif)

**Comment by Deivis** [comment]
Reaberta só para esperar o deploy da versão do (former-kit)[https://github.com/pagarme/former-kit] que tenha a animação do popover

**Comment by rsmelo** [comment]
o fix do popover está feito neste PR pagarme/former-kit#212

**Comment by Deivis** [comment]
Esta issue só está na espera do lançamento de uma nova versão do `former-kit`

**Comment by rsmelo** [comment]
publicado na versão 0.11.0 do former-kit https://github.com/pagarme/former-kit/releases/tag/0.11.0
