### ISSUE TITLE
Micro interação: snackbar

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#857]
Épico: https://github.com/pagarme/roadmap/issues/564

Vou descrever aqui o comportamento de nossos snackbars, usados para dar feedbacks para os usuários.

## Descrição da animação
• Seguiremos o mesmo modelo do material design, visto nesse link: https://material-ui.com/demos/snackbars/

## Aplicação
• Sempre que os snackbars forem ativados por uma ação do usuário.

**Comment by flaviolee** [comment]
Gifs para facilitar a visualização. São o mesmo contéudo do link lá de cima.

Esse indica o movimento e posição corretos de nossos snackbars:
![snackbar_posicao](https://user-images.githubusercontent.com/29930809/43542408-46e5a466-95a3-11e8-8c8a-2d079427bb6a.gif)

Esse aqui mostra como eles se comportam se mais de um for exibido consecutivamente:
![snackbar_sequencia](https://user-images.githubusercontent.com/29930809/43542434-57709bb0-95a3-11e8-8c9d-c283c3de95c0.gif)

**Comment by alexandralugli** [comment]
Essa issue está sendo tratada pelo time do Caesar: https://github.com/pagarme/caesar/issues/317
