### ISSUE TITLE
Micro interação: modais

### ISSUE THREAD

**Issue by flaviolee** [pagarme/pilot#858]
Épico: https://github.com/pagarme/roadmap/issues/564

Vou descrever aqui o comportamento de nossos modais.

## Descrição da animação
• Seguiremos o mesmo modelo do material design, visto nesse link: https://material-ui.com/demos/dialogs/

@deivis ou quem for pegar isso: aqui vale ver se não faz mais sentido fazermos nossos modais se aparecerem da mesma forma que o descrito na issue #830 .

## Aplicação
• Todos nossos modais.

**Comment by flaviolee** [comment]
Gif da animação contida dentro do link para facilitar a visualização: 
![modais](https://user-images.githubusercontent.com/29930809/43541903-e89ab3fc-95a1-11e8-9490-0d044e391862.gif)

**Comment by suzanabueno** [comment]
@miguelssrs pode clarificar pra gente o que falta para essa task ser finalizada?

**Comment by miguelssrs** [comment]
Issue já foi concluida! https://github.com/pagarme/pilot/pull/1014 🎉

**Comment by suzanabueno** [comment]
Vou manter aberta porque ainda não foi deployada.

**Comment by rsmelo** [comment]
publicado na release https://github.com/pagarme/pilot/releases/tag/v0.8.0
