### ISSUE TITLE
TotalDisplay: Adicionar cor no amount e ajustar fonte

### ISSUE THREAD

**Issue by oieusouamiguel** [pagarme/pilot#874]
### Contexto
Cor: adicionar cor #757575 no amount 
Fonte: ajustar tamanho dos títulos e valores
Background: ajustar cor para #f7f7f7
Espaçamento: Ajuste no espaçamento entre `label` e o valor para 16px

### Exemplo
`master`: 
![image](https://user-images.githubusercontent.com/20358128/43921683-d37cef7e-9bf2-11e8-91d5-846dc47656cf.png)

`Zeplin`:
![image](https://user-images.githubusercontent.com/20358128/43921656-c41eeda2-9bf2-11e8-8636-d6c45b40e96c.png)

Link do Zeplin: https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5ad8dbcced00ed91933463da

### Requisitos e Critérios de Aceite

- [x] Adicionar cor no amount
- [x] Ajustar tamanho dos títulos e valores
- [x] Ajustar cor do background
- [x] Ajuste espaço entre label e valor

**Comment by alexandralugli** [comment]
Orá!

Gostaria de trazer um erro que encontrei aqui:

![image](https://user-images.githubusercontent.com/8549244/44176215-5b8d8880-a0bf-11e8-96aa-085ea2e32b3f.png)

A ordem correta de informações é: valor solicitado > custo da transferência > valor a ser transferido

Tela do zeplin:
![image](https://user-images.githubusercontent.com/8549244/44176237-7102b280-a0bf-11e8-80ef-af13520c3d5b.png)
