### ISSUE TITLE
Não está sendo exibido a mensagem de message erro no modal ManualReview no storybook

### ISSUE THREAD

**Issue by macabeus** [pagarme/pilot#888]
### Contexto

Na página `Manual review result error` do storybook, não aparece a mensagem de erro. O mesmo problema acontece na página `Manual review step result error`.

![image](https://user-images.githubusercontent.com/9501115/44154818-005a8e82-a082-11e8-84d5-7611e761138d.png)

### Descrição técnica

O texto dessa mensagem é gerada pela função [`getErrorMessage`](https://github.com/pagarme/pilot/blob/bbef1836a832cbd2bb28aeefb58f4cf050c6258e/packages/pilot/src/containers/ManualReview/Result/index.js#L16-L22), e utiliza como base a prop [`errorMessage`](https://github.com/pagarme/pilot/blob/bbef1836a832cbd2bb28aeefb58f4cf050c6258e/packages/pilot/src/containers/ManualReview/Result/index.js#L26).

Porem, [essa prop em nenhum momento é passada no story](https://github.com/pagarme/pilot/blob/master/packages/pilot/stories/containers/ManualReview/Result/index.js).

É necessário passar essa prop com uma mensagem adequada, [tal como é feito quando ele é utilizado na Pilot](https://github.com/pagarme/pilot/blob/master/packages/pilot/src/pages/ManualReview/index.js#L29-L35).

**Comment by Deivis** [comment]
Done
