### ISSUE TITLE
Ajustar espaçamentos do svg do logotipo

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#889]
### Contexto

Hoje o svg de nossa logo tem espaçamentos acima e abaixo da parte visível do logo que estão afetendo os espaçamentos que utilizamos por padrão. 
Aparentemente os espaçamentos estão sendo taxados no logotipo via css, sendo assim será necessário revisar estes estilos e ajustar a sua utilização.

### Exemplo

![image](https://user-images.githubusercontent.com/1773766/44235968-c99a8400-a181-11e8-8183-b6592848e895.png)

### Requisitos e Critérios de Aceite

- [ ] Remoção dos espaçamentos superiores e inferiores que estão sobrando no svg.
- [ ] Revisar a utilização do logo sem espaçamentos no sistema.

**Comment by oieusouamiguel** [comment]
Sobre essa issue e já marcando o @macabeus: O nosso SVG se redimensiona à partir do valor que é colocado via props. Se você colocar apenas o valor `width`, ele irá redimensionar o valor `height`. O correto é setar nas props do componente o valor exato de `width` e `height` para que ele não se adapte ao tamanho do `<Header />`.

Essa é a solução mais viável que encontramos.
