### ISSUE TITLE
Telas de arquitetura extrato e transações

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#90]
A tela de extrato e transações principais devem ser liberadas para desenvolvimento de UI

**Comment by IedaOtero** [comment]
Protótipo de baixa fidelidade de Extrato e Transações, desenvolvido com base nas análises do produto atual, pesquisas com o cliente e workshop de cocriação com a equipe interna do Pagar.me (Responsáveis pela Ativação e Relacionamento com o cliente,  Account Managers, Product Owners, Devs, Redatora e UX Designers).

Link: http://vkahme.axshare.com
Senha: eppagarme

PS: Protótipo ainda está desenvolvimento e sendo testado com clientes.
