### ISSUE TITLE
Adicionar status em solicitações recentes

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#900]
**Contexto**

A tela de extrato possui um bloco de solicitações recentes, que é um demonstrativos dos últimos saques, antecipações, etc.

Inicialmente, havíamos pensado em uma área que aparecessem as solicitações pendentes, de forma que o usuário pudesse cancelar essas ações antes que elas fossem aprovadas.

No mvp não subimos essa funcionalidade e causou confusão ao usuário que precisou reverter uma antecipação.

![image](https://user-images.githubusercontent.com/8549244/44414727-edc0e100-a544-11e8-9ae4-681445c72d37.png)

**Resolução**

Precisamos adicionar o status da solicitação e a opção que a cancela enquanto está pendente de aprovação.

**Comment by uselessdev** [comment]
@alexandralugli deixa eu perguntar, a opção de cancelar só deve existir se o status for 'pendente' certo?

**Comment by suzanabueno** [comment]
Antecipação feito, falta o saque, o @uselessdev vai abrir outra issue para acompanhar.
