### ISSUE TITLE
Mapeamento de actions de Extratos e transações

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#91]
Aprofundamento nas ações que derivam de extrato e transações, como saque, antecipação, estorno e reprocessar informação.

**Comment by Fausto-Junior** [comment]
Time, segue a última versão de Extrato e Transações - http://o0wfef.axshare.com 

Senha: eppagarme 

Alguns fluxos e regras ainda precisam ser mapeados. 

Vamos falar na segunda-feira? @derekstavis @alexandralugli @ericksahara @IedaOtero @Evilhideki 

Um abraço.

**Comment by Evilhideki** [comment]
@derekstavis , é possível ter um código autenticador em transações, tipo saque e transferências, que tornem as mesmas únicas?

**Comment by alexandralugli** [comment]
@Fausto-Junior Vamos começar a desenhar as telas de extrato e transações. Quer conversar antes de iniciarmos?

**Comment by Fausto-Junior** [comment]
Vamos conversar @alexandralugli

**Comment by Fausto-Junior** [comment]
Foram feitas algumas atualizações de conteúdo e também alguns ajustes no fluxo de sacar e antecipar.

@derekstavis precisamos definir como exibiremos os valores possíveis para antecipação (dentro do fluxo de antecipar) e também as datas possíveis para essa antecipação.

Outro ponto que precisamos bater é se existe a necessidade de termos uma busca quando o usuário resolve procurar por outras contas (dentro do fluxo de saque).

https://github.com/pagarme/produtos/tree/master/Arquitetura/Extrato%20e%20Transa%C3%A7%C3%B5es/Wireframes/Desktop

Abraços.

**Comment by Evilhideki** [comment]
Pessoal, não esqueçam de dar o output de uma issue, caso vcs tenham alinhado as coisas em uma reunião.

**Comment by mccraveiro** [comment]
@Evilhideki 
> é possível ter um código autenticador em transações, tipo saque e transferências, que tornem as mesmas únicas?

Isso você diz do lado da API? Acredito que ainda não temos, mas podemos implementa algo parecido com a `reference_key` que existe na transação.

**Comment by Evilhideki** [comment]
@mccraveiro na verdade estou mais interessado em **Proof of Transfer or transaction**. Essa é uma demanda dos clientes para operação diária deles. Muitas vezes, eles precisam de um comprovante de estorno ou de transferência, e para ser um comprovante, teríamos que ter um armazenamento de documentos, algo bem parecido com **Bank Financial documentations**. No limite, seria aquele "id"que vc tem no final do comprovante de uma conta paga no banco normal.

**Comment by Fausto-Junior** [comment]
Time, para fecharmos essa issue precisamos definir alguns pontos que ficaram soltos. 

Segue abaixo a lista de pendências: 

**Fluxo de antecipação** 

- Definir como exibiremos os valores possíveis para antecipação.
- Definir as datas possíveis para antecipação. 

**Fluxo de saque**

- Definir se é preciso manter uma busca quando o usuário decide procurar por outras contas. 

É isso, definindo esses pontos podemos fechar a issue. 

@derekstavis

**Comment by mccraveiro** [comment]
@Evilhideki o @greenboxal estava falando outro dia sobre esse comprovante de extorno.
Segundo ele, esse comprovante é uma "mentira" haha.
Acho que vale a pena alinhar isso.
