### ISSUE TITLE
Listagem de funcionalidades de extratos e transações

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#93]
É necessário criar uma listagem de funcionalidades para comparar o que está proposto em protótipos de baixa fidelidade e com as funcionalidades existentes hoje, divergindo entre o que já existe, e evidenciar o que ainda é necessário se criado.

@derekstavis  irá criar uma lista com o que existe hoje
@IedaOtero  junto comigo, faremos uma com o que está feito em proposta

Iremos consolidar as duas listagens.

**Comment by derekstavis** [comment]
Movido para a issue pagarme/produtos#4
