### ISSUE TITLE
Criação de componentes para animação de componentes

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#942]
### Contexto

Hoje na pilot ainda há a falta de algumas animações de feedback para o usuário, e tendo em vista as tecnologias que utilizamos "criei"(compus este componente pegando idéias de diversos lugares) estes componentes sobre a interface **TransitionMotion** do [react-motion](https://github.com/chenglou/react-motion) que é nossa biblioteca padrão para animações. 
Condensei estes exemplos e testes na branch [add/local-loader](https://github.com/pagarme/pilot/tree/add/local-loader) e o resultado desta pesquisa foram as seguintes interfaces:

### Transition
- Hoje esta interface está dentro da pilot, mas creio que deva ser migrada para o former-kit.

- Este componente serve para simplificar a  utilziação do **TransitionMotion** o qual tem uma interface um pouco mais complicada.

- As propriedades recebidas por esta interface fazem com que diversos micro estados sejam criados para um componente com base nos estilos a serem animados e aplicados diretamente na propriedade __style__ do compoenete filho que vai ser animado.

  - __springOptions__: é principal propriedade recebida por este componente e é responsável por ditar a criação dos micro estados que compõem uma animação, ela espera um objeto que contenha as seguintes propriedades:

    - _damping_: Esta propriedade espera um numero que define o amortecimento da animação

    - _precision_: Define o aredondamento e o valor inical da velocidade da animação (normalmente 0.01 é o suficiente), é preciso ter cuidado ao alterar esta campo pois ele influencia diretamente na performance da animação.

    - _stiffness_: Esta prorpiedade define a dureza da animação com base no número recebido.

    A junção destes valores seguindo os algoritmos usados dentro do **TransitionMotion** define qual será a velocidade, quantidade de frames e suavidade da animação.

- As três seguintes propriedades irão representar os estados que ditarão a animação, com base nos objetos redebidos. Estes objetos precisam conter as propriedaedes de estilos que irão gerar a animação com base nos calculos feitos pelo **TransitionMotion**

  - __atEnter__: Esta propriedade precisa conter os estilos inicias do componente ex:
     ``` { width: 0, zIndex: 10, opacity: 0 } ```

  - __atActive__: Esta propriedade representa o estado de ativo do componente filho, sendo assim quando um objeto for "ativado" o seus estilos serão alterados periodicamente (de acordo com os valores da propriedade __springOptions__) até atingirem os valores recebidos nesta propriedade.

  - __atLeave__: Esta propriedade representa o estado posterior ao __atActive__ onde da mesma maneira que temos um objeto que representa os estilos do componente sendo alterado periodicamente. 

- Mais algumas funções disponibilizadas para auxiliar a utilização do componente:

  - __mapStyles__: esta propriedade recebe uma função que será executada sobre o objeto que contém os estilos do componente. Esta função visa apenas fornecer uma maneira de formatar as unidades dos estilos recebidos, mas como se trata de um map ela não impede o usuário de fazer o que bem entender com os estilos recebidos.

  - __didLeave__: propriedade que recebe uma função que será executada após os eventos que levam ao estado final(__atLeave__), em suma depois executa depois que a animação acabou seu ciclo.

  - __runOnMount__: como padrão recebe `false` e como o nome sugere roda a animação no mount do componente.

### LocalLoader

- Componente que engloba a interface **Transition** e fornece uma animação padrão que irá animar a propriedade _overlay_ a qual deve ser um elemento react.

- Este é um __High Order Component__ que encapsula os componentes que receberiam as animações de loading, este encapsulamento é feito por meio de uma `div` com posicionamento relativo que por sua vez englobará os filhos recebidos e o overlay animado.

- Este componente utiliza de uma propriedade chamada __visible__ para ativar ou desativar a animação do loader.

- Há a possibilidade de transformá-lo em um `enhancer` para nossos componentes, para poder adicionar o loader de maneira mais transparente e fazer com que este escute um propriedade **loading** que viria ser recebida pelo componente filho, como já fazemos em alguns casos.

### Exemplo

![localloader](https://user-images.githubusercontent.com/1773766/45783694-e3c1f900-bc3c-11e8-8c8c-832f849c94d2.gif)

#### Trantision
https://github.com/pagarme/pilot/blob/add/local-loader/packages/pilot/src/components/Transition/index.js

#### Local loader
https://github.com/pagarme/pilot/blob/add/local-loader/packages/pilot/src/components/LocalLoader/index.js

Utilização do **LocalLoader**
https://github.com/pagarme/pilot/blob/add/local-loader/packages/pilot/stories/components/LocalLoader/index.js

**Comment by gmbarroso** [comment]
@Deivis testei aqui o componente novo e achei legal termos esse loading novo. Parabéns!
Quanto a comentários técnicos, sei que o time curte muito a utilização do ramda, mas para mim ficou um pouco confuso, no arquivo de `Transition`, todos os ramdas utilizados com exceção do `map`. Nos outros dois arquivos consegui entender de boa o que acontece por serem componentes mais simples.

Sobre o comportamento, posso dar uma sugestão? Ao invés do Spin Load vir de lado aparecendo e depois desaparecer de lado, o que acham de deixar ele apenas aparecendo e desaparecendo, sem a ida e vinda da lateral? Quanto a este último, se ficou confuso a maneira como escrevi, me avisa que tento explicar melhor de outro jeito.

**Comment by uselessdev** [comment]
@gmbarroso ótimo ponto sobre a utilização do Ramda, o que você acha de apontar o que ficou exatamente confuso pra podermos entender como deixar o código mais legível?

**Comment by gmbarroso** [comment]
@uselessdev Vamos lá. Por não manjar muito de ramda, talvez falte a voz da experiência aqui hehe
Logo no começo é realmente necessário o `ifElse`? Pesquisei e entendi o que acontece ali. Só que dentro desse método tem  `ramda` dentro de `ramda` sendo utilizado. E mesmo que muitas linhas de código sejam diminuidas, sinto a falta de uma coisa mais legível, sabe?
Posso estar falando besteira, mas o único arquivo que não entendi foi esse e pode ter sido pelo meu tempo de profissão. Mas pensando que isso fica para a empresa, não seria legal que o entendimento seja facilitado, também?

**Comment by uselessdev** [comment]
@gmbarroso entendi, meu ponto é o seguinte:

Eu acredito que o código deve ser escrito da maneira mais simples possível pra facilitar a integração de pessoas no projeto e facilite a manutenção do mesmo, então eu concordo com você que o código precisa estar legível.

Já a questão da experiência é inevitável que em algumas ocasiões isso acabe pesando, então eu acho muito importante discurtimos esses pontos de legibilidade e sempre que necessário sentar e conversar sobre o código.

No momento, a minha sugestão é sempre que um código ficar imcompreensível é perguntar o que está acontecendo no review ou mesmo chamar a pessoa que escrever e pedir pra explicar, alias eu acho esse tópico ótimo pra gente discutir [aqui](https://github.com/pagarme/pilot/issues/939)

**Comment by gmbarroso** [comment]
@uselessdev boa Wallace!

**Comment by Deivis** [comment]
Boa @gmbarroso, vou tentar dar uma simplificada no código 👍 
em relação a animação a ideia do componente é prover um jeito fácil de fazer qualquer animação, então pra mudar a animação de `slide` para outra coisa fica fácil. Se quiseres podes tentar mudar as propriedades que são passadas no `LocalLoader` para testar 😄

**Comment by otaviopace** [comment]
Achei maneiro o componente! Não cheguei a testar, somente vi o exemplo e li o código. Quanto ao ponto de legibilidade, concordo que quanto mais pessoas entenderem melhor. Mas por exemplo, a parte do ramda eu entendi, mas a parte do `React`, nem tanto haha. O problema é que eu não tenho muito conhecimento de `React`. Então se me perguntar como esse componente funciona, não vou saber dizer, apesar de saber o que alguns pedacinhos parecem estar fazendo (partes em ramda).

**Comment by otaviopace** [comment]
Inclusive, concordo que algo assim deveria estar no `former-kit`.

**Comment by tisoap** [comment]
Pergunta: qual a vantagem de termos nossos próprios componentes de animação em vez de utilizar uma biblioteca pronta? O tempo de desenvolvimento que será gasto nisto compensa?

Também achei o uso dessas provas de conceito difíceis de entender. Limitaria a quantidade de pessoas capazes de utilizar e dar manutenção a estes componentes.

**Comment by uselessdev** [comment]
@tisoap estamos usando uma lib, o que foi feito é um `wrapper` pra simplificar a interface pública

**Comment by Deivis** [comment]
Estes componentes já são a simplificação de uma lib te terceiros @tisoap, objetivo é deixar a criação de animações em componentes react mais simples :smile: apesar de ainda não ter atingido este objetivo de simplificação.

**Comment by tisoap** [comment]
Caramba, animação é difícil mesmo então... Vou dar uma olhada na biblioteca principal para poder formar uma opinião melhor.

**Comment by Deivis** [comment]
Este é um ponto bem interessante @otaviopace, acho que o ramda não deve ser obrigatório, mas também não deve ser negligenciado pois hoje já temos uma boa codebase. O ponto que o @gmbarroso colocou é que o que utilizei de `ramda` era um pouco complexo de mais, e com isso concordo, simplificar a leitura sempre é essencial.

**Comment by uselessdev** [comment]
Eu concordo com o @Deivis que não devemos negligenciar o ramda, muitas coisas que fazemos com ramda hoje ficaria muito mais complexo escrito com vanilla, talvez a forma como foi escrita ficou um tanto confuso, mas isso pode ser resolvido separando mais a parte do ramda em micro funções bem nomeadas por exemplo.

**Comment by Deivis** [comment]
Sim, foi bem isso que fiz no ponto que o @gmbarroso  não entendeu, separei mais as funções e simplifiquei elas.

**Comment by Deivis** [comment]
@gmbarroso  se puderes dá uma olhada neste PR também, movi a parte de transition para o `former-kit` https://github.com/pagarme/former-kit/pull/200  para poder utilizar isso também nos componentes como popover :smile: .
