### ISSUE TITLE
Componente de formulário adição de cliente

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#951]
### Contexto

Este componente deve permitir a adição de um novo clinente no inicio de uma transação.

### Exemplo

Link para a modelo no zeplin https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5ba96848b285705d9c51994d

O formulário:
![screenshot from 2018-09-25 14-18-55](https://user-images.githubusercontent.com/1773766/46030981-0c7b4000-c0ce-11e8-8fe1-2d7732361ccc.png)

### Descrição técnica

```jsx
<ClientForm
  customer={{
    name: '',
    email: '',
    externalId: '',
    type: '',
    phone: '',
    document: '',
  }}
  onCancel={() => null}
  onChange={() => null}
  onSubmit={() => null}
  t={t => t}
/>
```

### Requisitos e Critérios de Aceite

- [x] Passar os dados do cliente a ser criado para a função de `submit` corretamente.
- [x] Disparar a função de voltar corretamente quando o botão `voltar` for clicado.
- [x] Submeter formulário quando o botão continuar for clickado.
- [x] Validar o formato de email.
- [x] Validar campos de  CPF e CNPJ separadmente.
- [x] Validar o formato do telefone informado.
- [x] Validar a obrigatoriedade dos campos: `Nome do cliente`, `Telefone`, `E-mail`, `Documento`

**Comment by uselessdev** [comment]
@Deivis acredito que esses dois primeiros items devem ser responsabilidade do container principal não?

**Comment by Deivis** [comment]
Sim e não @uselessdev, pois no frigir dos ovos isso é responsabilide da página e do container more, a ideia ali é passar os valores certos para as funções de submit e back(caso precise de algum valor).

**Comment by rsmelo** [comment]
@uselessdev atualizei essa issue com os parametros esperados

**Comment by rsmelo** [comment]
percebi que essa tela não prevê o campo `country` que hoje é obrigatorio na API https://docs.pagar.me/reference#criando-um-cliente

**Comment by rsmelo** [comment]
@alexandralugli

**Comment by uselessdev** [comment]
resolved in #981
