### ISSUE TITLE
Componente de seleção de cliente

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#952]
### Contexto

Este componente deve permitir a selcção de um cliente já cadastrado na adição de uma transação.

### Exemplo

Link do zeplin:
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5ba96849b285705d9c519a11

O componente:
![screenshot from 2018-09-25 14-41-04](https://user-images.githubusercontent.com/1773766/46032093-1488af00-c0d1-11e8-9d1c-654283ba27be.png)

### Descrição técnica

```
<CustomerSelection
  customers={[]}
  onCancel={() => null}
  onSelect={() => null}
  onSubmit={() => null}
  selected={null}
/>
```

### Requisitos e Critérios de Aceite

- [x] Deve permitir a seleção de um cliente cadastrado
- [x] Deve permitir filtrar os usuários listados por nome ou email
- [x] Deve permitir a paginação dos itens mostrados na tabela

**Comment by tisoap** [comment]
É possível generalizar este componente de forma que seja possível selecionar um dado genérico? Como contas bancárias por exemplo :grin:

**Comment by uselessdev** [comment]
@tisoap é sim, aliás faz bastante sentido, só vou precisar de alguns minutos pra renomear tudo :joy:

**Comment by rsmelo** [comment]
@uselessdev 

> filtrar os usuários listados ficou confuso pra mim, o campo de busca é pra fazer uma request nova na API certo? ou é pra filtrar pelos items que já estão no state?

sempre fazendo request a api, porem isso sera feito na page, aqui so recebe as funćões 

> Essa paginação também é da API correto?

Exatamente, pela api sempre

**Comment by uselessdev** [comment]
resolved in #987
