### ISSUE TITLE
Espaço entre cards e dentro de cards

### ISSUE THREAD

**Issue by oieusouamiguel** [pagarme/pilot#968]
### Contexto
Na `master`, os espaços entre cards estão em `padding-left: 24px` e `padding-bottom: 24px` e `padding: 16px;` dentro dos cards. Precisa inverter os valores pra `padding: 16px` entre cards
`padding: 24px` dentro de cards.

### Exemplo
Zeplin: https://zpl.io/VDn3DqW

### Requisitos e Critérios de Aceite
- [x] `padding: 16px` entre cards
- [x] `padding: 24px` dentro de cards

**Comment by alexandralugli** [comment]
Lembrando que: alguns cards específicos terão seus próprios espaçamentos, mas são bem exceção. :)
