### ISSUE TITLE
agendamento e recrutamento de clientes para teste final de extratos e transações

### ISSUE THREAD

**Issue by Evilhideki** [pagarme/pilot#97]
Essa issue descreve os clientes que já visitamos e os feedbacks deles.

Eduzz; **(06/09 - agendado)**
Empório da cerveja; **(13/09 - agendado)**
Por dentro da História; **(13/09 - agendado)**
Estratégia Concursos; **(19/09 - agendado)**
CER Educacional **(20/09 - agendado)**
Unileya _**_(20/09 - Agendado)_**_
Print. **(20/09 - Agendado)**

**Comment by felquis** [comment]
@Evilhideki achei que não iamos citar nomes de empresas pro aqui.

**Comment by Evilhideki** [comment]
@felquis , você está completamente certo. My bad. Tks! =)
