### ISSUE TITLE
Ajustar a o formato de datas utilizado em antecipações

### ISSUE THREAD

**Issue by Deivis** [pagarme/pilot#972]
### Contexto

Hoje na utima [versão de testes](https://beta.dashboard.sandbox.stg.pagarme.net/latest/) e na última [versão de produção](https://beta.dashboard.stg.pagarme.net/latest/) publicadas da pilot estamos com a data da antecipação utilizando o padrão `MM/DD/YYYY` quando deveriamos utilizar o padrão `DD/MM/YYYY`, acho válida a verificação de qual linguagem o `moment.js` está recebendo na página.

### Exemplo

![erro datas](https://user-images.githubusercontent.com/1773766/46102094-ea53f180-c1a3-11e8-99d9-8ddedf7c5478.gif)

### Descrição técnica

Acho válida a verificação da linguagem setada no `moment.js` para a página e também no componente [CalendarInut](https://github.com/pagarme/former-kit/tree/master/src/CalendarInput) em sí, pois por algum motivo estranho ele pode não estar obedecendo a página.

### Requisitos e Critérios de Aceite

- [ ] Mostrar as datas no formato `DD/MM/YYYY` ao invés de `MM/DD/YYYY`

**Comment by rsmelo** [comment]
bloqueado aguardando a conclusão da issue #1084
