### ISSUE TITLE
Calculo do valor de antecipação ao alterar  a ordem de antecipação 

### ISSUE THREAD

**Issue by rsmelo** [pagarme/pilot#982]
### Contexto

Na tela de antecipação ao alterar a ordem de antecipação (timeframe) o novo valor é sempre calculado com base no menor valor antecipavel ignorando qualquer input que tenha sido feito pelo usuário

### Exemplo

![timeframe](https://user-images.githubusercontent.com/479495/46231993-1b6b2800-c344-11e8-8a6b-1543680e6ede.gif)

### Descrição técnica
Seria interessante utilizar o valor já digitado pelo usuário para o calculo de antecipação se possível. É necessário testar para ver no que isso implica na tela. Atualmente é usado o valor mínimo para garantir que será um valor possível de antecipação.

**Comment by rsmelo** [comment]
bloqueado aguardando a conclusão da issue #1084

**Comment by rsmelo** [comment]
talvez no ultimo refactor de antecipação isto já tenha sido resolvido, verificar antes de executar a issue

**Comment by miguelssrs** [comment]
Aparentemente, foi consertado já! :tada: 
![Apr-02-2019 14-28-54](https://user-images.githubusercontent.com/20358128/55423259-e7bbc580-5553-11e9-9b9a-e12e61122db4.gif)
